== Al Lector

La mayoría de los hombres reconocerá que las primeras iglesias,
a quienes Pablo escribió sus epístolas,
superaban en muchos aspectos a los profesantes del cristianismo en nuestra presente edad;
y tienen buenos motivos para creerlo así. Porque dicho apóstol, en sus epístolas,
les dijo a los corintios que sus cuerpos eran templo del Espíritu Santo;^
footnote:[Ver 1 Corintios 6:19]
les dijo a los Efesios que eran conciudadanos de los santos,
y miembros de la familia de Dios;^
footnote:[Ver Efesios 2:19]
les dijo a los Filipenses que su ciudadanía estaba en los cielos;^
footnote:[Ver Filipenses 3:20]
les dijo a los Colosenses que habían sido librados de la potestad de las tinieblas,
y trasladados al reino del amado Hijo;^
footnote:[Ver Colosenses 1:13]
les dijo a los Hebreos que habían sido acercados a la ciudad del Dios vivo,
Jerusalén la celestial.^
footnote:[Ver Hebreos 12:22]
Y Pedro, en su epístola general a las iglesias, les dijo que ellos eran linaje escogido,
real sacerdocio, nación santa, pueblo adquirido por Dios.^
footnote:[Ver 1 Pedro 2:29]

¿Pero es este nuestro estado?
¿Podemos decir, desde un desde un sentir vivo y perceptible,
que el Espíritu Santo mora en nosotros?
¿O que nuestros cuerpos son los templos en los cuales podemos contemplar Su presencia,
sentir Su poder, y temerle, adorarle y servirle?
¿Podemos decir que nuestra ciudadanía está en los cielos?
¿Que hemos sido trasladados al reino del amado Hijo de Dios,
y vivimos bajo el cetro de Su gobierno?
¿Que hemos llegado a la Jerusalén celestial,
donde el gran Dios es adorado en Espíritu y en verdad?
¿O somos más bien extraños a todas estas cosas,
y aun así nos persuadimos a nosotros mismos de que
somos el pueblo de Dios y buenos cristianos?

Las primeras iglesias tenían el honorable nombre de santos; nosotros, a menudo,
no podemos darnos un mejor nombre que el de "`miserables pecadores;`"^
footnote:[El Libro de Oración Común, de la Iglesia de Inglaterra]
y ¿cuál es la razón? La mayoría de los miembros de las iglesias mencionadas,
antes de su conversión, no eran más que paganos;
no habían nacido de padres cristianos ni habían sido instruidos en la fe cristiana,
como pensamos nosotros que lo somos.
Y después de su conversión,
apenas tenían predicación en comparación con la que tenemos ahora;
ni estaban tan abundantemente provistos de libros como nosotros hoy.

No podemos concluir que el reino de Cristo, que entonces apareció con poder,
se mostrara en la mañana y no se dejara ver el resto
del día (como hace a veces el sol natural);
porque el reino de Cristo es un reino eterno,
y el nuevo pacto que fue hecho con la casa de Jacob es un pacto eterno.
Tampoco podemos concluir que Dios se haya apartado de los hijos de los hombres,
porque Él nunca nos abandona, a menos que primero Lo abandonemos.

Los apóstoles previeron que habría una apostasía de la gracia
en la que muchos de los primeros cristianos se establecerían;
lo cual aconteció poco después de su fallecimiento.
Pero nuestros predicadores dicen: "`La noche oscura de la apostasía ha terminado,
y vivimos de nuevo en los días del evangelio.`"
Pero si fuera así, ¿dónde están los frutos?
Es cierto que podemos escuchar las palabras del evangelio;
pero ¿dónde está el poder del evangelio mediante
el cual los creyentes llegan a ser hijos de Dios,
y a llevar Su imagen en justicia?
¿Por qué nosotros, que somos llamados cristianos,
no hemos crecido a la estatura de aquellos que nacieron
paganos y fueron criados en ceguera e ignorancia?
¿Por qué no somos santificados, y hechos un pueblo santo como lo fueron ellos?
¿Por qué nuestros cuerpos no son limpiados y convertidos
en morada para el Espíritu eterno,
como fueron los de ellos?
¿Por qué nuestra ciudadanía no está en los cielos,
o por lo menos nuestras vidas más celestiales de lo que son?
La razón para mí es esta:
no hemos edificado sobre el mismo fundamento sobre el cual ellos edificaron.
Porque hay algo que debemos entender:
los paganos no tenían las Escrituras como las tenemos nosotros, y por lo tanto,
no podían establecer una "`apariencia de piedad`"^
footnote:[2 Timoteo 3:5]
a partir de ellas, como muchos lo han hecho desde entonces, compuesta de buenas palabras,
llamándola piedad y descansando en prácticas externas,
sin una verdadera conversión o experiencia de esa vida y poder interno que los primeros
cristianos llegaron a sentir y a encontrar en sí mismos mediante la fe,
con la operación del eterno Espíritu vivificante de Jesucristo.

Los paganos, al igual que los demás,
eran hombres y mujeres creados por Dios ("`pues de
una sangre ha hecho todo el linaje de los hombres`"^
footnote:[Hechos 17:26]), por lo tanto, tenían en sí mismos,
como tienen todos los demás, una semilla de Su reino (una medida de gracia,
un talento celestial o mina), junto con la semilla o espíritu del maligno.^
footnote:[Con esta afirmación,
Hugh Turford está lejos de sugerir que todo hombre _nace_ de gracia,
o _es salvado_ por esta semilla o talento celestial.
Ni él, ni ninguno de los primeros Amigos,
fueron partidarios de la reconciliación universal.
Sin embargo, creían que cierta medida de la gracia de Dios se
ofrece a toda la humanidad en su condición caída,
incluso antes de la venida de Cristo en la carne.
Sin tal don,
"`todo designio de los pensamientos del corazón del hombre es de
continuo solamente el mal`" (Génesis 6:5). Pero por él,
Dios "`contiende en el hombre`" (Génesis 6:3 Traducción Literal),
convenciéndolo de pecado y llamándolo al Dios de justicia.
Creían que este era el don, o la "`Simiente de la mujer`" (Génesis 3:15),
que fue hallada y seguida por Abel, Set, Enoc, Noé,
Abraham y muchos otros que "`hallaron gracia ante los ojos de Jehová`" (Génesis 6:8),
incluso antes de que se diera una ley, o de que un Salvador se manifestara en la carne.
Este es el don o luz que "`alumbra a todo hombre que viene
a este mundo`" (Juan 1:9) y los llama fuera de las tinieblas.
Es una Semilla que se siembra en todo tipo de tierra (Mateo 13:1-9).
Es la "`gracia que se ha manifestado a todos los hombres`" (Tito
2:11). Es la razón por la que Pablo podía decir:
"`lo que se conoce acerca de Dios es evidente dentro de ellos,
pues Dios se lo hizo evidente.`"
(Romanos 1:19 LBLA), y por la que Jesús podía decir:
"`la luz vino al mundo +++[+++y no solo a Israel+++]+++,
pero los hombres amaron más las tinieblas que la luz`" (Juan 3:19).
Esta es la "`Palabra cerca en el corazón y en la boca`" (Deuteronomio
30:14) de la que Moisés dijo a Israel que no estaba lejos de ellos,
y es la razón por la que Salomón nos dice que Dios "`puso la eternidad en el corazón
del hombre`" (Eclesiastés 3:11). Los Amigos creían que este don llega a todos,
invita a todos, pero solo salva a aquellos que, por fe,
entregan su vida en la carne para seguirlo.]
De este modo, conocían lo bueno así como lo malo; la luz así como las tinieblas;
algo que los reprendía por el pecado, así como también algo que los tentaba a pecar.
Y siendo, por el apóstol, vueltos de las tinieblas que había en ellos a la luz,^
footnote:[Hechos 26:18]
de aquello que los tentaba a pecar,
a aquello que los condenaba y reprendía por el pecado, se aferraron a eso,
confiaron en eso, y se convirtieron en sus seguidores.
Y al aferrarse a lo bueno, fueron librados del mal;
al seguir la luz de Cristo fueron trasladados del reino de las tinieblas,
y obtuvieron su ciudadanía en los cielos, aun mientras estaban sobre la tierra.

Estos edificaron sobre una roca estable, sobre un cimiento vivo,
sobre Cristo--tal como Él ha sido en todas las edades y sigue siendo--sobre
Su aparición espiritual como la luz del mundo y la vida de justicia.
Y tomando en sí mismos Su Espíritu eterno como guía,
se apartaban de todo aquello de lo que eran condenados y reprendidos.
Así Esaú (o la primera naturaleza) era suplantado,
y Aquel a quien pertenece el derecho de reinar,
tenía el dominio y el gobierno sobre ellos.
Y a medida que las tinieblas (que habían eclipsado el resplandor
del Sol de justicia en ellos) eran eliminadas,
crecían en un claro discernimiento de lo que era de Dios,
y también de lo que era egoísta y debía ser negado;
y volviéndose de cada intención que no provenía de Dios,
el cuerpo del pecado era crucificado, su interior era limpiado,
y toda la masa se iba leudando.
De esta manera, los que eran carnales se volvían espirituales,
convirtiéndolos en "`un pueblo propio`"^
footnote:[Tito 2:14; 1 Pedro 2:9]
de Dios.

Y si tan solo anduviéramos en sus pasos, alcanzaríamos sus logros;
pero si edificamos sobre palabras y servicios externos, sin el Espíritu y sin vida,
nunca podremos crecer.
Porque, como dijo Pablo en otro caso: que aunque hablásemos lenguas humanas y angélicas,
pero no tenemos amor, venimos a ser como metal que resuena,
o címbalo que retiñe. Así digo yo en este caso:
que aunque escuchemos las predicaciones de los hombres y de los ángeles,
y vivamos continuamente bajo el sonido de palabras buenas,
si no atendemos a esa luz interna que descubre el surgimiento de las malas intenciones,
y otorga el poder de Dios para apartarse de ellas, nunca podremos hacer morir el pecado,
limpiar nuestras almas y llegar a ser una nación santa.
La obra de santificación es interior,
y tiene que ser llevada a cabo por medios interiores.
Nada, excepto la luz interior puede echar fuera las tinieblas interiores;
nada menos que la luz eterna puede librar nuestras almas del poder de la muerte.

Pero desde que los hombres llegaron a convencerse de que, aunque siembren cizaña,
todavía recogerán trigo, y aunque desciendan a la tumba como pecadores,
aun así se levantarán santos,
y alcanzarán en otro mundo lo que los primeros cristianos alcanzaron en este mundo;
desde entonces, yo digo, la ciudadanía de los cristianos no ha estado en los cielos,
sino en la tierra.
Han andado en tinieblas y no en la luz; el dios de este mundo ha sido servido,
y no el Dios del cielo.
Y qué felicidad futura puede producir esto, dejemos que el sabio de corazón lo juzgue.

[.signed-section-signature]
Hugh Turford
