== Al Lector

La mayoría de los hombres reconocerá que las primeras
iglesias a las cuales Pablo escribió sus epístolas,
superaron en muchos aspectos a los profesantes del Cristianismo en nuestra presente era;
y tienen buenos motivos para creer esto.
Porque en sus epístolas, dicho apóstol les dijo a los Corintios,
que sus "`cuerpos eran templo del Espíritu Santo;`"^
footnote:[1 Corintios 6:19]
les dijo a los Efesios que "`eran conciudadanos de los santos,
y miembros de la familia de Dios;`"^
footnote:[Efesios 2:19]
les dijo a los Filipenses que su "`ciudadanía está en los cielos;`"^
footnote:[Filipenses 3:20]
les dijo a los Colosenses que habían sido "`librados de la potestad de las tinieblas,
y trasladados al reino de su amado Hijo;`"^
footnote:[Colosenses 1:13]
les dijo a los Hebreos que se habían acercado "`a la ciudad del Dios vivo,
Jerusalén la celestial.`"^
footnote:[Hebreos 12:22]
Y Pedro, en su epístola general a las iglesias,
les dijo que ellos eran "`linaje escogido, real sacerdocio, nación santa,
pueblo adquirido por Dios.`"^
footnote:[1 Pedro 2:29]

Sin embargo, ¿es este nuestro estado?
¿Podemos decir, desde un sentir vivo y perceptible,
que el Espíritu Santo mora en nosotros?
¿O que nuestros cuerpos son los templos en los cuales podemos contemplar Su presencia,
sentir Su poder, y temerle, adorarle, y servirle?
¿Podemos decir que nuestra ciudadanía está en los cielos?
¿Que hemos sido trasladados al reino del amado Hijo de Dios,
y vivimos bajo el cetro de Su gobierno?
¿Que hemos llegado a la Jerusalén celestial,
donde el gran Dios es adorado en Espíritu y en verdad?
O, por el contrario, ¿somos ajenos a todas estas cosas,
y sin embargo nos persuadimos a nosotros mismos de que somos el pueblo de Dios,
y buenos cristianos?

Las primeras iglesias tenían el honorable nombre de santas;
nosotros a menudo no podemos darnos un mejor nombre que el de "`miserables pecadores;`"^
footnote:[__El Libro de Oración Común,__ de la Iglesia de Inglaterra]
y ¿cuál es la razón? La mayoría de los miembros de las iglesias mencionadas anteriormente,
antes de su conversión, no eran más que paganos;
no nacieron de padres Cristianos ni fueron educados en la fe Cristiana,
como nosotros creemos que somos.
Y después de su conversión escuchaban muy pocos sermones
en comparación a lo que tenemos ahora;
ni estaban tan abundantemente equipados con libros como nosotros.

No podemos concluir que el reino de Cristo, que entonces apareció con poder,
se mostraba en la mañana y no se dejaba ver el resto
del día (como hace el sol natural a veces);
porque el reino de Cristo es un reino eterno,
y el nuevo pacto que fue hecho con la casa de Jacob es un pacto eterno.
Ni podemos concluir que Dios se ha apartado de los hijos de los hombres,
porque Él nunca nos abandona, a menos que primero Lo abandonemos.

Los apóstoles previeron que habría una apostasía de la gracia,
en la que muchos de los primeros Cristianos se establecerían;
lo cual aconteció poco después de su fallecimiento.
Pero nuestros predicadores dicen, "`La noche oscura de la apostasía ha terminado,
y vivimos de nuevo en los días del evangelio.`"
Pero si fuera así, ¿dónde están los frutos?
Es cierto que podemos escuchar las palabras del evangelio;
pero ¿dónde está el poder del evangelio por el cual
los creyentes llegan a ser hijos de Dios,
y llevan Su imagen en justicia?
¿Por qué nosotros, que somos llamados Cristianos,
no crecemos a la estatura de aquellos que nacieron
Paganos y fueron criados en ceguera e ignorancia?
¿Por qué no somos santificados, y hechos un pueblo santo, al igual que ellos?
¿Por qué nuestros cuerpos no son limpiados y convertidos
en morada para el Espíritu eterno como los de ellos?
¿Por qué nuestra ciudadanía no está en los cielos,
o por lo menos nuestras vidas más celestiales de lo que son?
La razón para mí es esta:
no hemos edificado sobre el mismo fundamento sobre el cual ellos edificaron.
Porque hay algo que debemos entender--los Paganos
no tenían las Escrituras como las tenemos nosotros,
y por lo tanto, no podían establecer a partir de ellas una "`apariencia de piedad`"^
footnote:[2 Timoteo 3:5], como muchos lo han hecho desde entonces,
compuesta de buenas palabras, llamándola santidad, y descansando en prácticas externas,
sin una verdadera conversión o experiencia de esa vida y poder interno,
que los primeros Cristianos llegaron a sentir y a
encontrar en sí mismos a través de la fe,
mediante la operación del eterno Espíritu vivificante de Jesucristo.

Los Paganos, al igual que otros,
eran hombres y mujeres creados por Dios (siendo hecho
todo linaje de los hombre de una sangre),
y por ende tenían en sí mismos, como tienen todos los demás,^
footnote:[Ver Juan 1:9, Tito 2:11, Romanos 1:19, Juan 3:19, Miqueas 6:8,
Eclesiastés 3:11.]
una semilla de Su reino (una medida de Su Espíritu, un talento celestial o mina),
como también la semilla o espíritu del maligno.
Así que ellos conocían lo bueno y lo malo; tanto la luz como la oscuridad;
algo que los reprobaba por el pecado; así como algo que los tentaba a pecar.
Y siendo, por el Apóstol, vueltos de las tinieblas que había en ellos, a la luz^
footnote:[Hechos 26:18]
de aquello que los tentaba a pecar, a eso que los condenaba y reprobaba por el pecado,
se aferraron a eso, se afianzaron en eso,
y por lo tanto se convirtieron en seguidores de eso mismo.
Entonces al aferrarse al bien, fueron librados del mal; al seguir la luz de Cristo,
llegaron a ser trasladados del reino de las tinieblas;
y a tener su ciudadanía en los cielos, incluso mientras estaban en la tierra.

Estos edificaron sobre una roca estable, sobre un cimiento vivo,
sobre Cristo como Él ha sido en todas las eras, y sigue siendo--es decir,
sobre Su aparición espiritual como la luz del mundo, y como la vida de justicia.
Y tomando Su Espíritu eterno en sí mismos como su guía,
rechazaron todo aquello por lo que fueron condenados y reprendidos.
Así Esaú (o la primera naturaleza) llegó a ser suplantado,
y Aquél cuyo derecho es reinar,
llegó a tener el dominio en ellos y el gobierno sobre ellos.
Asimismo,
a medida que la oscuridad (que había eclipsado el resplandor
del Sol de justicia en ellos) llegó a ser eliminada,
ellos llegaron a tener un discernimiento claro de lo que era de Dios,
y también lo que era egoísta y que por lo tanto debía ser negado;
y volviéndose de cada intención del corazón que no provenía de Dios,
el cuerpo del pecado fue crucificado, su interior fue limpiado,
y toda la masa fue leudada.
De esta manera, aquellos que eran carnales, se volvieron espirituales,
y esto los convirtió en "`un pueblo propio`"^
footnote:[Tito 2:14; 1 Pedro 2:9]
de Dios.

Y si tan sólo camináramos en sus pasos, alcanzaríamos su logro;
pero si edificamos sobre palabras, y servicios externos sin el Espíritu y vida,
nunca podremos crecer.
Porque, como dijo Pablo en otro caso--que aunque habláramos lenguas humanas y angélicas,
pero no tenemos amor, llegamos a ser como metal que resuena,
o címbalo que retiñe--asimismo, digo en este caso,
que aunque escucháramos las predicaciones de los hombres y de los ángeles,
y viviéramos continuamente bajo el sonido de palabras buenas,
pero no tomáramos en cuenta a esa luz interna que
descubre el surgimiento de las malas intenciones,
y otorga el poder de Dios para apartarse de ellas, nunca podríamos hacer morir el pecado,
limpiar nuestras almas, y volvernos una nación santa.
La obra de santificación es interna, y tiene que llevarse a cabo por un medio interno.
Nada, excepto la luz interna, puede echar fuera la oscuridad interna;
nada menos que la luz eterna puede librar nuestras almas del poder de la muerte.

Pero desde que los hombres llegaron a ser convencidos de que, aunque siembren cizaña,
recogerán trigo, y que, aunque desciendan a la tumba como pecadores,
aún así ellos se levantarán santos,
y alcanzarán en otro mundo lo que los primeros cristianos alcanzaron en este mundo;
desde entonces, yo digo, la ciudadanía de los Cristianos no ha sido en los cielos,
sino en la tierra.
Ellos han caminado en oscuridad y no en la luz; el dios de este mundo ha sido servido,
y no el Dios del cielo.
Y ¿qué felicidad futura puede producir esto?
Dejemos que el sabio en el corazón juzgue.

[.signed-section-signature]
Hugh Turford
