== Capítulo I. Andar en el Espíritu

Pablo, en su epístola a los Gálatas, capítulo 5:16, dice: "`Andad en el Espíritu;
y no cumpliréis las concupiscencias de la carne.`"^
footnote:[Reina Valera 1602 Purificada]
Y en su epístola a los Romanos, capítulo 8:13, dice:
"`Porque si vivís conforme a la carne, moriréis;
mas si por el Espíritu hacéis morir las obras de la carne,
viviréis.`" Si alguna vez las Escrituras fueron escritas para nuestro aprendizaje,
estas lo fueron; porque mucho se puede aprender de ellas.
El fin de la predicación--tanto en nuestra edad presente como en todas las edades
pasadas--ha sido que los hijos e hijas de los hombres puedan así aprender a negar,
rechazar y abandonar toda obra mala, y llegar a vivir una vida sobria,
justa y santa en este mundo presente,
a fin de que tengan paz con Dios en sus propias conciencias
en este mundo y vida eterna en el venidero.

Ahora, para llevar a cabo esta gran obra,
en la cual miles de obreros han estado empleados por muchos años,
el apóstol da esta exhortación: "`Andad en el Espíritu,`" afirmándoles a los Gálatas que,
si ellos andaban en el Espíritu, no cumplirían los deseos de la carne;
no cederían ante las malas intenciones, ni satisfarían sus deseos carnales,
lo cual es la única manera de hacer morir las obras
de la carne y curar todas las enfermedades espirituales.
Pero este camino de la salvación de Dios ha sido rechazado por tanto tiempo,
que pocos en nuestra edad actual saben _qué_ es este Espíritu, _dónde_ pueden conocerlo,
o _cómo_ pueden andar en él. Por lo tanto,
para que nuestro entendimiento pueda ser abierto en este gran asunto, consideremos:

[.numbered-group]
====

[.numbered]
1+++.+++ Qué era Pablo y cómo llegó a ser ministro del evangelio.

[.numbered]
2+++.+++ Qué clase de personas eran los destinatarios de sus epístolas.

[.numbered]
3+++.+++ A qué se refiere el apóstol con los términos "`carne`"
y "`espíritu,`" y qué significa andar conforme a ellos.

[.numbered]
4+++.+++ Qué debemos entender por las palabras "`morir`" y "`vivir.`"

[.numbered]
5+++.+++ Cómo podemos, por medio del Espíritu, hacer morir las obras de la carne.

====

[.blurb]
=== ¿Qué era Pablo y cómo llegó a ser ministro del evangelio?

Al leer las Escrituras podemos encontrar, que Pablo era un israelita,
de la simiente de Abraham, educado como un erudito, bien instruido en la ley.
En cuanto a su religión, era fariseo.
Y, ¿qué eran los fariseos?
No eran personas livianas ni profanas;
sino (en apariencia externa) un pueblo muy religioso,
celoso de su templo y sus servicios, y de muchas otras observancias externas;
tanto que Jesús dijo de ellos, que limpiaban "`lo de fuera del vaso y del plato,`"^
footnote:[Mateo 23:25; Lucas 11:39]
algo que pocos hacen ahora.

Pero cuando se acercó el tiempo en el que Dios ya
no sería adorado en templos hecho de manos,
sino que habitaría y sería adorado en corazones santificados;
y cuando las leyes que aquel gran profeta Moisés escribió para
que la casa de Israel las guardara y anduviera conforme a ellas,
ya no serían la regla de justicia,
sino que los judíos y los gentiles debían andar por una
ley que procedía del Espíritu de Dios en lo íntimo;
y cuando Uno mayor que Moisés llegó proclamando que el reino se había acercado,
que consistía en una justicia más excelente que la de ellos,
testificando ante los rostros de esos adoradores externos que,
a pesar de su gran celo por el templo y sus servicios,
no eran más que hipócritas y guías ciegos; entonces,
los gobernantes de este pueblo se ofendieron grandemente.
Y teniendo un espíritu perverso dentro de ellos,
a pesar de su apariencia de justicia externa,
se esforzaron por detener la venida de ese reino
matando al Príncipe y encarcelando a Sus súbditos.
Y en esta persecución nadie fue más activo que Pablo,
asolando a la iglesia de Dios sin medida, y tratando de destruirla.

Pero en el apogeo de su persecución, no fue el hombre, sino Dios,
quien puso fin a su proceder; mostrándole que no perseguía a los hombres,
_sino a Cristo en los hombres._
Y de hecho, esto era verdad, porque si Cristo, por Su Espíritu eterno,
no hubiera estado en los hombres a quienes Pablo perseguía,
abriendo los ojos de sus entendimientos para ver
el vacío de todas las sombras y apartándolos de ellas,
Pablo no habría tenido nada que decirles.
Pero viendo que ellos se inclinaban a adorar a Dios en Espíritu,
y así descuidaban la adoración del templo,
Pablo los consideraba un pueblo que no era digno de vivir.

Pero agradó a Dios revelar en Pablo el mismo Cristo que había perseguido en otros;
y esta revelación, o conocimiento interior de Cristo,
fue el fundamento de todo el conocimiento de Pablo en el misterio de la piedad.
Sus futuras enseñanzas no provendrían de hombres ni de libros,
sino de la operación del Espíritu eterno de Jesús
en él. Y permaneciendo en la guía de ese Espíritu,
crecía en gracia; y a medida que crecía en gracia, crecía en el conocimiento de Cristo.
Así que,
no subió a Jerusalén para recibir instrucciones u
órdenes de los que eran apóstoles antes que él,
sino que, en la fortaleza del Señor,
con un libro de experiencia en su corazón en lugar de una Biblia en su mano,
fue a Arabia para predicar el evangelio a los paganos.
¿Y qué fundamento puso?
No el de la circuncisión (que era el fundamento de la religión judía),
ni el del bautismo de Juan en agua (que después vino a ser
el fundamento de la mayoría de la religión cristiana);
porque les dijo a los corintios que Cristo no lo había enviado a bautizar,
sino a predicar el evangelio, y dio gracias a Dios de no haber bautizado a más de ellos,
sino a Crispo y a Gayo, y a la familia de Estéfanas.
Pero, así como los ojos de Pablo habían sido abiertos para ver el don de Dios en él mismo,
así su obra era abrir los ojos de otros,
para que ellos también pudieran ver el don de Dios en sí mismos.

Los paganos también tenían una luz que "`en las tinieblas resplandece`"^
footnote:[Juan 1:5]
y que "`alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
la cual les mostraba, como nos muestra a nosotros,
lo que es recto y lo que es incorrecto; lo que es justo y lo que es injusto;
aunque en su ignorancia puede que no le hayan prestado mucha
atención como muchos de nosotros lo hacemos ahora.

Puesto que el reino de los cielos consiste en justicia,
la obra de Pablo fue llevar a todas aquellas personas a una vida justa y celestial.
¿Y qué mejor fundamento podía poner un hombre con el fin de conducir a una vida de justicia,
que la luz de Cristo que resplandece en el corazón,
manifestando cada acción de injusticia?
Una Guía, que cuando verdaderamente es seguida, conduce a Dios,
de quien todos los hombres se han apartado por sus vidas injustas.
Pablo experimentó esto, y su experiencia lo hizo un ministro competente,
capaz de predicar sin libros ni estudios,
y de afirmar con confianza que la manera de lograr una vida justa
era "`andar en el Espíritu,`" o permanecer aferrado a esta Guía.

[.blurb]
=== ¿Qué clase de personas eran los destinatarios de sus epístolas?

Los Romanos y los Gálatas, antes de su conversión, eran llamados paganos,
porque no conocían al verdadero Dios, sino que adoraban ídolos mudos.
Estos eran un pueblo que vivía, como muchos lo hacen ahora, en toda clase de impiedad,
andando (como Pablo les dijo a los Efesios),
"`conforme al príncipe de la potestad del aire.`"^
footnote:[Efesios 2:2]
Pero siendo vueltos de sus tinieblas, llegaron a conocer esta luz verdadera,
que nunca consentía ninguna acción injusta.
Sí, a esta luz se volvieron muchos de los paganos,
tomándola como su guía y confiando en ella como un fundamento firme;
y esta es la fe verdadera en Aquel que fue puesto "`por luz de las naciones,`"^
footnote:[Isaías 42:6; 49:6]
y que es una en naturaleza con la fe de Abraham.

Estas personas fueron convencidas (aunque muchos de nosotros no lo estamos) de que,
después de haberse vuelto al Señor, tenían una carrera que correr.
Y puesto que se habían apartado de Dios y de la piedad,
a Dios y a la piedad debían volver.
No se contentaron (como muchos de nosotros lo hacemos) con solo tener el nombre de cristianos,
sino que siguiendo a este Líder, caminaron en novedad de vida,
y llegaron a ser personas sobrias, justas, y piadosas en este mundo presente.^
footnote:[Ver Tito 2:12]
Pablo elogió esto, y les dijo a los Gálatas que ellos corrían bien;
y nosotros también correríamos bien, si corriéramos la misma carrera--volviéndonos,
día a día, más justos, más rectos, más honestos,
más fieles y más vigilantes--lo cual no puede esperarse
hasta que tomemos a su guía como nuestro Líder.

Pero las iglesias de Galacia, siendo en ese tiempo "`hijitos`"^
footnote:[Gálatas 4:19]
(como los llamaba Pablo),
un pueblo de escaso crecimiento en el conocimiento del misterio de la piedad,
fueron persuadidos por algunos (como muchos ahora lo son)
de que una vida nueva y celestial no era suficiente;
sino que también debían practicar varias formas de adoración externa.
Y como la religión de los judíos mostraba la mayor apariencia de piedad,
fueron persuadidos a imitar sus costumbres y prácticas.

Pero Pablo,
habiendo experimentado la insuficiencia de todos los servicios externos
para cambiar la naturaleza del hombre y llevarlo a una vida justa,
dijo a los Gálatas: "`Si os circuncidáis, de nada os aprovechará Cristo.`"^
footnote:[Gálatas 5:2]
Es decir, si se apartaban de su Guía interior,
para descansar en prácticas externas (como lo hacían los celosos fariseos),
entonces Aquel que fue dado como una luz y un líder, dejaría de ser su luz y su líder.
Y, en verdad, ¡no hay nada más evidente!
Porque si Cristo es _el camino,_
y si andar en el Espíritu es _el medio_ por el cual debemos
crucificar el pecado y alcanzar una vida justa,
entonces cualquiera que se aparte de este camino, cualquiera que menosprecie este medio,
no recibe más beneficio de Cristo que el que recibe un viajero de un guía que ha abandonado.
Puesto que Cristo es un "`Espíritu vivificante,`"^
footnote:[1 Corintios 15:45]
es sólo siguiéndole en Sus manifestaciones espirituales que una vida justa es recobrada.
Nada menos puede cambiar nuestra naturaleza y hacernos nuevas criaturas.
Y hasta que seamos nuevas criaturas, nuestra ciudadanía no puede estar en los cielos.

Así, las epístolas de Pablo fueron escritas a un pueblo
que estaba en su viaje de la muerte a la vida.
Habían salido de Egipto, pero no habían llegado a la tierra prometida.
Se habían vuelto de sus tinieblas y tenían sus rostros vueltos hacia Sion,
pero no habían llegado a la Nueva Jerusalén, la ciudad de Dios.
Habían comenzado en el Espíritu,
pero no habían llegado a la verdadera adoración en Espíritu.
Habían recibido a Cristo, pero no estaban arraigados y cimentados en Cristo.
Y para perfeccionar lo que había comenzado, el apóstol no les señaló otra cosa sino:
"`Andad en el Espíritu;`" permanezcan en su Guía interior, la luz de justicia,
porque sólo esto puede levantar a los hijos e hijas de los
hombres de su caída y llevarlos a una vida de justicia.

[.blurb]
=== ¿A qué se refiere el apóstol con los términos "`carne`" y "`espíritu,`" y qué significa andar conforme a ellos?

Es evidente que tanto la carne como el Espíritu son líderes,
de lo contrario no podríamos andar según ellos, y si éstos son líderes,
entonces nuestros cuerpos deben ser seguidores,
manifestando en nuestras palabras y acciones aquello
que ha sido concebido en nuestros corazones o mentes.
Porque toda obra es primero un pensamiento, sea bueno o malo.
Los pensamientos malos surgen de lo que Pablo llama carne.
Los pensamientos verdaderamente buenos proceden de lo que él llama Espíritu.
De modo que la carne es la raíz del mal, y el Espíritu el manantial del bien,
y ambos están dentro de nosotros.

De la carne proceden todas las inclinaciones que conducen al vicio.
Del Espíritu proceden todas las advertencias y convicciones que
encontramos en nosotros mismos para que no cedamos a ellos,
junto con todas las reprensiones que surgen cuando
permitimos que el enemigo prevalezca sobre nosotros.
Estas reprensiones son en amor hacia nosotros,
así como nuestras reprensiones son en amor hacia nuestros hijos,
para que anden con reverencia y no ofendan.

Siempre que cedemos a las inclinaciones del mal, le damos lugar al diablo;
y aquel que cede a una inclinación del mal, tendrá otra del mismo tipo.
Cuanto más cedemos, más terreno gana en nosotros y más poder llega a tener sobre nosotros.
Y el único refugio al que el hombre puede huir cuando una mala inclinación se levanta,
es ese don que está en su corazón que Pablo llama Espíritu;
porque este no consiente ningún acto maligno.
Quienes se mantienen cerca de ese don, se mantienen cerca de Dios;
permanecen con su Guía, y "`andan en el Espíritu.`"

Los paganos convertidos anduvieron por esta regla.
Tomaron al eterno Espíritu de Cristo en sí mismos como su
guía. Confiaron en Él y se hicieron Sus seguidores;
y fue esto lo que los llevó a ser una "`nación santa, pueblo adquirido.`"^
footnote:[1 Pedro 2:9]
Y nosotros seríamos lo mismo,
si tan solo nos volviéramos a este Espíritu eterno en nuestros propios
corazones y ordenáramos todas las cosas según Su gobierno y guía;
porque permaneciendo ahí, no cumpliremos las obras de la carne.

[.blurb]
=== ¿Qué debemos entender por las palabras "`morir`" y "`vivir`"?

Ciertamente, con la palabra morir no se refería a la cesación de sus vidas mortales,
pues tal muerte, en el tiempo señalado por el Señor, es común para todos los hombres.
Tanto los que viven conforme al Espíritu, como los que andan conforme a la carne,
deben descender a la tumba.
Pero la muerte a la que se refería el apóstol era el deterioro de nuestra vida interior,
la muerte a la justicia (de la que pocos están conscientes en nuestra presente época):
el mismo tipo de muerte que el primer hombre, Adán,
experimentó cuando cayó del gobierno del eterno Espíritu,
que fue el primer estado del hombre; y que la casa de Israel sufrió,
cuando se aferraron a las observancias externas, ignoraron la justicia,
la misericordia y el humilde andar con su Dios.

Ahora,
los que andan conforme a la carne y viven en la práctica de cualquier pecado conocido,
se alejan cada vez más de Dios, y llegan a tener menos vida, menos luz, menos gracia,
menos temor de ofender a Dios y de hacer daño a su prójimo,
como se puede ver por la conducta de los hombres.
Y esta continua decadencia es morir a la justicia.

Y así como los que viven conforme a la carne tienen menos vida, menos luz,
menos gracia y menos temor; así también los que andan conforme al Espíritu,
haciendo cosas que son rectas,
honestas y honorables a partir de la Semilla justa sembrada en sus propios corazones,
hallan un incremento.
Estos llegan a tener más vida, más luz,
más gracia y más temor de ofender a Dios o a su prójimo.
Y experimentar este incremento es vivir para la justicia.
Así como los unos se alejan, los otros se acercan al reino de los cielos.

Si no tuviéramos en nosotros mismos Espíritu así como carne, luz así como tinieblas,
un Conductor en el camino de la vida y la salvación,
así como un líder en los caminos de destrucción,
podríamos echar toda la culpa de la pérdida de la vida y
las calamidades del pecado sobre la cuenta de Adán,
o cargarlas exclusivamente a la cuenta del maligno,
de quién proceden todas las inclinaciones malignas.
Pero Pablo era un maestro experto en teología espiritual.
Él sabía qué corrompía a los hijos e hijas de los hombres,
y de dónde surgía toda la perversidad que hay en este mundo.
Y para limpiar, purgar, purificar,
hacer que los paganos se vuelvan cristianos verdaderos y los pecadores santos,
no señala ningún otro medio sino este: "`Andad en el Espíritu.`"
Porque al mantenernos en este Espíritu,
aprenderemos (como lo hicieron los paganos convertidos) no solo a negar la impiedad,
sino también a vivir piadosamente en este presente siglo.

Pero si no hacemos uso de los medios antes mencionados,
sino que descansamos en prácticas externas (como hicieron los celosos fariseos),
considerándonos justos por una supuesta forma correcta de piedad, entonces,
aunque tengamos un celo por nuestras formas y prácticas tan grande
como el que tuvo Pablo por la religión de los judíos,
no nos aprovechará más de lo que la circuncisión hubiera aprovechado a los Gálatas.

Hemos tenido mucha predicación y enseñanza.
Se han prometidos los gozos del cielo a los que hacen el bien;
se han amenazado con los tormentos del infierno a los que hacen el mal.
Pero ¿todas estas promesas y amenazas nos han hecho una nación santa y un pueblo escogido,
superando a todos los demás en los frutos del Espíritu?
¿Todas las exhortaciones que hemos recibido han logrado
capacitarnos para hacer morir el cuerpo de pecado,
que es la causa de la impiedad?
¿Hemos sido por ello, como lo fueron los paganos,
trasladados de las tinieblas al reino del amado Hijo de Dios,
para tener nuestra ciudadanía en el cielo incluso
mientras nuestros cuerpos están en la tierra?
¿Podemos decir verdaderamente que "`las cosas viejas pasaron:`"^
footnote:[2 Corintios 5:17]
todos los pensamientos altivos, todos los apetitos codiciosos, toda ira y amargura;
y que en su lugar han llegado cosas nuevas: humildad, mansedumbre, templanza, abnegación,
con un amor sincero hacia Dios y a nuestro prójimo?

¿Podemos decir:
"`Hubo un tiempo en el que el pecado tenía tal dominio sobre nosotros
que no podíamos abstenernos de cumplir los deseos de la carne,
pero ahora estamos tan gobernados por el Espíritu eterno que debemos ser moderados,
debemos ser sobrios y vigilantes, debemos ser justos, rectos y fieles en palabra y obra?
Si este es realmente nuestro estado, entonces,
al igual que los primeros cristianos en su estado más pleno,
estamos muertos al pecado y vivos para la justicia,
habiendo sido edificados sobre la misma roca que ellos.
Pero si no hemos llegado a esto,
sería sabio volvernos al Señor (como lo hicieron ellos)
y construir sobre el mismo fundamento sobre el cual construyeron,
a saber: "`La luz verdadera, que alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera Gómez]
para que lleguemos a conocer al Espíritu eterno, como ellos lo conocieron,
y tengamos un Guía y Líder en los caminos de la santidad, como ellos lo tuvieron.
Porque es por medio y a través del poder del Espíritu eterno de Jesús en nuestros corazones,
que nuestras corrupciones deben ser purgadas, y nuestro interior limpiado.
Porque, en verdad, así como nuestro andar conforme a la carne ocasionó todas las heridas,
así nuestro andar conforme al Espíritu debe sanar todas las heridas.
Así como nuestro vivir conforme a la carne hizo que aumentara nuestra injusticia,
así andando conforme el Espíritu hacemos morir el pecado y recuperamos una vida de justicia.

Pablo habló a partir de un buen entendimiento cuando les dijo a los Romanos:
"`Porque lo que se conoce acerca de Dios es evidente dentro de ellos.`"^
footnote:[Romanos 1:19 LBLA]
De allí obtenía su conocimiento en los misterios de la piedad;
cualquier cosa que predicara, cualquier cosa que escribiera,
la fuente estaba en él mismo.
Él no sabía más de la obra interior y espiritual de la gracia que cualquier otro hombre,
hasta que llegó a tener sus ojos vueltos al interior y a andar en el Espíritu;
y así recomendó a las iglesias lo que él mismo había experimentado.

Muchos pueden hablar de redención, justificación,
santificación y salvación por medio de Cristo,
pero el cristiano es aquel que experimenta estas cosas formadas en sí mismo.
Los tales pueden ser llamados apropiadamente hombres entendidos;
porque conocen qué significa levantarse con Él,
qué significa morir y qué significa vivir, saben de qué han sido redimidos y salvados,
y por qué medios.

[.blurb]
=== Cómo podemos, por medio del Espíritu, hacer morir las obras de la carne.

Pero primero, consideremos cuáles obras de la carne deben morir.
Puesto que un espíritu maligno en el hombre es la raíz de todas las obras malignas,
_toda obra que procede de esa raíz_ tiene que morir.
Y nada puede manifestar tales obras,
dándonos una verdadera visión de su naturaleza y surgimiento, sino el Espíritu del Señor,
o la Luz de justicia en nuestros propios corazones,
a medida que resplandece con claridad.

Para saber cuáles de nuestras obras o actividades tenemos que hacer morir,
debemos considerar nuestro objetivo en ellas.
Si no tenemos otro fin más que la justicia, equidad, honestidad y amor,
podemos proceder con seguridad; pero si el yo es lo que nos mueve,
si no estamos buscando el bien de nuestro prójimo junto con el nuestro,
pretendamos lo que pretendamos,
tales obras proceden de una raíz maligna y tienen que ser negadas; y al negarlas,
llegan a morir.
¿Y qué puede manifestar nuestro objetivo en cada acción? Ni los libros,
ni los predicadores, sino solamente el Espíritu del Señor, que es una luz interna.

Ahora bien,
no encontramos que Pablo haya acusado directamente
a los Gálatas de ningún tipo de pecado manifiesto,
sino solamente de "`guardar los días, y los tiempos;`" y ¿qué mal podría haber en eso?

Puede que los Gálatas no hayan visto nada, aun así Pablo vio mucho,
de lo contrario no les hubiera preguntado:
"`¿Quién os fascinó?`" Porque ellos habían comenzado en el Espíritu;
habían caminado por un tiempo tras un Guía interior,
que es el único líder hacia una vida de justicia tal como el Señor (en
todas las edades) ha requerido de los hijos e hijas de los hombres.
Esta no era una apariencia de piedad sin vida, sino la verdad en lo íntimo;
porque si tenemos la verdad en nuestros corazones,
la justicia será realizada por nuestras manos.
Y Pablo sabía que ellos nunca podrían llegar a esto imitando una adoración externa,
mucho menos guardando los días y los tiempos,
por eso consideró tales cosas como obras de la carne,
argumentando con ellos de esta manera: "`¿Tan necios sois?
¿Habiendo comenzado en el Espíritu, ahora os perfeccionáis por la carne?`"^
footnote:[Gálatas 3:3 Reina Valera de Gómez]
Es como si hubiera dicho: "`¿Están tan vacíos de entendimiento?
Habiendo empezado a caminar en novedad de vida,
¿esperan alcanzar tal perfección como para tener su ciudadanía
en los cielos mientras viven en la tierra,
volviendo a las prácticas de ritos externos?`"
"`Esta persuasión,`" dijo, "`no procede de Aquel que os llama;`"^
footnote:[Gálatas 5:8]
y si no era de Dios, debía provenir del antiguo engañador.
Y en verdad, muchos han sido engañados de esta manera,
persuadiéndose a sí mismos que la piedad consiste en eso
que es llamado (pero no lo es) verdadera devoción,
y sin embargo, viven en orgullo, codicia,
envidia y muchas otras cosas que claramente son obras de la carne,
nunca llegando a ser trasladados del reino de las tinieblas,
ni a vivir bajo el gobierno del Espíritu eterno.

La caída del hombre no fue de ninguna religión externa o apariencia de piedad,
sino de la vida de justicia.
El hombre cayó de un estado en el que el esposo, la esposa, los padres, los hijos,
los amos, los siervos y todas las otras relaciones, habrían conocido su lugar y deber,
y habrían permanecido allí. Cayó de un estado en donde todas
las cosas creadas que Dios había dado para el uso del hombre,
se habrían utilizado correctamente,
y ninguna de ellas habría sido malgastada o maltratada por el exceso.
Cayó de un estado en el que la verdad se habría hallado en todas nuestras palabras,
y la equidad en todas nuestras obras;
de un estado en donde la voluntad de Dios se habría hecho en la tierra como en los cielos,
y el gran Dios habría sido glorificado por nosotros, y no deshonrado.
De este estado, por la entrada y crecimiento del pecado,
los hijos e hijas de los hombres se apartaron;
y a este mismo estado regresaron los primeros cristianos haciendo morir el pecado.

Esta fue la vida que perdió el primer Adán. Esta es la vida que
vino a recuperar el segundo Adán. Y todos los que tengan el Espíritu
de Cristo y se conviertan en verdaderos seguidores de Él,
se levantan de esta caída, regresan a Dios,
viven bajo Su gobierno y se convierten en testigos de esta vida celestial restaurada.

Cuando he mirado el Libro de Oración Común,
he hallado que las palabras en él son tan buenas como pueden recopilarse de las Escrituras,
con el requisito de que no se admita ni a un solo hombre
en la iglesia sin prometer hacer todo lo que he mencionado.
Si estas promesas se cumplieran realmente, seríamos en verdad una nación santa,
que de ninguna manera quedaría corta de los santos más eminentes;
porque los que más alto han llegado,
no han llegado a un estado superior al de "`caminar en los
mandamientos de Dios todos los días de sus vidas.`"^
footnote:[Un Catecismo; 1662 [.book-title]#Libro de Oración Común.#]

Pero es raro encontrar a un hombre que cumpla este pacto, y la razón es esta:
decimos que las Escrituras son nuestra regla, pero no atendemos a su consejo.
No se sigue el consejo de Pablo, no andamos en el Espíritu; porque si lo hiciéramos,
la luz de justicia en nuestros corazones nos mostraría
el surgimiento de cada inclinación maligna,
y a qué conduce.
Este es el tiempo de "`renunciar al diablo y todas sus obras,
con todas las vanidades del mundo y deseos pecaminosos:`"^
footnote:[Un Catecismo; 1662 [.book-title]#Libro de Oración Común.#]
porque si rechazamos todas las inclinaciones malignas,
nunca seremos hallados en actos malignos; y hasta que dejemos de hacer lo malo,
no aprenderemos a hacer el bien.^
footnote:[Isaías 1:16-17]
El pecado debe ser crucificado antes de que podamos vivir una vida de justicia.
Las obras del diablo deben ser rechazadas,
antes de que se pueda caminar en los mandamientos de nuestro Dios siquiera un día,
mucho menos "`todos los días de nuestras vidas.`"

Y Pablo experimentó esto, lo que le hizo decir con gran confianza:
"`Andad en el Espíritu; y no cumpliréis las concupiscencias de la carne.`"
Porque si rechazamos y nos volvemos de cada inclinación que la luz de
Cristo en nuestros propios corazones nos muestra como maligna,
no las cumpliremos; sino que, al contrario, haremos morir la raíz de la cual surgen;
porque aquello que no se alimenta, con el tiempo llega a morir.

Así, los paganos convertidos llegaron a ser una nación santa.
Esta es la manera de llegar a ser ciudadanos de la Nueva Jerusalén. Por este medio,
los Colosenses fueron (y nosotros también podemos
serlo) trasladados al reino del amado Hijo de Dios,
para vivir bajo Su gobierno.
Este es el reino que Juan el Bautista proclamó que se había acercado.
Este es el reino por el cual los discípulos de Cristo fueron instruidos a orar.
Este es el reino que consiste en justicia y se establece en poder.
Este es el reino que todos los creyentes deben buscar primero;
porque bajo el gobierno del Espíritu eterno de Jesús en sus corazones,
los hijos e hijas de los hombres quedan limitados de hacer cualquier cosa injusta.

Muchos de los actuales profesantes del cristianismo están persuadidos de que,
aunque sus vidas siguen siendo injustas,
al estar en la práctica de algo llamado religión, les irá bien al final.
Pero el Señor vivo no toma en cuenta qué religión profesamos, sino a qué líder seguimos;
porque sea cual sea nuestra religión, si vivimos conforme a la carne, moriremos.
Y aunque aparezca poco de lo que se considera religión, si andamos conforme al Espíritu,
si nuestra ciudadanía está en los cielos,
si la verdad está en nuestras bocas y la justicia se cumple con nuestras manos,
viviremos.

Pero ¿quién es capaz de andar conforme al Espíritu,
y por el Espíritu de hacer morir las obras de la carne?

Hay muchos, incluso entre los que llevan el nombre de cristianos, quienes,
por su perseverancia en hacer lo malo, han llegado a sentirse muertos en pecado,
habiendo perdido toda sensibilidad y conciencia de ese don en sí mismos que es de Dios;
y estos, que no están familiarizados con el Espíritu,
ciertamente no pueden "`andar conforme al Espíritu.`"

Hay otros que no están muertos, sino muriendo.
Todavía tienen sensibilidad y cierta conciencia;
tienen en sí mismos aquello que los guiaría a cosas mejores que las que practican,
pero le prestan poca o ninguna atención. No lo toman como su guía. Y mientras
rechazan esa luz dentro de ellos que manifiesta las obras de la carne,
no pueden de ninguna manera hacerlas morir.

Pero se hallan algunos que están cansados de sus pecados y cargados con sus iniquidades,
teniendo en sí mismos hambre y sed de justicia.
Tales como estos son un pueblo vivo, y capaces, mediante el Espíritu,
de hacer morir las obras de la carne.

Estoy convencido de que en nuestra época muchos han sido despertados del sueño del pecado,
y han encontrado en sí mismos una verdadera hambre y sed de justicia;
pero habiendo sido despertados por un ministerio externo,
han esperado que su hambre y su sed sean saciados por este.

Muchos pueden ser despertados, pero no vivificados, por un ministerio externo.
Porque como dijo Jesús:
"`El Espíritu es el que da vida;`" y ¿qué puede vivificar sino aquello que da vida?
¿Qué puede saciar un alma que está sedienta de justicia,
sino aquello que en verdad es la Fuente misma de la justicia?
Es en nosotros mismos que el pozo debe ser hallado,
donde aquellos que beben no tendrán sed jamás. Solamente
allí está la fuente que salta para vida eterna.

Así como el reino de los cielos no consiste en palabras, sino en poder,
así tampoco son las palabras, sino el poder de Dios,
lo que puede hacer morir las obras de la carne,
cambiar nuestra naturaleza y hacernos nuevas criaturas.
Si las palabras nos pudieran llenar de justicia, rectitud, verdad, equidad y fidelidad,
hace mucho tiempo que seríamos una nación santa, porque no ha habido falta de palabras,
pero todavía hay una gran falta de justicia y fidelidad.

Si las buenas palabras pudieran llevar a los oyentes a una vida de justicia,
entonces en lugar de decir:
"`Andad en el Espíritu,`" Pablo les habría dicho a los Gálatas:
"`¡Escuchad a vuestro ministro!`"
No habría tenido la necesidad de encomendarlos al Guía interior.^
footnote:[Hechos 20:32]
Pero la experiencia le había demostrado a Pablo que no por el oír de las palabras,
sino por la obediencia a la ley del Espíritu,
él hacía morir las obras de la carne y vivía una vida justa.
Y lo que halló ser eficaz en sí mismo, lo recomendó a las iglesias.

Las palabras, por numerosas que sean, pueden ser fácilmente olvidadas;
estas no permanecen.
Pero el Espíritu eterno permanece, y es ese '`maestro el que nunca más te será quitado.`'^
footnote:[Ver Isaías 30:20]
El uso de las palabras en la obra de salvación es despertar a aquellos
que duermen en pecado y volverlos (como Pablo volvió a los paganos)^
footnote:[Hechos 26:18]
al Guía interno, y también para amonestarlos a mantenerse aferrados a su Guía,
mientras están en su viaje.

Si los que tenían hambre y sed de justicia hubieran buscado fervientemente lo que deseaban;
si se hubieran familiarizado con el Espíritu eterno que engendraba esos deseos,
y seguido Su dirección, Él habría desarraigado todo orgullo y egoísmo.
Los habría llevado a un estado humilde, bajo, manso, paciente y pacífico,
y a hacer lo correcto en todo momento.
Esto, en verdad, les habría quitado su carga y les habría dado descanso y paz.

Y si queremos ser como fueron los primeros cristianos,
debemos comenzar donde ellos lo hicieron.
Debemos volvernos a la luz de justicia en nuestros propios corazones,
y andar en esa luz hasta convertirnos en hijos de la luz.
Debemos caminar en la senda de los justos, que va en aumento como la luz de la aurora,^
footnote:[Proverbios 4:18]
hasta que la justicia sea nuestro centro.
Esto convirtió a los primeros cristianos en un pueblo verdaderamente piadoso;
gracias a esto prosperaron,
de lo contrario los paganos ciegos e ignorantes nunca habrían llegado
a ser conciudadanos de los santos y miembros de la familia de Dios.

Pablo no fue un ministro establecido en un solo lugar, lo escuchaban rara vez;
pero oían la voz del Espíritu eterno cada vez que
transgredían el pacto de la luz y la vida.
Es a esta voz a la que los cristianos deben inclinar su oído;
porque bajo el nuevo pacto Dios habla a Su pueblo por Su Hijo,
a través del Espíritu eterno en sus corazones.

El primer paso para lograr una vida de justicia es familiarizarnos con el don de la
gracia en nuestros propios corazones que nos reprende a causa de la impiedad;^
footnote:[Tito 2:11]
porque hasta que lleguemos a esto, somos extraños al fundamento de una vida piadosa.
Porque cada aspecto de nuestra edificación, de nuestro viaje espiritual,
de nuestro levantamiento de la caída y acercamiento
al reino de Dios depende completamente de que neguemos,
rechacemos y abandonemos absolutamente lo que la luz de
justicia condena y reprueba en nuestros corazones;
porque al negar todo lo que es contrario a la luz, hacemos morir las obras de la carne.
A medida que nos ocupamos de esto y somos fieles en ello, Su luz brilla más y más;
y cuanta más luz tenemos, mayor es el descubrimiento que hace de lo que es malo,
de lo que se debe negar, rechazar y abandonar.
Así que, guiando nuestros pasos por esta luz, edificamos sobre el verdadero fundamento,
caminamos en el camino vivo, crecemos en la gracia y en el conocimiento de Cristo,
y nos acercamos más y más a Su reino y gobierno de justicia;
y Su poder es experimentado en una vida justa.

Este fue el consejo de Cristo:
"`Esforzaos por entrar por la puerta estrecha;`" testificando,
que el camino a la vida eterna era estrecho y difícil.
¿A qué hace referencia esta puerta estrecha y camino angosto?
No al egoísmo, ni tampoco a la justicia propia;
porque el egoísmo es la raíz de todas las prácticas codiciosas,
los tratos deshonestos y acciones injustas.
La justicia propia es la raíz de toda formalidad y contienda sobre religión,
de la cual ha habido (y todavía hay) demasiada en el mundo cristiano,
persiguiéndose unos a otros,
tal como los paganos inconversos persiguieron a los primeros convertidos.

Ninguno de estos caminos lleva a ese reino que consiste
en justicia y paz en el Espíritu Santo.
Si los paganos recién convertidos hubieran andando en esos caminos,
nunca habrían llegado a ser una nación santa,
porque su ciudadanía habría estado en la tierra y no en los cielos.
Pero la puerta estrecha y el camino angosto que llevan a una vida justa,
son la negación al yo--la negación a todo lo que procede de la raíz del mal,
desde el asunto más pequeño hasta el deseo más grande;
lo cual sólo puede ser manifestado por una luz interna que resplandece con claridad.
Pero con tristeza podemos decir,
que es raro encontrar aún a uno entre muchos que viva en
la práctica de lo que él mismo reconoce como correcto.
¿Quién no confesará que decir la verdad en todo momento es algo correcto?
¿Quién no reconocerá que cumplir nuestra palabra, aunque sea para nuestro perjuicio,
es algo honesto?
¿Quién no concederá,
que hacerles a todos los hombres lo que quisiéramos que ellos hicieran con nosotros,
es algo justo?
Sin embargo, ¡cuán pocos viven en la práctica de estas cosas!
Y si no vivimos en la práctica de lo que sabemos que es correcto,
¿de qué nos sirve saberlo?
Podemos seguir moviéndonos, como lo hizo Israel en el desierto,
pero si no andamos en el camino estrecho, nunca podremos llegar a una vida justa.

Entonces, si no cerramos deliberadamente nuestros ojos,
podemos ver con claridad que el camino hacia una vida justa es "`andar
en el Espíritu,`" someternos al gobierno de nuestro Guía interior,
negar y apartarnos de todo lo que la luz de justicia
manifiesta en nuestros corazones como impío,
injusto o deshonesto.
Y al apartarnos del mal, nos volvemos al Único que es bueno; al abandonar lo malo,
procuramos ser llenos de virtud; al morir al pecado, somos vivificados para la justicia,
y así la verdad, la pureza y el amor llegan a tener dominio en nuestros corazones.
A estos, Pablo les dijo:
"`No hay condenación;`" porque tienen "`el testimonio de una buena conciencia,`"^
footnote:[1 Pedro 3:21 Reina Valera de Gómez, Reina Valera 1602 Purificada.]
paz con Dios y paz en sí mismos--paz mientras están aquí, y paz cuando partan de aquí.
