== Capítulo I. Andar en el Espíritu

Pablo, en su epístola a los Gálatas, capítulo 5:16, dijo, "`Andad en el Espíritu,
y no satisfagáis los deseos de la carne.`"
Asimismo, en su epístola a los Romanos, capítulo 8:13, dijo,
"`porque si vivís conforme a la carne, moriréis;
mas si por el Espíritu hacéis morir las obras de la carne,
viviréis.`" Si es cierto que las escrituras fueron escritas para nuestro aprendizaje,
sin duda estos versículos lo fueron, porque mucho se puede aprender de ellos.
El fin de la predicación, tanto en nuestra era presente como en todas las eras pasadas,
ha sido que los hijos e hijas de los hombres así aprendan a negar,
rechazar y abandonar toda obra mala, y lleguen a vivir una vida sobria,
justa y santa en este mundo presente,
para que tengan paz con Dios en sus propias conciencias
en este mundo y vida eterna en el venidero.

Ahora, para llevar a cabo esta gran obra,
en la que miles de trabajadores han estado por muchos años empleados,
el apóstol da esta exhortación: "`Andad en el Espíritu,`" afirmándoles a los Gálatas que,
si ellos anduvieran en el Espíritu, no cumplirían los deseos de la carne;
no cederían ante las malas intenciones, ni satisfarían sus deseos carnales,
lo cual es la única manera de hacer morir las obras de la
carne y curar todas nuestras enfermedades espirituales.
Pero este camino de la salvación de Dios ha sido rechazado por tanto tiempo,
que pocos en nuestra era actual saben _qué_ es este Espíritu, _dónde_ conocerlo,
o _cómo_ caminar en él. Por lo tanto,
para que nuestro entendimiento sea abierto en este gran asunto, consideremos:

[.numbered-group]
====

[.numbered]
1+++.+++ Qué era Pablo y cómo llegó a ser ministro del evangelio.

[.numbered]
2+++.+++ Qué clase de personas eran los destinatarios de sus epístolas.

[.numbered]
3+++.+++ A qué se refiere el apóstol con los términos carne y espíritu,
y qué significa andar conforme a ellos.

[.numbered]
4+++.+++ Qué quiere decir con las palabras "`morir`" y "`vivir.`"

[.numbered]
5+++.+++ Cómo podemos, por medio del Espíritu, hacer morir las obras de la carne.

====

Al leer las Escrituras podemos encontrar, que Pablo era un Israelita,
de la simiente de Abraham, educado para ser un erudito, bien instruido en la ley.
En cuanto a su religión, era Fariseo.
Y, ¿quiénes eran los Fariseos?
No eran personas ligeras ni profanas;
sino (en apariencia externa) un pueblo muy religioso,
celoso por su templo y sus servicios, y por muchas otras observaciones externas;
hasta el punto de que Jesús dijo de ellos,
que limpiaban "`lo de fuera del vaso y del plato,`"^
footnote:[Mateo 23:25; Lucas 11:39]
algo que pocos hacen ahora.

Pero cuando se acercaba el tiempo en el que Dios
no sería adorado más en templos hecho de manos,
sino que moraría en corazones santificados y sería adorado ahí;
y cuando las leyes que fueron escritas por el gran profeta Moisés
para que la casa de Israel las observara y caminara en ellas,
ya no deberían ser más una regla de justicia,
sino que los Judíos y los Gentiles andarían por una
ley que procedía del Espíritu de Dios en lo íntimo;
y cuando Uno más grande que Moisés vino,
proclamando un reino cercano que consistía en una
justicia mayor y más excelente que la de ellos,
testificando a los rostros de esos adoradores externos que,
a pesar de su gran celo por el templo y sus servicios,
no eran más que hipócritas y guías ciegos;--entonces,
los gobernantes de este pueblo se ofendieron grandemente.
Y, teniendo un espíritu perverso dentro de ellos,
a pesar de su apariencia de justicia externa,
se esforzaron por detener la venida de ese reino
al asesinar al Príncipe y aprisionar a Sus súbditos.
Y en esta persecución nadie fue más activo que Pablo,
asolando a la iglesia de Dios desmedidamente, y tratando de destruirla.

Pero en la cúspide de su persecución, no fue el hombre quien puso fin a su proceder,
sino Dios; mostrándole que no perseguía a los hombres, _sino a Cristo en los hombres._
Y de hecho esto era verdad, porque si Cristo, por Su Espíritu eterno,
no hubiera estado en los hombres a quienes Pablo perseguía,
abriendo los ojos de sus entendimientos para ver el vacío de todas las sombras,
y apartándolos de ellas, Pablo no tendría nada que decirles.
Más viendo que ellos se inclinaban a adorar a Dios en Espíritu,
y por lo tanto descuidaban la adoración del templo,
Pablo los veía como un pueblo que no era digno de vivir.

Pero agradó a Dios revelar en Pablo el mismo Cristo que él había perseguido en otros;
y esta revelación, o conocimiento interno de Cristo,
fue el fundamento de todo el conocimiento de Pablo en el misterio de la piedad.
Sus enseñanzas posteriores no provenían de hombres, ni de libros,
sino de la operación del Espíritu eterno de Jesús
en él. Y manteniéndose bajo la guía de ese Espíritu,
crecía en gracia; y a medida que crecía en gracia, crecía en el conocimiento de Cristo.
Así que él no subió a Jerusalén para recibir instrucciones
u órdenes de los que eran apóstoles antes que él,
sino que, en la fortaleza del Señor, con un libro de experiencia en su corazón,
en lugar de una Biblia en su mano, fue a Arabia para predicar el evangelio a los Paganos.
Y ¿cuál fue el fundamento que él puso?
No el de circuncisión (que era el fundamento de la religión judía),
ni del bautismo de Juan en agua (que desde entonces se ha convertido
en el fundamento de la mayoría de la religión Cristiana);
porque les dijo a los Corintios que Cristo no lo envió a bautizar,
sino a predicar el evangelio,
y dio gracias a Dios de que a ninguno de ellos había bautizado, sino a Crispo y a Gayo,
y a la familia de Estéfanas.
Pero, así como los ojos de Pablo fueron abiertos para ver el don de Dios en él mismo,
así también su labor era abrir los ojos de otros,
para que ellos también vieran el don de Dios en ellos mismos.

Los Paganos también tenían una luz que "`en las tinieblas resplandece`"^
footnote:[Juan 1:5]
y que "`alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
que les mostraba (como nos muestra a nosotros) lo que está bien y lo que está mal;
lo que es justo y lo que es injusto;
aunque en su ignorancia puede que no le hayan prestado mucha
atención como muchos de nosotros lo hacemos ahora.

Puesto que el reino de los cielos consiste en justicia,
la obra de Pablo era llevar a todas esas personas a una vida justa y celestial.
Y,
¿qué mejor fundamento podría poner cualquier hombre con el fin de lograr una vida justa,
que la luz de Cristo que resplandece en el corazón,
manifestando cada acción de injusticia?
Un Guía, que cuando verdaderamente es seguido, conduce a Dios,
de quien todos los hombres se han apartado a causa de sus vidas injustas.
Esto lo experimentó Pablo, y su experiencia lo hizo un ministro competente,
capaz de predicar sin libros ni estudios,
y de afirmar con confianza que la manera de lograr una vida justa
era "`andar en el Espíritu,`" o mantenerse aferrado a este Guía.

De esta manera, he mostrado cómo Pablo llegó a ser un ministro del evangelio;
y ahora mostraré quiénes eran los destinatarios de sus epístolas.

Los Romanos y los Gálatas, antes de su conversión, eran llamados Paganos,
porque ellos no conocían al verdadero Dios, sino que adoraban ídolos mudos.
Este era un pueblo que vivió, como muchos lo hacen ahora, en toda clase de impiedad,
andando (como Pablo le dijo a los Efesios),
"`conforme al príncipe de la potestad del aire.`"^
footnote:[Efesios 2:2]
Pero siendo vueltos de su oscuridad, se familiarizaron con esta luz verdadera,
que nunca consiente ninguna acción de injusticia.
Sí, a esta luz se volvieron muchos de los Paganos, tomándola como su guía,
confiando en ella como un fundamento firme;
y esta es la fe verdadera en Aquel que fue puesto "`por luz de las naciones`"^
footnote:[Isaías 42:6; 49:6], la cual es una en naturaleza con la fe de Abraham.

Estas personas fueron convencidas (aunque muchos de nosotros
no lo estamos) de que después de haberse vuelto al Señor,
luego tenían una carrera que correr.
Y puesto que se habían apartado de Dios y de la piedad,
a Dios y a la piedad tenían que regresar.
Ellos no se contentaron (como muchos de nosotros
lo hacemos) con solo tener el nombre de cristianos,
sino que siguiendo a este Líder, caminaron en novedad de vida,
y llegaron a ser personas "`sobrias, justas, y piadosas en este mundo presente.`"^
footnote:[Tito 2:12]
Pablo elogiaba esto, y por eso les dijo a los Gálatas que ellos corrían bien;
y nosotros también correríamos bien,
si corriéramos la misma carrera--volviéndonos cada día más justos, más rectos,
más honestos, más fieles,
y más diligentes--lo cual no puede esperarse hasta
que tomemos su guía como nuestro Líder.

Sin embargo, las iglesias de Galacia, siendo en ese tiempo "`hijitos`"^
footnote:[Gálatas 4:19]
(como los llamaba Pablo),
un pueblo de pequeño crecimiento en el conocimiento del misterio de la piedad,
fueron persuadidos por algunos (como muchos ahora son) de
que una vida nueva y celestial no era suficiente;
sino que también debían practicar varias formas de adoración externa.
Y como la religión de los Judíos tenía la mayor apariencia de piedad,
fueron persuadidos a imitar sus costumbres y prácticas.

Pero Pablo,
habiendo experimentado la insuficiencia de todos los servicios externos
para cambiar la naturaleza del hombre y llevarlo a una vida justa,
les dijo a los Gálatas que, "`si os circuncidáis, de nada os aprovechará Cristo.`"^
footnote:[Gálatas 5:2]
Es decir, si ellos se apartaban de su Guía interno,
para descansar en prácticas externas (como hicieron los celosos Fariseos),
entonces Aquel que fue dado como una luz y un líder,
ya no iba a ser más su luz ni su líder.
De hecho, ¡no hay nada más evidente!
Porque si Cristo es _el camino,_
y si andar en el Espíritu es _el medio_ por el cual
crucificamos el pecado y llegamos a una vida justa,
entonces quienquiera que se aparte de este camino,
quienquiera que menosprecie este medio,
no recibe más beneficio de Cristo que el que recibe un viajero de un guía que ha abandonado.
Puesto que Cristo es un "`Espíritu vivificante,`"^
footnote:[1 Corintios 15:45]
seguirlo en Sus manifestaciones espirituales es la
única manera de recuperar una vida de justicia.
Nada menos que eso puede cambiar nuestra naturaleza y hacernos nuevas criaturas.
Y hasta que seamos nuevas criaturas, nuestra ciudadanía no puede estar en los cielos.

Así que las epístolas de Pablo fueron escritas a un pueblo
que estaba en un viaje de la muerte a la vida.
Había salido de Egipto, pero no había llegado a la tierra prometida.
Se había vuelto de sus tinieblas, y tenía su rostro vuelto hacia Sion,
pero no había llegado a la Nueva Jerusalén, la ciudad de Dios.
Había comenzado en el Espíritu,
pero no había llegado a la verdadera adoración en el Espíritu.
Había recibido a Cristo, pero no estaba arraigado y cimentado en Cristo.
Y para perfeccionar lo que había comenzado,
el apóstol no le indicó otra cosa más que esto:
"`Andad en el Espíritu;`" manténgase siguiendo a su Guía interno, la luz de justicia,
porque solo esto puede levantar a los hijos e hijas de los
hombres de su caída y llevarlos a una vida de justicia.

La tercera cosa que debe ser considerada es esta:
A qué se refiere el apóstol con los términos carne y espíritu,
y qué significa andar conforme a ellos.

Es evidente, que tanto la carne como el Espíritu son líderes,
de lo contrario no podríamos andar tras ellos, y si estos son líderes,
entonces nuestros cuerpos deben ser seguidores,
manifestando en nuestras palabras y acciones eso
que ha sido concebido en nuestros corazones o mentes.
Porque cada obra es primero un pensamiento, ya sea bueno o malo.
Los pensamientos malignos surgen de eso que Pablo llamó carne.
Los buenos pensamientos proceden de eso que él llamó Espíritu.
De modo que la carne es una raíz del mal y el Espíritu un manantial de bien,
y ambos están dentro de nosotros mismos.

De la carne proceden todas las inclinaciones que conducen al vicio.
Del Espíritu proceden todos los temores y advertencias que
encontramos en nosotros mismos de que no cedamos a ellos,
junto con todas las reprensiones que surgen cuando
permitimos que el enemigo prevalezca sobre nosotros.
Estas reprensiones son en amor hacia nosotros,
así como nuestras reprensiones son en amor a nuestros hijos,
para que anden con reverencia y no ofendan.

Cada vez que cedemos a las malas inclinaciones, le damos lugar al diablo;
y quienquiera que ceda a una mala inclinación, tendrá otra del mismo tipo.
Entre más cedamos,
más terreno tiene él en nosotros y llega a tener más poder sobre nosotros.
Y el único refugio al que el hombre puede huir cuando las malas inclinaciones se levantan,
es a ese don que está en nuestro corazón el cual Pablo llama Espíritu;
porque este no consentirá ningún acto maligno.
Cualquiera que se mantenga cerca de esto, se mantiene cerca de Dios;
estos permanecen con su Guía, y "`andan en el Espíritu.`"

Los Paganos convertidos caminaban por esta regla.
Ellos tomaron al eterno Espíritu de Cristo en sí mismos como su guía. Confiaban en eso,
y se volvieron seguidores de ello; y fue esto lo que los llevó a ser "`nación santa,
pueblo adquirido.`"^
footnote:[1 Pedro 2:9]
Y nosotros seríamos iguales si tan solo nos volviéramos
a este Espíritu eterno en nuestros propios corazones,
y ordenáramos todas las cosas según Su gobierno y guía; porque al mantenernos bajo esto,
no satisfaremos las obras de la carne.

La cuarta cosa, a considerar es, qué quería decir el apóstol con estas palabras,
morir y vivir.

Ciertamente, con la palabra morir, él no se refería al cese de sus vidas mortales,
porque este tipo de muerte es común para todos los
hombres en el momento que el Señor lo determina.
Tanto los que viven según el Espíritu, como los que andan conforme a la carne,
deben bajar a la tumba.
Pero la muerte a la que se refería el apóstol era, al deterioro de nuestra vida interna,
la muerte a la justicia (algo de lo que pocos están conscientes
en esta época)--el mismo tipo de muerte que el primer hombre
(Adán) experimentó cuando cayó del gobierno del eterno Espíritu,
que fue el primer estado del hombre; y que la casa de Israel sufrió,
cuando se aferraron a las prácticas externas, ignoraron la justicia y misericordia,
y dejaron de caminar humildemente con su Dios.

Ahora,
los que andan conforme a la carne y viven en la práctica de cualquier pecado conocido,
se alejan cada vez más de Dios, y llegan a tener menos vida, menos luz, menos gracia,
menos temor de ofender a Dios y de hacer daño a su prójimo,
como se puede ver por la conducta de los hombres.
Y esta continua decadencia es morir a la justicia.

Y así como los que viven conforme a la carne tienen menos vida, menos luz, menos gracia,
y menos temor; así los que andan conforme al Espíritu, haciendo cosas que son rectas,
honestas, y honorables a partir de la Semilla justa sembrada en sus propios corazones,
encuentran un incremento.
Estos llegan a tener más vida, más luz, más gracia,
y más temor de ofender a Dios o a su prójimo.
Y experimentar este incremento es vivir para la justicia.
Mientras el uno se aleja, el otro se acerca al reino de los cielos.

Si no tuviéramos en nosotros tanto el Espíritu como la carne,
la luz como también la oscuridad, un Conductor en el camino de la vida y salvación,
así como a un líder en los caminos de destrucción,
podríamos echar toda la culpa de la pérdida de vida
y las calamidades del pecado sobre la cuenta de Adán,
o cargarlas exclusivamente a la cuenta del maligno,
de quién proceden todas las inclinaciones malignas.
Pero Pablo era un maestro experto en teología espiritual.
Él sabía lo que corrompía a los hijos e hijas de los hombres,
y de dónde surgía toda la perversidad que hay en este mundo.
Y para limpiar, purgar, purificar,
hacer que los paganos se vuelvan cristianos verdaderos,
y los pecadores se vuelvan santos, él no describe ningún otro medio sino este,
"`Andad en el Espíritu.`"
Porque a medida que nos aferremos a este Espíritu,
aprenderemos (como lo hicieron los Paganos convertidos) no solo a negar la impiedad,
sino también a vivir piadosamente en este mundo presente.

Sin embargo, si no hacemos uso de los medios antes mencionados,
sino que descansamos en prácticas externas (como hicieron los celosos fariseos),
considerándonos justos debido a una supuesta forma correcta de piedad, entonces,
aunque tengamos tanto celo por nuestras formas y prácticas
como lo tuvo Pablo por la religión de los judíos,
no nos aprovecharía más de lo que la circuncisión hubiera aprovechado a los gálatas.

Hemos tenido mucha predicación y enseñanza.
Los gozos del cielo han sido prometidos a los que hacen el bien;
los tormentos del infierno han sido amenazados para los que hacen el mal.
Pero ¿todas estas promesas y amenazas nos han hecho una nación santa y un pueblo escogido,
superando a todos los demás en los frutos del Espíritu?
¿Todas las exhortaciones que hemos recibido nos han
capacitado para hacer morir el cuerpo de pecado,
que es la causa de impiedad?
¿Hemos sido de este modo (como fueron los Paganos) trasladados
de las tinieblas al reino del amado Hijo de Dios,
para tener nuestra ciudadanía en el cielo incluso
mientras nuestros cuerpos están en la tierra?
¿Podemos decir verdaderamente que, "`las cosas viejas pasaron,`"^
footnote:[2 Corintios 5:17]
todos los pensamientos altivos, todos los apetitos codiciosos, toda ira y amargura;
y que cosas nuevas han llegado en su lugar, como: humildad, mansedumbre, templanza,
abnegación, con un amor sincero hacia Dios y a nuestro prójimo?
¿Podemos decir que,
hubo un tiempo en el que el pecado tuvo tal dominio sobre nosotros
que no podíamos abstenernos de satisfacer los deseos de la carne,
pero ahora estamos tan gobernados por el Espíritu eterno que debemos ser moderados,
debemos ser sobrios y vigilantes, debemos ser justos, rectos,
y fieles en palabras y obras`'? Si este es realmente nuestro estado, entonces,
al igual que los primeros Cristianos en su estado más pleno,
estamos muertos al pecado y vivos para la justicia,
habiendo sido edificados sobre la misma roca que ellos experimentaron.
Mas si no hemos llegado a esto,
sería prudente volvernos al Señor (como lo hicieron ellos) y construir
sobre el mismo fundamento sobre el cual ellos construyeron,
a saber, la "`luz verdadera, que alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera Gómez]
para que lleguemos a familiarizarnos con el Espíritu eterno,
(igual que ellos) y tener un Guía y Líder en los
caminos de la santidad (como ellos tenían);
porque es por medio y a través del poder del Espíritu eterno de Jesús
en nuestros corazones que nuestras corrupciones deben ser eliminadas,
y nuestro interior limpiado.
Porque en verdad, como nuestro andar conforme a la carne ocasionaba todas las heridas,
así también nuestro andar conforme al Espíritu debe sanar todas las heridas.
Así como nuestro vivir conforme a la carne hacía que aumentara nuestra injusticia,
así nuestro andar en el Espíritu hace morir el pecado, y recupera una vida de justicia.

Pablo habló a partir de un buen entendimiento cuando les dijo a los Romanos,
"`porque lo que se conoce acerca de Dios es evidente dentro de ellos.`"^
footnote:[Romanos 1:19 LBLA]
Es allí donde él obtuvo su conocimiento en los misterios de la piedad;
cualquier cosa que predicara, cualquier cosa que escribiera,
la fuente estaba en sí mismo.
Él no sabía más de la obra interna y espiritual de la gracia que cualquier otro hombre,
hasta que llegó a tener sus ojos vueltos hacia el interior, y a andar en el Espíritu;
entonces recomendó a las iglesias lo que él mismo había experimentado.

Muchos pueden hablar de la redención, la justificación, la santificación,
y la salvación por medio de Cristo,
pero el Cristiano es aquel que experimenta estas cosas formadas en sí mismo.
Tales pueden ser llamados apropiadamente hombres entendidos;
porque conocen lo que significa levantarse con Él,
lo que significa morir y lo que significa vivir,
saben de qué han sido redimidos y salvados, y por qué medios.

La quinta cosa, a considerar es, cómo los hijos e hijas de los hombres pueden,
a través del Espíritu, hacer morir las obras de la carne.

Pero primero, consideremos cuáles obras de la carne deben morir.
Puesto que un espíritu maligno en el hombre es la raíz de todas las obras malignas,
_cada obra que procede de esa raíz_ tiene que morir.
Y nada puede manifestar tales obras,
brindándonos una verdadera visión de su naturaleza y surgimiento,
sino el Espíritu del Señor, o la Luz de justicia en nuestros propios corazones,
a medida que resplandece con claridad.

Para saber cuáles de nuestras obras o actividades tenemos que hacer morir,
debemos considerar nuestro objetivo en ellas.
Si no tenemos otro fin más que la justicia, equidad, honestidad y amor,
podemos proceder con seguridad; pero si el yo es lo que nos mueve,
si no estamos buscando el bien de nuestro prójimo junto con el nuestro,
pretendamos lo que pretendamos,
tales obras proceden de una raíz maligna y tienen que ser negadas; y al negarlas,
las hacemos morir.
Y, ¿qué puede manifestar nuestro objetivo en cada acción? No los libros,
ni los predicadores, sino solamente el Espíritu del Señor, que es una luz interna.

Ahora,
no encontramos que Pablo haya acusado directamente
a los gálatas de ningún tipo de pecado manifiesto,
sino solamente de "`guardar los días, y los tiempos;`" y ¿qué mal podría haber en eso?

Puede que los gálatas no hayan visto ninguno, aún así Pablo vio mucho,
de lo contrario no les hubiera preguntado,
"`¿quién os fascinó...?`" Porque ellos habían comenzado en el Espíritu;
habían caminado por un tiempo tras un Guía interno,
que es el único líder hacia la clase de vida justa que el Señor
(en todas las eras) ha requerido de los hijos e hijas de los hombres.
Esta no era una apariencia de piedad sin vida, sino la verdad en lo íntimo;
porque si tenemos la verdad en nuestros corazones,
la justicia se llevará a cabo por nuestras manos.
Y, Pablo sabía que ellos nunca podrían llegar a esto imitando una adoración externa,
ni mucho menos guardando los días y los tiempos,
y por lo tanto consideró tales cosas como obras de la carne,
argumentando con ellos de esta manera: "`¿Tan necios sois?
¿Habiendo comenzado en el Espíritu, ahora os perfeccionáis por la carne?`"^
footnote:[Gálatas 3:3 Reina Valera de Gómez]
Es como si hubiera dicho, '`¿Están tan vacíos de entendimiento?
Habiendo empezado a caminar en novedad de vida,
¿esperan llegar a tal perfección como para tener su ciudadanía
en los cielos mientras viven en la tierra,
volviendo a las prácticas de ritos externos?`' "`Esta persuasión,`" dijo,
"`no procede de Aquel que os llama;`"^
footnote:[Gálatas 5:8]
y si no proviene de Dios, debe provenir del antiguo engañador.
Y en verdad, muchos han sido engañados de esta manera,
persuadiéndose a sí mismos que la piedad consiste en eso
que es llamado (pero no lo es) verdadera devoción,
y sin embargo viven en orgullo, codicia, envidia,
y muchas otras cosas que claramente son obras de la carne,
nunca llegando a ser trasladados del reino de la oscuridad,
ni a vivir bajo el gobierno del Espíritu eterno.

La caída del hombre no fue de ninguna religión externa o apariencia de piedad,
sino de la vida de justicia.
El hombre cayó de un estado en el que el esposo, la esposa, los padres, los hijos,
los señores, los sirvientes, y todas las otras relaciones,
habrían sabido su lugar y deber,
y habrían permanecido allí. Cayó de un estado en donde todas
las cosas creadas que Dios había dado para el uso del hombre,
se habrían utilizado correctamente,
y ninguna de ellas habría sido malgastada a causa del exceso.
Cayó de un estado en el que la verdad se habría encontrado en todas nuestras palabras,
y la equidad en todas nuestras obras;
de un estado en donde la voluntad de Dios se habría hecho en la tierra como en los cielos,
y el gran Dios habría sido glorificado por nosotros, y no deshonrado.
De este estado,
los hijos e hijas de los hombres (a través de la
entrada y crecimiento del pecado) se han apartado;
y a este mismo estado,
los primeros Cristianos (por medio de hacer morir al pecado) habían regresado.

Esta fue la vida que perdió el primer Adán. Esta es la vida que vino a
recuperar el segundo Adán. Y todos los que tengan el Espíritu de Cristo,
y se conviertan en verdaderos seguidores de lo mismo, se levantarán de esta caída,
regresarán a Dios, vivirán bajo Su gobierno,
y se volverán testigos de esta vida celestial restaurada.

Cuando he mirado el Libro de Oración Común,
he encontrado que las palabras en él son tan buenas
como se pueden recopilar de las Escrituras,
con el requisito de que no se admita ni a un solo hombre
en la iglesia sin prometer hacer todo lo que he mencionado.
Si estas promesas se cumplieran realmente, seríamos en verdad una nación santa,
que de ninguna manera quedaría corta de los santos más eminentes;
porque los que más alto han llegado,
no han llegado a un estado más alto que "`caminar en los
mandamientos de Dios todos los días de sus vidas.`"^
footnote:[Un Catecismo; 1662 [.book-title]#Libro de Oración Común.#]

Pero es muy raro encontrar a un hombre que lleve a cabo este pacto, y la razón es esta:
decimos que las Escrituras son nuestra regla, pero no atendemos su consejo.
No le hacemos caso al consejo de Pablo;
nosotros no "`andamos en el Espíritu;`" porque si lo hiciéramos,
la luz de justicia en nuestros corazones nos mostraría
el surgimiento de cada inclinación maligna,
y a qué nos lleva.
Este es el tiempo de "`renunciar al diablo y a todas sus obras,
con todas las vanidades del mundo y deseos pecaminosos:`"^
footnote:[Un Catecismo; 1662 [.book-title]#Libro de Oración Común.#]
porque si rechazamos todas las inclinaciones malignas,
nunca seremos encontrados en actos malignos; y hasta que dejemos de hacer lo malo,
no aprenderemos a hacer el bien.^
footnote:[Isaías 1:16-17]
El pecado debe ser crucificado antes de que podamos vivir una vida de justicia.
Las obras del diablo deben ser rechazadas,
antes de que se pueda caminar en los mandamientos de nuestro Dios incluso un día,
mucho menos "`todos los días de nuestras vidas.`"

Y Pablo experimentó esto, lo que lo hizo decir con gran certeza, "`Andad en el Espíritu,
y no satisfagáis los deseos de la carne.`"
Porque si rechazamos y nos volvemos de cada inclinación que la luz de
Cristo nos muestra como maligna en nuestros propios corazones,
no las cumpliremos.
Al contrario, haremos morir la raíz de la cual surgen; porque eso que no es alimentado,
con el tiempo llega a morir.

Así, los Paganos convertidos llegaron a ser una nación santa.
Esta es la manera de convertirse en ciudadanos de la Nueva Jerusalén. Por este medio,
los Colosenses fueron (y nosotros también podemos
serlo) trasladados al reino del amado Hijo de Dios,
para vivir bajo Su gobierno.
Este es el reino que Juan el Bautista proclamó que se había acercado.
Este es el reino por el cual los discípulos de Cristo fueron instruidos a orar.
Este es el reino que consiste en justicia y se establece en poder.
Este es el reino que todos los creyentes deben buscar primero;
porque bajo el gobierno del Espíritu eterno de Jesús en sus corazones,
los hijos e hijas de los hombres no pueden hacer ninguna cosa injusta.

Muchos de los profesantes actuales del cristianismo son persuadidos de que,
aunque sus vidas siguen siendo injustas, aún así,
por estar en la práctica de algo llamado religión, les irá bien al final.
Sin embargo, el Señor viviente no toma en cuenta qué religión profesamos,
sino a qué líder seguimos; porque no importa cuál sea nuestra religión,
si vivimos conforme a la carne, moriremos.
Y aunque parezca que tenemos lo que se considera religión,
si andamos conforme al Espíritu, si nuestra ciudadanía está en los cielos,
si la verdad está en nuestras bocas y la justicia es llevada a cabo por nuestras manos,
viviremos.

Pero ¿quién es capaz de andar conforme al Espíritu,
y a través del Espíritu de hacer morir las obras de la carne?

Hay muchos, incluso entre los que llevan el nombre de Cristianos,
quienes a través de una perseverancia en hacer el mal,
han llegado a estar muertos en pecado,
han perdido toda sensibilidad y consciencia de ese don en sí mismos que es de Dios;
y estos, que no están familiarizados con el Espíritu,
ciertamente no pueden "`andar conforme al Espíritu.`"

Hay otros que no están muertos, sino muriendo.
Todavía tienen sensibilidad y cierta conciencia;
tienen eso en sí mismos que los guiaría a cosas mejores que las que ellos practican,
pero le prestan poca o nada de atención. No lo toman como su guía. Y mientras
rechazan esa luz dentro de ellos que manifiesta las obras de la carne,
no pueden de ninguna manera hacerlas morir.

Pero se pueden encontrar algunos que están cansados
de sus pecados y cargados con sus iniquidades,
teniendo en sí mismos hambre y sed de justicia.
Tales como estos son un pueblo vivo, y capaz, a través del Espíritu,
de hacer morir las obras de la carne.

Estoy convencido de que muchos han sido despertados
del sueño del pecado en nuestra era presente,
y han encontrado en sí mismos una verdadera hambre y sed de justicia;
pero habiendo sido despertados por un ministerio externo,
han esperado que su hambre y su sed sean satisfechos por este.

Muchos pueden ser despertados, pero no ser vivificados, por un ministerio externo.
"`El Espíritu,`" como dijo Jesús,
"`es el que da vida;`" y ¿qué puede vivificar sino aquello que da vida?
¿Qué puede satisfacer un alma que está sedienta de justicia,
sino eso que en verdad es la fuente misma de justicia?
Es en nosotros mismos que el pozo debe ser hallado,
donde aquellos que beben no tendrán sed jamás. Solamente
allí está la fuente que salta para vida eterna.

Así como el reino de los cielos no consiste en palabras sino en poder,
así no son las palabras sino el poder de Dios que
puede hacer morir las obras de la carne,
cambiar nuestra naturaleza, y hacernos nuevas criaturas.
Si las palabras nos pudieran llenar de justicia, juicio, verdad, equidad y fidelidad,
desde hace mucho tiempo habríamos sido una nación santa,
porque no ha habido falta de palabras;
pero todavía hay una gran falta de justicia y fidelidad.

Si las palabras buenas pudieran llevar a los oyentes a una vida de justicia,
entonces en lugar de decir "`Andad en el Espíritu,`" Pablo les habría dicho a los gálatas,
"`¡Escuchen a su ministro!`" Él no habría tenido
la necesidad de encomendarlos al Guía interno.^
footnote:[Hechos 20:32]
Pero la experiencia de Pablo le demostró, que no era por el oír de las palabras,
sino a través de la obediencia a la ley del Espíritu,
que hizo morir las obras del cuerpo, y llegó a vivir una vida justa.
Y lo que resultó ser eficaz en sí mismo, lo recomendó a las iglesias.

Las palabras, por numerosas que sean, pueden ser fácilmente olvidadas;
estas no permanecen.
Pero el Espíritu eterno permanece,
y es ese "`maestro`" el que "`nunca más te será quitado.`"^
footnote:[Isaías 30:20]
El uso de las palabras en la obra de salvación es
despertar a aquellos que duermen en pecado,
y volverlos (como Pablo volvió a los Paganos)^
footnote:[Hechos 26:18]
al Guía interno, y también para amonestarlos a mantenerse aferrados a su Guía,
mientras se encuentran en su viaje.

Si los que tenían hambre y sed de justicia hubieran buscado fervientemente lo que deseaban;
si se hubieran familiarizado con el Espíritu eterno que engendraba esos deseos,
y seguido Su dirección, Él habría desarraigado todo orgullo y egoísmo de ellos.
Él los habría llevado a un estado humilde, bajo, manso, paciente, y pacífico,
y a hacer lo que es correcto en todo momento.
Esto en verdad habría removido su carga, y les habría dado descanso y paz.

Y si queremos ser como los primeros Cristianos,
debemos comenzar por donde ellos comenzaron.
Debemos volvernos a la luz de justicia en nuestros propios corazones,
y andar en esa luz hasta convertirnos en hijos de la luz.
Debemos caminar en la senda de los justos por la luz de la aurora,^
footnote:[Proverbios 4:18]
hasta que la justicia sea nuestro centro.
Esto convirtió a los primeros Cristianos en un pueblo verdaderamente piadoso;
por medio de esto ellos prosperaron,
de lo contrario los paganos ciegos e ignorantes nunca hubieran llegado
a ser conciudadanos de los santos y miembros de la familia de Dios.

Pablo no era un ministro establecido en un solo lugar, lo escucharon muy pocas veces;
pero escuchaban la voz del Espíritu eterno cada vez
que transgredían el pacto de la luz y la vida.
Es a esta voz a la que los cristianos deben inclinar su oído; porque bajo el nuevo pacto,
Dios habla a Su pueblo por medio de Su Hijo,
a través del Espíritu eterno en sus corazones.

El primer paso para lograr una vida de justicia es familiarizarnos con el don de la
gracia en nuestros propios corazones que nos reprende a causa de la impiedad;^
footnote:[Tito 2:11]
porque hasta que lleguemos a esto, somos ajenos al fundamento de una vida piadosa.
Porque cada aspecto de nuestra edificación, de nuestro viaje espiritual,
de nuestro levantamiento de la caída y acercamiento al reino de Dios,
depende completamente de que neguemos,
rechacemos y abandonemos absolutamente lo que la luz de
justicia reprende y reprueba en nuestros corazones;
porque al negar todo lo que es contrario a la luz, hacemos morir las obras de la carne.
A medida que nos ocupamos de esto, y somos fieles en ello, Su luz brilla más y más;
y cuanta más luz tengamos, mayor será el descubrimiento que ella hace de lo que es malo,
de lo que se debe negar, rechazar y abandonar.
Así que, guiando nuestros pasos por esto, edificamos sobre el verdadero fundamento,
caminamos en el camino vivo, crecemos en la gracia y en el conocimiento de Cristo,
y nos acercamos más y más a Su reino y gobierno de justicia;
y Su poder es experimentado en una vida justa.

Este fue el consejo de Cristo:
"`Esforzaos por entrar por la puerta estrecha;`" testificando,
que el camino a la vida eterna era estrecho y difícil.
¿Qué significa esta puerta angosta, y camino estrecho?
No egoísmo, ni tampoco justicia propia.
El egoísmo es la raíz de todas las prácticas codiciosas,
de todos los tratos y negocios deshonestos, y de todas las acciones injustas.
La justicia propia es la raíz de toda formalidad y contienda acerca de la religión,
de la cual ha habido (y todavía hay) demasiada en el mundo cristiano,
persiguiéndose unos a otros,
tal como los Paganos inconversos persiguieron a los primeros convertidos.

Ninguno de estos caminos lleva a ese reino que consiste
en justicia y paz en el Espíritu Santo.
Si los paganos recién convertidos hubieran caminado en estos caminos,
nunca se habrían convertido en una nación santa,
porque su ciudadanía habría estado en la tierra y no en los cielos.
Pero la puerta estrecha y el camino angosto, que llevan a una vida justa,
es la abnegación--una negación de todo lo que procede de la raíz del mal,
desde el asunto más pequeño hasta el deseo más grande;
lo cual nada puede manifestar sino una luz interna que resplandece con claridad.
Pero con tristeza podemos decir,
que es raro encontrar (aún entre muchos) a uno que viva
en la práctica de lo que él mismo reconoce como correcto.
¿Quién no confesará que decir la verdad en todo momento es algo correcto?
¿Quién no reconocerá que cumplir nuestra palabra, aunque sea para nuestro perjuicio,
es algo honesto?
¿Quién no concederá,
que hacerles a todos los hombres como queremos que nos hagan a nosotros, es algo justo?
Sin embargo, ¿Cuán pocos viven en la práctica de estas cosas?
Y si no vivimos en la práctica de lo que sabemos que es correcto,
¿de qué nos sirve saberlo?
Podemos seguir moviéndonos, como lo hizo Israel en el desierto,
pero a menos que caminemos en el camino estrecho,
nunca podremos llegar a una vida justa.

Entonces, si no cerramos deliberadamente nuestros ojos,
podemos ver con claridad que el camino hacia una vida justa es,
"`andar en el Espíritu,`" someternos al gobierno de nuestro Guía interno,
negar y apartarnos de todo lo que la luz de justicia
manifiesta en nuestros corazones como impío,
injusto, o deshonesto.
Y al apartarnos del mal, nos acercamos al Único que es bueno; al abandonar lo malo,
buscamos ser llenos con virtud; al morir al pecado, somos vivificados para la justicia,
y entonces la verdad, la pureza, y el amor llegan a tener dominio en nuestros corazones.
A tales como estos, Pablo dijo,
"`No hay condenación;`" porque tienen "`el testimonio de una buena conciencia,`"^
footnote:[1Pedro 3:21 Reina Valera de Gómez, Reina Valera 1602 Pur.]
paz con Dios, y paz en sí mismos--paz mientras están aquí, y paz cuando partan.
