[short="Capítulo II -- Consideraciones Sobre el Discurso Anterior"]
== Capítulo II. Consideraciones Basadas en el Discurso Anterior

El hombre fue creado (como muchos reconocerán) para
glorificar a Dios y hacer Su voluntad en la tierra.
Y para que el hombre fuera capaz de servir a su Creador según Su voluntad,
Dios le dio una medida de Su buen Espíritu como instructor;
de modo que había mucho de Dios en el hombre,
tal como fue creado al principio--mucha humildad y mansedumbre,
mucha verdad y fidelidad, mucha sabiduría y entendimiento celestiales.

Este Espíritu eterno debía ser la cabeza y líder del hombre,
el guía e instructor del hombre en los caminos de justicia.
En este Espíritu el hombre debía fijar su ojo;
a este Espíritu el hombre debía inclinar su oído;
por este Espíritu el hombre debía ser gobernado; y así, siguiendo a este guía,
líder e instructor,
el hombre habría sido capaz de gobernarse a sí mismo
y la creación sobre la cual fue hecho señor,
según la voluntad de Dios.

Si la humanidad viviera bajo el gobierno de este Espíritu eterno,
todos llevaríamos la imagen de Dios.
Todos seríamos piadosos, humildes, mansos, misericordiosos, pacientes, pacíficos,
íntegros y fieles; rectos en todos nuestros caminos, y justos en todas nuestras obras.
Pero al no mantenerse aferrado a este Guía,
el hombre desobedece el mandamiento de su Creador.
Y al entregarse como siervo a otro señor,
entra en él otro espíritu que es tan contrario en
naturaleza como los son las tinieblas a la luz.
Y cuantos siguen a este otro líder, no sirven al Dios del cielo,
sino al dios de este mundo; porque todo hombre es esclavo de aquel a quien obedece.^
footnote:[Romanos 6:16]

Ahora nosotros, siendo descendientes de Adán en su estado caído, llevamos su imagen.^
footnote:[Génesis 5:3]
Dentro de nosotros tenemos tanto el bien como el mal,
una Semilla de gracia y una semilla de pecado.
Estas, en la Escritura, son llamadas luz y tinieblas, carne y espíritu,
el viejo hombre y el nuevo hombre,
según el crecimiento de las semillas dentro de nosotros
y el dominio que llegan a tener sobre nosotros.
Porque así como hay diferencia entre una semilla y una hierba, una planta y un árbol,
un niño y un hombre, así también hay diferencias en la gracia y en el pecado;
según su crecimiento en nosotros, así sentimos su fuerza,
y los nombres dados en las Escrituras corresponden a ello.

Porque aunque todos tenemos una semilla de pecado en nosotros,
no por ello somos dominados por ella,
ni estamos completamente esclavizados por ella tan pronto como nacemos.
Necesita tiempo para brotar y crecer en nosotros
antes de llegar a tener dominio sobre nosotros.
Y lo mismo se puede decir de la Semilla de gracia,
porque su naturaleza es también crecer;
de lo contrario el reino de los cielos (o gobierno
de Cristo en los corazones de Su pueblo),
no habría sido comparado con un grano de mostaza, el cual,
a pesar de ser pequeño cuando es sembrado,
luego brota y va creciendo hasta llegar a ser muy grande.

Hay, en verdad, muchos en el mundo que son notoriamente impíos,
y que se mostrarían mucho más impíos si no estuvieran limitados por una ley externa.
Estos no nacieron así;
es el crecimiento del pecado y el incremento de su dominio sobre los hombres
lo que los hace notoriamente impíos. Porque la semilla de pecado,
cuando llega a su pleno crecimiento en cualquiera de los hijos e hijas de los hombres,
los convierte en su misma naturaleza,
por lo que llegan a ser habitualmente activos en la maldad.

Este fue el objetivo del diablo en la caída de Adán,
pero como su objetivo no fue entonces llevado a cabo completamente,
ha seguido a los hijos e hijas de los hombres en
todas las edades del mundo (y lo hace en este día),
poniendo sus inclinaciones malignas en sus mentes junto con varias tentaciones,
presentando falsas apariencias,
y pintando las cosas prohibidas con un hermoso brillo que resulta
más atractivo para el hombre caído que las sendas de justicia.
Todas sus inclinaciones malignas, tentaciones, carnadas, trampas,
anzuelos y falsas apariencias,
son para llevar a cabo su plan original--y siendo
atrapados y alejados de Dios por estas cosas,
nos olvidemos de nuestro Dios y hagamos que Él quite Su Espíritu Santo de nosotros.
Hasta entonces, el dios de este mundo no puede llamar suyo a ningún hombre;
podemos ser sus cautivos, pero no tiene completo dominio sobre nosotros.

En nuestra presente edad, hablar de la luz de Dios en el interior,
de la ley en el corazón, del Espíritu en el interior, de Cristo en nosotros, etc.,
es motivo de burla para algunos y de poca estima por muchos.
Pero lo sepan o no, debo decirles,
que se burlan y desprecian el tesoro más grande que jamás ha sido dado al alma del hombre.
Menosprecian el talento celestial que Dios le ha dado a cada hombre para que lo incremente,
con el fin de lograr que se levante de su caída y regrese a su tierra natal,
para vivir bajo el gobierno del Espíritu eterno.
Cualquiera que esté sin el Espíritu y luz interna, está sin Dios en el mundo.
Si se quitara este tesoro, no tendríamos nada en nosotros que fuera bueno;
quedaríamos absolutamente sin gracia.

Leemos de Jacob y Esaú,
quienes eran figuras vivientes de estas dos semillas en el hombre,
cómo luchaban mientras estaban en el vientre de Rebeca.
Y así como hubo una lucha entre la simiente de dos naciones en el vientre de Rebeca,
así hay una lucha entre la simiente de dos reinos en cada hombre,
en cuanto a cuál de ellos se levantará para gobernar
en nosotros y tener todo el dominio sobre nosotros.

Cuando nacemos en el mundo, todos somos inocentes.
Aunque tenemos una semilla de pecado en nosotros,
no somos verdaderamente pecadores hasta que cedemos ante
las inclinaciones pecaminosas que proceden de ella.
El diablo sabe esto (aunque muchos opinan diferente), por lo tanto,
con el fin de que la semilla que él ha sembrado brote y crezca,
y que un espíritu malo llegue a gobernar en nosotros, comienza su lucha a temprana edad,
antes de que podamos distinguir la mano izquierda de la derecha.

Ahora, donde la maldad no es reprimida por padres o tutores cuidadosos,
rápidamente se convierte en la cabeza,
y tales personas pueden decir (como muchos lo hacen hoy):
"`No hay nada bueno en nosotros.`"
Porque, por el rápido crecimiento de lo que es malo,
estos nunca llegan a tener conocimiento de lo que es bueno,
excepto por las reprensiones internas,
que pocos están dispuestos a reconocer que provienen de Dios.
Porque tal como las malas hierbas, que se dejan crecer en un jardín,
ahogan y reprimen las buenas plantas, así el vicio suprime la virtud,
y hace que la creación de Dios sea tan ajena a su Creador que,
a pesar de que '`en él viven, se mueven y son`'^
footnote:[Ver Hechos 17:28]
viven sin ningún sentido o percepción de Su presencia.

Y así como todas las inclinaciones perversas que nos llevan al pecado,
todas las carnadas,
trampas y anzuelos que nos encontramos en el transcurso de nuestras vidas,
son las luchas y esfuerzos de la semilla del mal en nosotros;
así mismo todos los llamados que encontramos en nosotros a la justicia, honestidad,
verdad y fidelidad, con todas las reprobaciones,
reprensiones y convicciones que sentimos internamente,
son las luchas y esfuerzos de la buena semilla.
Y si estas cosas son atendidas, obedecidas, seguidas y vividas,
ellas detienen el crecimiento del mal; de modo que,
aunque tenemos una raíz de pecado en nosotros, ésta permanece impotente;
no se levanta ni llega a reinar sobre nosotros.

Por esta razón, los padres y tutores deben estar muy atentos para suprimir el pecado,
a fin de permitir el crecimiento de la gracia.
Porque así como el maligno se aprovecha de nuestra niñez para hacernos
cometer maldad antes de que conozcamos aquello que es bueno,
los padres y tutores (como fieles desyerbadores) deben vigilar, suprimir,
detener y usar todos sus esfuerzos para desarraigar la maldad en cuanto aparezca,
hasta que la gracia crezca,
y un Espíritu recto llegue a reinar en ellos y a tener dominio sobre ellos.

Pero este es nuestro estado actual: así como Esaú, que por sus luchas dentro de Rebeca,
llegó a ser el primogénito en la antigüedad, de igual manera, la iniquidad,
por el surgimiento de la serpiente sutil a temprana edad, sigue siendo el primogénito.
Y a pesar de que la mayoría de los padres en el mundo
cristiano a veces se preocupan por proveer desyerbadores,
es muy poca la maleza que realmente arrancan, y muchos padres no arrancan nada;
por lo cual, ante esta gran negligencia, la mayoría de los niños llegan a ser indomables,
tercos, obstinados, desobedientes a los padres y muy impíos en sus vidas.
Pero el fundamento de toda impiedad es el crecimiento de esa semilla que
el maligno sembró. ¿Y cómo se puede derribar la maldad cuando ya ha brotado?
No por padres, tutores o predicadores; sino que, así como Jacob suplantó a Esaú,
así también la gracia debe suplantar al pecado.
Porque vemos que, a pesar de toda la predicación,
hay mucho más orgullo y arrogancia que humildad y mansedumbre,
más tratos engañosos y prácticas malvadas que negación al yo,
más deseo por el mundo y sus vanidades que por el reino de los cielos y su justicia.
Y siempre será así, mientras el primogénito tenga la preeminencia.

Y si queremos que el primogénito sea suplantado;
si queremos que aquello que se esfuerza por privarnos de vida, luz,
gracia y toda bondad sea hecho impotente;
si queremos que sea reprimido aquello que continuamente trabaja
para hacernos siervos del pecado y esclavos de Satanás;
si queremos experimentar la muerte de aquello que nos hace
incapaces de glorificar a Dios con nuestras vidas;
si queremos ser librados (como lo fueron los primeros cristianos) de la
potestad de las tinieblas y trasladados al reino del amado Hijo de Dios,
para vivir bajo el gobierno de Su Espíritu eterno,
que fue el primer estado del hombre--entonces consideremos
cómo surgió eso que ahora nos estorba,
y por qué medios puede ser derribado.

He dicho, y digo otra vez, que no es la mera presencia de la semilla del mal,
sino el crecimiento y reino de ella,
lo que hace que los hijos e hijas de los hombres sean orgullosos, arrogantes, altivos,
envidiosos, crueles, despiadados, fraudulentos e impíos;
oscureciendo sus entendimientos y haciéndolos ajenos al don de Dios en sí mismos.
Y el crecimiento de esta semilla del mal se debe a que a menudo
cedemos a las inclinaciones perversas que proceden de ella.
Esto lo sabe la sutil serpiente, y nosotros podemos saberlo también,
por las múltiples tentaciones que sentimos hacia el mal,
especialmente donde nuestro enemigo ha encontrado que son efectivas.

¿Quién ha cedido alguna vez a una inclinación perversa,
cometiendo pecado y disfrutando de ello,
y luego no ha sido tentado nuevamente a hacer lo mismo?
¿O quién no sabe, que cuanto más a menudo cedemos a cualquier tentación,
más fuertes se vuelven y más difíciles de negar?
Y cada vez que cedemos, el pecado se levanta y llega a tener más poder sobre nosotros.

Por lo tanto,
si ceder ante las inclinaciones perversas hace que el espíritu
maligno se levante y llegue a tener poder en nosotros,
entonces,
negar las inclinaciones perversas hace que dicho
espíritu sea suplantado y pierda su poder en nosotros.

Todo aquel que desee ser un seguidor de Cristo debe aprender primero a negarse a sí mismo.
Debemos apartarnos de todo aquello que la luz eterna
en nuestro propio corazón nos muestra ser egoísta,
sin importar cuánto parezca ser una desventaja para nosotros;
y al negarnos a nosotros mismos,
negaremos abundantemente al autor de todas las inclinaciones perversas.

El orgullo, el placer y la ambición personal son carnadas que han atrapado a muchos.
Estas, junto con muchas otras cosas,
deben ser negadas y evitadas si queremos ser seguidores de Cristo en una vida de justicia.
Y por medio de negaciones continuas hallaremos que la raíz de la iniquidad se seca,
y la gracia crece; los deseos pecaminosos disminuyen y los deseos celestiales aumentan;
la pequeña semilla se convertirá en la mayor de las hortalizas;
y la masa de harina llega a ser una en naturaleza con la levadura celestial.

Pero esta negación debe hacerse mientras el dragón aún está en el cascarón, es decir,
mientras el pecado todavía es una inclinación, antes de que se convierta en una acción;
porque las inclinaciones pecaminosas pueden ser rechazadas,
pero las acciones pecaminosas no se pueden deshacer.
¿Y qué nos puede mostrar el surgimiento de las inclinaciones malignas?
Los predicadores no pueden; los libros no pueden;
nada que esté fuera puede mostrarnos eficazmente lo que está dentro.
Debe ser una luz interior; debe ser la lámpara del Señor,
el Espíritu eterno que desde el principio fue dado al hombre como instructor.

En las Escrituras leemos acerca de hombres buenos, hombres fieles, hombres abnegados,
incluso cuando no había predicadores ni libros;
¿y quién era su maestro sino el Espíritu eterno?
¿Qué guía tenían sino la luz de justicia en sus propios corazones?
Y si nuestros predicadores de hoy en día se preocuparan
por volver los corazones de las personas a este Guía interior,^
footnote:[Ver Hechos 26:18 y Hechos 20:32]
y convertirlos en fieles seguidores de Él, tendríamos más hombres buenos,
más hombres fieles y más hombres abnegados, que los que se pueden encontrar ahora.

Ni los hombres ni los ángeles podrían dar mejor consejo
a un pueblo que se ha vuelto hacia esta luz interior,
que aquel que Pablo dio a los Gálatas cuando los exhortó diciendo:
"`Andad en el Espíritu`"; porque si no somos guiados por un Espíritu justa,
nunca podremos llevar una vida de justicia.

Pero así como la semilla de pecado crece y se fortalece
en nosotros cuando nos entregamos a las inclinaciones malignas,
así también crece y se fortalece la Semilla de gracia
en nosotros al negar las inclinaciones malignas.
Al despojarnos del viejo hombre nos revestimos del nuevo,
y el nuevo hombre es el que nos hace nuevas criaturas,
y el que engendra una vida nueva y celestial.

Si no aprendemos a negar las inclinaciones malignas,
y a vivir en el continuo ejercicio de ello,
entonces (aunque escuchemos predicadores todos los días de nuestra
vida) seremos como la puerta que gira sobre sus quicios,
o como Israel en el desierto, avanzando y retrocediendo con frecuencia,
pero quedando cortos de una vida justa,
tal como la primera generación que salió de Egipto quedó corta de la Tierra Prometida.

No podemos permanecer en el camino de justicia hasta que Su luz brille con tal claridad
que podamos ver desde lejos el levantamiento de todas las inclinaciones malignas.
Porque cuando la gracia llega a ser lo más alto en nosotros,
la raíz de iniquidad es lo más bajo.
Cuando una llega a permanecer ante nuestros rostros, la otra queda a nuestras espaldas.
Porque ¿de dónde viene el orgullo y la altivez, la contienda y la rencilla,
el fraude y el engaño, la opresión y la crueldad, sino del autor de toda maldad?
Pero cuando la carne y sus pasiones son crucificadas, tales cosas no se hallan.
Y sin importar qué religión profesemos,
mientras vivamos en la práctica de alguno de esos males,
mantenemos vivo lo que debe ser crucificado.

Donde un espíritu maligno predomina, el hombre no experimenta límites; sus oídos, ojos,
lengua, manos y pies están en libertad.
Siente libertad para escuchar relatos maliciosos, contemplar la vanidad,
hablar con orgullo, precipitadamente, sin discreción y con engaño; para hacer violencia,
aceptar sobornos y para ir a donde desee.
Pero donde gobierna el Espíritu recto, cada miembro del cuerpo queda bajo Su gobierno.
El oído se aparta de las fábulas y el ojo deja de contemplar la vanidad.
No puede (como muchos hacen), cubrirse,
disfrazarse y mentir para lograr sus propios fines.
No permite que salgan de su boca conversaciones vanas,
y sus manos son guardadas de hacer el mal.
No puede caminar por los caminos de impureza,
sino que es amante de la justicia y aborrece la maldad, tanto en sí mismo como en otros.
Y todos podríamos llegar a este estado,
negando todas esas inclinaciones que la luz de justicia
manifiesta como malignas en nuestros propios corazones.

Y ahora mi consejo para todos los profesantes del cristianismo es este: que,
en lugar de contender sobre formas externas de piedad,
presten atención a ese don en sí mismos que conduce a la piedad; que,
en lugar de escudriñar las Escrituras en busca de una forma o práctica correcta,
procuren vivir bajo el gobierno del Espíritu correcto;
porque entonces serán librados de la potestad de las tinieblas y regresarán a Sion,
la ciudad de Dios, y a la Nueva Jerusalén,
donde Dios es conocido y verdaderamente adorado.

Hay algo más que quisiera que el lector considerara, y es lo siguiente:
Aunque dos espíritus operan en cada hombre que viene al mundo, sólo puede tener un Señor;
y es Señor aquel que tenga el dominio sobre ti.

El derecho de gobierno en todos los hombres le pertenece al Espíritu
eterno que estaba con el Padre antes de la fundación del mundo.
Este, en las Escrituras, es llamado el Espíritu de Cristo;
porque en Jesús (el segundo Adán) no habitaba ningún otro espíritu.
En Cristo no habitaban dos espíritus,
como sucede con la descendencia del Adán caído. No tenía en Sí mismo luz y oscuridad,
bien y mal, una semilla de gracia y una semilla de pecado; sino que,
como dicen las Escrituras, Él estaba "`lleno de gracia y de verdad.`"^
footnote:[Juan 1:14]
En Él estaba la vida--es decir,
la vida que perdió el primer Adán--como una fuente de justicia; y Él retuvo esta vida,
y así mantuvo fuera el espíritu maligno, que es el autor de toda maldad,
aunque Sus tentaciones excedieron con creces a las de Eva.
Y a pesar de que vivió muchos años en la tierra, y se encontró con muchas provocaciones,
aún así, a lo largo de toda Su vida cumplió toda justicia
y llevó a cabo la voluntad de Dios en la tierra.

Ahora, la Semilla de gracia en todo hombre es una en naturaleza con la plenitud que habitaba
en Él. Y a medida que esta Semilla brota en alguno de nosotros y crece en fuerza y estatura,
nos hace conforme a Su imagen.
Y así, cuanta más gracia tengamos, más humildes, mansos y amorosos seremos.
Cuanta más luz tengamos,
mayores descubrimientos hará de lo que está mal en nosotros
y en los demás. Cuanta más verdad habite en nuestro interior,
menos maldad e impureza será manifestada en el exterior.

Y a medida que andemos en la luz, creceremos en gracia,
y añadiremos a nuestra '`fe virtud, conocimiento, dominio propio, paciencia, piedad,
afecto fraternal y amor;`'^
footnote:[Ver 2 Pedro 1:5-7]
mediante lo cual, como dijo Pedro,
nos "`será otorgada amplia y generosa entrada en el reino
eterno de nuestro Señor y Salvador Jesucristo.`"^
footnote:[2 Pedro 1:11]
El Espíritu recto será exaltado en nosotros,
y tendrá el único gobierno y dominio sobre nosotros;
y bajo el gobierno del Espíritu recto, llevaremos fruto aceptable ante los ojos de Dios.

Ahora bien, siendo el príncipe de las tinieblas enemigo de toda justicia,
hace todo lo posible para cegar los ojos de nuestro entendimiento y mantenernos
ajenos a esta Semilla justa (que es la fuente de toda gracia y virtud interna),
con el fin de alejarnos de Dios y de la piedad.
De modo que,
así como aquellos que andan en la luz del Señor añaden
virtud a la virtud hasta ser llenos de Su justicia,
así también aquellos que siguen la guía del espíritu maligno,
añaden vicio al vicio hasta ser llenos de iniquidad.
Estos también tienen un solo señor,
porque el príncipe de la potestad de las tinieblas tiene todo el dominio sobre ellos.
Y en las Escrituras, estos dos estados son llamados _vida_ y _muerte._

Creo que se puede decir que todo hombre, cuando viene al mundo,
tiene delante de sí la vida y la salvación, y detrás de sí la muerte y la destrucción,
y ambas a cierta distancia de él. También tiene al buen Espíritu
para conducirlo por el camino de la vida y la salvación,
y al espíritu maligno que espera guiarlo por sendas de muerte y destrucción;
y aunque los dos están en él, la mayoría de los hombres son extraños a ambos.
Ahora, la predicación del evangelio era (y todavía debe ser) para abrir esos ojos ciegos,
a fin de que los hombres vean las operaciones y guías de estos dos espíritus en su interior,
y de esa manera se aparten del mal y se conviertan en seguidores de lo que es bueno,
para que Aquel a quien pertenece el derecho llegue
a tener el dominio en ellos y sobre ellos.

Y estoy seguro de que, aunque muchos ignoran estas cosas, aun hay muchos que han visto,
sentido y experimentado algo del Espíritu eterno de Jesús. Estos tienen
en sí mismos el conocimiento de algo que clama por la verdad y la justicia;
y si se aferraran a esto, seguirían al Guía recto, y la Semilla de gracia crecería,
la verdad y la fidelidad crecerían, el conocimiento, la templanza, la paciencia,
el afecto fraternal y el amor crecerían;
y hallarían en sí mismos que es otorgada una amplia y generosa entrada al reino de Cristo.

Pero mientras el espíritu maligno permanezca sin ser crucificado,
el yo se interpone en nuestro camino, y a fin de lograr nuestros fines egoístas,
no se mantienen las balanzas justas, no se hace justicia, no se establece la equidad,
no se guardan las promesas, no se manejan fielmente los compromisos,
y no se abandonan las costumbres y modas de este mundo pecaminoso.
Esto entorpece el crecimiento de la Semilla justa;
pues así como los cananeos no se vencieron mientras la "`anatema`"^
footnote:[Ver Josué 7]
aún estaba en el campamento,
así tampoco se vence la fuerza del pecado mientras
consideremos más al yo que a nuestro Salvador.
La luz es lo que manifiesta al yo,^
footnote:[Efesios 5:13]
y por ella podemos ver adónde conduce cada inclinación maligna; de modo que,
al andar en la luz, andamos en el camino de la salvación de Dios.

Sin embargo,
algunos podrían decir de esta vida eterna (como los hombres
malvados y los hijos de Belial dijeron de Saúl,
el elegido del Señor): "`¿Cómo nos ha de salvar éste?`"^
footnote:[1 Samuel 10:27]
"`¿Qué ventaja podría haber en prestar atención a esta luz?
¡Encontramos en nosotros reprensiones por el pecado,
pero no hallamos nada en nosotros que nos salve del pecado!`"

A estos les digo lo siguiente: Cristo fue dado a los gentiles por luz^
footnote:[Isaías 42:6, 49:6]
y por jefe.^
footnote:[Isaías 55:4]
Mientras nos encontremos en la naturaleza de los gentiles,
mientras andemos conforme a la carne, mientras sigamos las inclinaciones malignas,
estamos apartados de Dios,
alejados de la ciudadanía de Israel y ajenos al nuevo
pacto que Dios hizo con la casa de Jacob.
En este estado no podemos conocer a Cristo, el Salvador del mundo, sino como reprobador;
pero estas reprensiones,
siendo "`reprensiones que nos instruyen,`" son "`el camino hacia la vida;`"^
footnote:[Ver Proverbios 6:23]
sí, el camino hacia esa vida que el primer Adán perdió por la transgresión.

Porque si debido a estas reprensiones nos apartamos de las cosas
por las que somos reprendidos--ya sean conversaciones ociosas,
un estilo de vida desenfrenado, el orgullo,
la pasión o cualquier otro vicio al que nos conduce el espíritu
maligno de este mundo--y seguimos la justicia,
entonces las amonestaciones cesarán, y nuestro reprobador se convertirá en nuestro líder.
Entonces, lo que estaba a nuestras espaldas estará delante de nuestros rostros;
y lo que deseaba dirigirnos, ahora buscará perseguirnos, como Faraón persiguió a Israel,
para traernos nuevamente de vuelta a nuestra pasada manera de vivir,
y _entonces_ experimentaremos a Cristo como nuestro Salvador.
Porque así como los que siguieron a Saúl al inicio de su
reinado vieron cómo los salvó de sus enemigos externos;
así todos los que llegan a ser seguidores del Espíritu eterno
de Jesús ven cómo Él los salva de sus enemigos espirituales.

Mientras seguimos las inclinaciones pecaminosas, seguimos al guía equivocado;
y en este camino podemos experimentar que el poder del pecado prevalece,
pero nunca podremos experimentar el poder de la gracia que restringe y transforma.
Está escrito que Cristo les da poder a todos los que Lo reciben;^
footnote:[Juan 1:12]
pero ninguno Lo recibe en realidad, sino el que se aparta del pecado ante Su reprensión,
y se encomienda a Él como su Salvador.
Sólo estos creen verdaderamente en Su nombre.

Reconozco que el resplandor de la luz interior (que es la primera manifestación de Cristo
a los hijos e hijas de los hombres) parece ser pequeño y sin poder al principio;
y lo mismo sucede con las primeras inclinaciones al pecado.
Pero si seguimos tales inclinaciones pecaminosas hasta donde quieren llevarnos,
las hallaremos suficientemente poderosas.
¿Acaso no se encuentran en este día--aun entre nosotros que somos
llamados cristianos--muchos tan cautivos bajo el poder del pecado,
que un esclavo atado con cadenas de hierro podría romper más fácilmente sus ataduras,
levantarse y regresar a su país natal, que para estos cristianos dejar de pecar,
levantarse de su caída y vivir una vida sobria, justa y piadosa?

Ahora,
si la semilla de pecado tiene tal poder sobre nosotros cuando seguimos sus inclinaciones,
¿acaso no podría la Semilla de gracia tener un poder igualmente grande sobre nosotros,
si regresamos a ella y nos hacemos sus seguidores?
Ciertamente Juan--quien había pasado de muerte a vida,
y vio con sus ojos las cosas como eran desde el principio--sentía
ese poder en sí mismo cuando escribió:
"`Todo aquel que es nacido de Dios, no practica el pecado,
porque la simiente de Dios permanece en él; y no puede pecar.`"^
footnote:[1 Juan 3:9]
Y al día de hoy se pueden encontrar muchos testigos
vivos que pueden decir desde una experiencia palpable,
que donde esta Semilla justa ha brotado y ha llegado a tener dominio,
ha sido tan poderosa y restrictiva que no les ha sido posible ser injustos en sus tratos,
ni infieles en sus promesas; no pueden decir una mentira,
aunque fuera muy ventajoso para ellos; no pueden ser desenfrenados,
malgastando el bien de la creación que Dios les ha
dado para su sustento al comer y beber en exceso;
no pueden oprimir al pobre, a la viuda, ni al huérfano,
ni tomar con violencia aquello que no tienen derecho a tener.
La pequeña Semilla en ellos se ha convertido en la más alta de las plantas,
y tiene tanto poder sobre ellos como el pecado lo
tiene sobre todos los que moran en él. Estos,
como los colosenses, son librados de la potestad de las tinieblas.
Estos, como los filipenses, tienen su ciudadanía en los cielos.
Estos glorifican a Dios en sus vidas,
y así cumplen el propósito por el que fueron creados.

Una abundancia de predicación ha hecho que muchos hablen de Cristo,
pero es la gracia en el corazón y la verdad en lo íntimo,
lo que hace que los hombres caminen como Cristo.
Y no hay manera de alcanzar la plenitud de este tesoro celestial,
sino negando todas las inclinaciones que la luz eterna de justicia
en nuestro interior manifiesta como injustas y deshonestas.
Porque al negar lo malo, escogemos lo bueno;
y así como el crecimiento del pecado radica en abrazar lo que es malo,
así mismo el crecimiento de la gracia radica en abrazar lo que es bueno.

La conformidad con las formas externas de adoración (siendo más
atractiva para las personas que el camino angosto y estrecho de
la cruz) ha recibido en nuestra presente época el nombre de religión,
cristianismo y piedad verdadera.
Pero la conformidad que el Dios vivo requiere es la conformidad
a la imagen de Cristo en todos los aspectos de nuestras vidas;
es decir, ser santos como Él es santo.
Sin esto no podemos ser (como fueron los primeros cristianos)
verdaderos miembros de la familia de Dios;
no hemos llegado a la Nueva Jerusalén,
y por lo tanto no podemos ser conciudadanos con los santos.
Aunque llevamos el nombre de los primeros cristianos,
no estamos en la naturaleza de los primeros cristianos;
porque el primogénito no ha sido derribado para que un Espíritu
recto gobierne en nosotros y tenga dominio sobre nosotros.

Si las palabras contenidas en este libro le parecen extrañas al lector,
es porque el lector es extraño a la vida de los primeros cristianos.
Porque si Aquel que era la cabeza y líder de la iglesia
primitiva fuera nuestra cabeza y líder,
entonces tendríamos un eco en nosotros que respondería a lo que está escrito aquí;
y nuestros corazones dirían: "`Así es.`"

Y el camino para llegar a la vida justa que ellos experimentaron,
es andar en la misma luz,
negando y apartándonos de la cosa más pequeña que ella nos manifieste como mala.
Al inicio de nuestro viaje, el camino nos parecerá estrecho y difícil,
pero después de haber viajado por un tiempo, correremos en él con gran deleite.
Porque el reino de los cielos--o el gobierno de Cristo por Su Eterno Espíritu
en los corazones de Su pueblo--no consiste solamente en justicia;
la justicia que procede del Espíritu recto viene acompañada de paz y gozo.
Así como el hacer el mal trae consigo angustia y dolor, hacer el bien trae paz y gozo.
Todos los placeres de la maldad que el mundo entero puede ofrecer,
no se comparan con las alegrías de una vida justa.

Cuando los paganos, por la predicación del evangelio,
se volvieron de su oscuridad y llegaron a ser seguidores del Espíritu eterno,
haciendo morir de este modo la fuerza del pecado,
fueron llamados por el apóstol "`santos.`"
Este nombre era más apropiado que el de "`cristianos,`" porque el título
de santo es propio de todas las almas verdaderamente santificadas.

Así como someterse a la circuncisión externa les dio a muchos el nombre de judíos,
así también imitar el bautismo en agua de Juan les ha dado a muchos el nombre de cristianos;
pero nada puede dar a un judío o a un cristiano el nombre de santo,
sino un corazón hecho puro, fiel y justo, por medio de hacer morir el pecado,
lo cual es llamado en la Escritura "`el bautismo del Espíritu Santo,`"^
footnote:["`Él os bautizará en Espíritu Santo y fuego.
Su aventador está en su mano, y limpiará su era; y recogerá su trigo en el granero,
y quemará la paja en fuego que nunca se apagará.`"--Mateo 3:11-12]--porque
esto no es llevado a cabo por ningún medio externo,
sino al andar en el Espíritu Santo.
Hasta que esto sea obrado, aunque tengamos el nombre de cristianos,
de ninguna manera podremos manifestar una conducta celestial,
y entonces el nombre de nada aprovecha.

Porque nosotros, los que somos llamados cristianos,
tenemos en nosotros una semilla de pecado, como todos los demás,
y por no ser fieles desyerbadores que desarraiguen el mal tan pronto como aparece,
la iniquidad crece hasta tal punto que nada menos
que el poderoso Espíritu de Cristo puede derribarla.
Y de aquellos que siguen siendo extraños a la obra de este Espíritu ha salido un clamor:
"`¡No hay libertad del pecado en este lado del sepulcro!`"
Pero los colosenses, que fueron liberados de la potestad de las tinieblas,
conocieron cosas mejores; y nosotros experimentaríamos lo mismo,
si nos apartáramos de la iniquidad,
conociéramos a su Guía y anduviéramos en novedad de vida.

Pero así como nada desanimó tanto al campamento de Israel de subir a poseer la tierra
de Canaán como el informe que los diez espías dieron de los gigantes que moraban allí,
así también nada desalienta tanto a las almas despertadas que anhelan una vida de justicia
como el informe que los profesantes del cristianismo dan acerca de la fuerza del pecado,
y de cómo no puede ser vencido.
Quienes dan este informe nunca han probado el camino de la salvación de Dios.

Todos los espías hablaron bien de la tierra,
así como hoy toda clase de personas hablan bien de una vida sobria, justa y piadosa.
Todos alaban la humildad, mansedumbre, moderación, templanza, paciencia, pureza y,
sobre todo, la sencillez, rectitud, honestidad y justicia en los tratos,
aunque no practiquen tales cosas.
Y nada impide tanto una vida piadosa como esto:
que el espíritu maligno de este mundo permanece en lo más alto dentro de nosotros,
y pocos se esfuerzan (a la manera de Dios) por derribarlo.

Si el campamento de Israel hubiera nombrado un capitán y regresado a Egipto,
nunca habría podido someter a los cananeos en la tierra.
Y mientras nos permitamos vivir en pecado, nos será imposible someterlo;
porque estaremos fortaleciendo lo que debemos hacer morir.
La fuerza de los cananeos se fue debilitando por la guerra,
y lo mismo debe suceder con la fuerza del pecado;con esta diferencia:
que su guerra era externa y agresiva, y la nuestra debe ser interna y defensiva.
Cuando,
por la lámpara del Señor que brilla en nuestras almas vemos un pensamiento altivo,
un deseo de la carne, un impulso codicioso, o cualquier otra inclinación maligna,
si permanecemos en guardia y le negamos la entrada en nuestro corazón,
se retirará. Y después de muchos intentos, siendo aún resistido,
difícilmente lo intentará de nuevo, y sus movimientos serán más débiles.

Mientras el "`anatema`"^
footnote:[Josué 7:1, 11-15]
permaneció en el campamento, el enemigo prevaleció, e Israel retrocedió;
y así es hoy en día. Si cubrimos, si escondemos,
si justificamos lo que nuestros propios corazones condenan,
entonces el mal prevalece y el Espíritu se apaga.
Pero si nos acostumbramos al yugo de la cruz, entonces la fuerza del pecado,
día tras día, será debilitada,
y (como dijeron Josué y Caleb) "`con nosotros estará Jehová.`"^
footnote:[Números 14:9]
Su gracia estará en nuestros corazones, y Su temor delante de nuestros ojos.
La verdad, la equidad y la honestidad predominarán en el interior,
y entonces será tan fácil llevar una vida sobria, justa y piadosa,
como antes lo fue vivir una vida disoluta e impía. Y así,
todos nuestros miembros que alguna vez fueron siervos del pecado,
se volverán siervos de la justicia, como está escrito "`El mayor servirá al menor.`"^
footnote:[Génesis 25:23]
Porque aunque algo de pecado permanezca en nosotros--como algunos
cananeos quedaron en la buena tierra--no tendrá ningún poder,
como sucedió con ellos.

Pero si nos rebelamos contra el Señor uniéndonos a las inclinaciones
del pecado (como hacen muchos que son llamados cristianos,
como también los paganos en este día),
entonces esta guerra habrá terminado antes de haber empezado.
Aquella semilla que tenga el dominio no dejará de tenerlo, y como vivamos,
así moriremos--recibiendo la paga, no según nuestras _palabras,_
sino según nuestras __obras.__^
footnote:[Mateo 16:27; Juan 5:29; Romanos 2:6; 2 Corintios 5:10; Apocalipsis 2:23, 20:12]
Entonces, sabremos que el nombre de cristiano, sin la naturaleza cristiana,
no será de provecho al final; porque no es el que es vencido, sino el que vence,
quien no sufrirá daño de la segunda muerte.
