== Capítulo II. Consideraciones Basadas en el Discurso Anterior

El hombre fue creado (como muchos reconocen) para glorificar a Dios,
y para hacer Su voluntad en la tierra.
Y para que el hombre fuera capaz de servir a su Creador según Su voluntad,
Dios le dio una medida de Su buen Espíritu como Instructor;
de modo que había mucho de Dios en el hombre,
cuando fue creado originalmente--mucha humildad y mansedumbre, mucha verdad y fidelidad,
mucha sabiduría y entendimiento celestiales.

Este Espíritu eterno debía ser la cabeza y líder del hombre,
el guía e instructor del hombre en los caminos de justicia.
En este Espíritu el hombre debía fijar su ojo;
a este Espíritu el hombre debía inclinar su oído;
por medio de este Espíritu el hombre debía ser gobernado; y así, siguiendo a este guía,
líder e instructor,
el hombre habría sido capaz de gobernarse a sí mismo
y la creación sobre la cual fue hecho amo,
según la voluntad de Dios.

Si la humanidad viviera bajo el gobierno de este Espíritu eterno,
todos llevarían la imagen de Dios.
Todos serían piadosos, humildes, mansos, misericordiosos, pacientes, pacíficos,
íntegros y fieles; rectos en todos sus caminos, y justos en todas sus obras.
Pero al no mantenerse aferrado a este guía, el hombre desobedece el mandato de su Creador.
Y al rendirse a sí mismo como un sirviente de otro maestro,
entonces entra otro espíritu que es tan contrario
en naturaleza como la oscuridad es a la luz.
Y todos los que siguen a este otro líder, no sirven al Dios del cielo,
sino al dios de este mundo; porque cada hombre es esclavo de aquel a quien obedece.^
footnote:[Romanos 6:16]

Ahora nosotros, siendo descendientes de Adán en su estado caído, llevamos su imagen.^
footnote:[Génesis 5:3]
Dentro de nosotros tenemos tanto el bien como el mal,
una Semilla de gracia y una semilla de pecado.
Estas, en la Escritura, son llamadas luz y tinieblas, carne y espíritu,
el viejo hombre y el nuevo hombre,
de acuerdo con el crecimiento de las semillas dentro de
nosotros y el dominio que llegan a tener sobre nosotros.
Porque como hay una diferencia entre una semilla y una hierba, una planta y un árbol,
un niño y un hombre, así también hay diferencias en la gracia y en el pecado.
De acuerdo con su crecimiento en nosotros, sentimos su fuerza,
y los nombres dados en las Escrituras corresponden a dicho crecimiento.

Porque, aunque todos tenemos una semilla de pecado en nosotros, sin embargo,
no somos dominados por ella, ni estamos completamente esclavizados por ella,
tan pronto como nacemos.
Necesita tiempo para brotar y crecer en nosotros
antes de que llegue a tener dominio sobre nosotros.
Asimismo, debo decir lo mismo de la Semilla de gracia,
porque también su naturaleza es crecer;
de lo contrario el reino de los cielos (o gobierno
de Cristo en los corazones de Su pueblo),
no se hubiera comparado con una semilla de mostaza, la cual,
a pesar de ser pequeña cuando es sembrada,
luego brota y va creciendo hasta llegar a ser muy grande.

En verdad hay muchos en el mundo que son notoriamente impíos,
y quienes se mostrarían mucho más impíos si no estuvieran limitados por una ley externa.
Estos no eran así cuando nacieron;
es el crecimiento del pecado y el incremento de su dominio sobre los hombres,
que los hace notoriamente impíos. Porque la semilla de pecado,
cuando llega a su crecimiento pleno en cualquiera de los hijos e hijas de los hombres,
los convierte en su misma naturaleza,
por lo que llegan a ser habitualmente activos en la maldad.

Este fue el objetivo del diablo en la caída de Adán,
pero como su objetivo no fue entonces llevado a cabo completamente,
ha seguido a los hijos e hijas de los hombres en
todas las eras del mundo (y lo hace en este día),
poniendo sus inclinaciones malignas en sus mentes junto con varias tentaciones,
presentando apariencias falsas,
y pintando cosas prohibidas con un hermoso brillo que es más atractivo al hombre caído,
que los caminos de justicia.
Todas sus inclinaciones malignas, tentaciones, carnadas, trampas,
anzuelos y apariencias falsas,
son para llevar a cabo su plan original--y siendo
atrapados y alejados de Dios por estas cosas,
nos olvidemos de nuestro Dios y hagamos que Él nos quite Su Espíritu Santo.
Hasta entonces, el dios de este mundo no puede llamar suyo a ningún hombre;
podemos ser cautivos por él, pero él no tiene completo dominio sobre nosotros.

En nuestra presente era, hablar de la luz interna de Dios, de la ley en el corazón,
del Espíritu en el interior, de Cristo en nosotros, etc.,
es motivo de burla para algunos, y es poco considerado por muchos.
Pero lo sepan o no, debo decirles,
que ellos se burlan y desprecian el tesoro más grande
que jamás ha sido dado al alma del hombre.
Ellos menosprecian el talento celestial que Dios
le ha dado a cada hombre para que lo incremente,
a fin de que (siendo incrementado),
el hombre se levante de su caída y regrese a su tierra natal,
para vivir bajo el gobierno del Espíritu eterno.
Quienquiera que esté sin el Espíritu y luz interna, está sin Dios en el mundo.
Si nos quitaran este tesoro, no tendríamos nada en nosotros que fuera bueno;
nos quedaríamos absolutamente sin gracia.

Leemos de Jacob y Esaú,
quienes eran figuras vivientes de estas dos semillas en el hombre,
cómo lucharon mientras estaban en el vientre de Rebeca.
Y así como hubo una lucha entre la simiente de dos naciones en el vientre de Rebeca,
así también hay una lucha entre la simiente de dos reinos en cada hombre,
en cuanto a cuál de ellos se levantará a gobernar
y tener todo el dominio sobre nosotros.

Cuando nacemos en el mundo, todos somos inocentes.
Aunque tenemos una semilla de pecado en nosotros,
no somos realmente pecadores hasta que cedemos ante
las inclinaciones pecaminosas que proceden de ella.
El diablo lo sabe (aunque muchos opinan diferente), por lo tanto,
con el fin de que la semilla que él ha sembrado brote y crezca,
y que un espíritu malo llegue a gobernar en nosotros,
él comienza su lucha a temprana edad,
antes de que podamos distinguir la mano izquierda de la derecha.

Ahora, cuando la maldad no es reprimida por cuidadosos padres o tutores,
rápidamente se convierte en la cabeza, y tales pueden decir (como muchos lo hacen hoy):
"`No hay nada bueno en nosotros.`"
Porque, por medio del rápido crecimiento de lo que es malo,
estos nunca tienen conocimiento de lo que es bueno,
excepto por las reprensiones internas,
que pocos están dispuestos a reconocer que provienen de Dios.
Porque tal como las malas hierbas en un jardín ahogan y reprimen las buenas plantas,
así la maldad reprime la virtud,
y hace que la creación de Dios sea tan ajena a su Creador que,
a pesar de que "`en él viven, se mueven, y existen,`"^
footnote:[Hechos 17:28]
muchos viven sin ningún sentido o percepción de Su presencia.

Y de la misma manera que todas las inclinaciones perversas que nos llevan al pecado,
todas las carnadas, trampas y anzuelos,
con los que nos encontramos en el transcurso de nuestras vidas,
son las maneras por las que la semilla del mal pelea y se esfuerza en nosotros;
así mismo todos las llamadas que encontramos en nosotros mismos a la justicia,
honestidad, verdad y fidelidad, con todas las reprobaciones,
reprensiones y convicciones que sentimos internamente,
son las maneras por las que la semilla del bien pelea y se esfuerza en nosotros.
Y si estas cosas son recibidas, obedecidas, seguidas y vividas,
ellas detienen el crecimiento del mal; de modo que,
aunque tenemos una raíz de pecado en nosotros, ésta permanece sin poder;
no se levanta ni llega a reinar sobre nosotros.

Por esta razón,
los padres y tutores deberían preocuparse mucho por suprimir el pecado,
para permitir así el crecimiento de la gracia.
Porque como el maligno se aprovecha de nuestra niñez para hacernos
cometer maldad antes de que conozcamos aquello que es bueno,
los padres y tutores (como fieles "`desmalezadores`") deberían vigilar, suprimir,
detener y usar todos sus esfuerzos para desarraigar la maldad en cuanto aparezca,
hasta que la gracia crezca,
y un Espíritu recto llegue a reinar en ellos y a tener dominio sobre ellos.

Pero este es nuestro estado actual: así como Esaú, por sus luchas dentro de Rebeca,
llegó a ser el primogénito en la antigüedad, de la misma manera, la iniquidad,
a través del surgimiento de la serpiente sutil a temprana edad,
sigue siendo el primogénito.
Y a pesar de que la mayoría de los padres en el mundo
Cristiano a veces se preocupan por sacar la maleza,
sin embargo es muy poca la maleza que realmente arrancan, y muchos no arrancan nada.
Ante esta gran negligencia, la mayoría de los niños llegan a ser indomables, tercos,
obstinados, desobedientes a los padres, y muy impíos en sus vidas.
Pero el fundamento de toda impiedad es el crecimiento de esa semilla que
el maligno sembró. Y ¿cómo se puede derribar la maldad cuando ya ha brotado?
No por padres, tutores o predicadores; sino, así como Jacob suplantó a Esaú,
así la gracia tiene que suplantar al pecado.
Porque vemos que, a pesar de toda la predicación que existe,
todavía hay mucho más orgullo y arrogancia que humildad y mansedumbre,
más tratos y negocios engañosos y prácticas malvadas que abnegación;
más deseo por el mundo y sus vanidades que por el reino del cielo y su justicia.
Y siempre va a ser así mientras que el primogénito predomine.

Y si queremos que el primogénito sea suplantado;
si queremos que se vuelva impotente aquello que se esfuerza por privarnos de vida,
luz y gracia;
si queremos que sea reprimido aquello que continuamente
busca hacernos siervos del pecado y esclavos de Satanás;
si queremos experimentar la muerte de aquello que nos hace
incapaces de glorificar a Dios con nuestras vidas;
si queremos ser librados (como lo fueron los primeros cristianos) de la
potestad de las tinieblas y trasladados al reino del amado Hijo de Dios,
para vivir bajo el gobierno de Su Espíritu eterno (que fue el primer estado
del hombre)--entonces consideremos cómo surgió eso que ahora nos estorba,
y por qué medios se puede derribar.

He dicho antes y ahora digo otra vez, que no es la mera presencia de la semilla del mal,
sino el crecimiento y reino de ella,
lo que hace que los hijos e hijas de los hombres sean orgullosos, arrogantes, altivos,
envidiosos, crueles, despiadados, fraudulentos e impíos; oscureciendo sus entendimientos,
y haciéndolos ajenos al don de Dios en sí mismos.
Y el crecimiento de esta semilla del mal,
se debe a que a menudo cedemos a las inclinaciones perversas que proceden de ella.
Esto lo sabe la sutil serpiente,
y nosotros podemos saberlo también por las múltiples
tentaciones que sentimos hacia el mal,
especialmente donde nuestro enemigo ha encontrado que son efectivas.

¿Quién ha cedido ante alguna inclinación perversa,
cometiendo pecado y disfrutando de ello,
y luego no ha sido tentado nuevamente a hacer lo mismo?
¿O quién no sabe, que entre más cedamos a cualquier tentación, más fuertes se vuelven,
y por ende más difíciles de negar?
Y cada vez que cedemos, el pecado se levanta, y llega a tener más poder sobre nosotros.

Por lo tanto, si ceder ante las inclinaciones perversas,
hace que el espíritu maligno se levante y llegue a tener poder en nosotros,
entonces negar las inclinaciones perversas,
hace que dicho espíritu sea suplantado y pierda su poder en nosotros.

Quien desee ser un seguidor de Cristo, tiene que aprender primero a negarse a sí mismo.
Debemos apartarnos de cualquier cosa que la luz eterna
en nuestros corazones nos muestre ser egoísta,
sin importar cuánto parezca ser una desventaja para nosotros;
y al negarnos a nosotros mismos de este modo,
negaremos abundantemente al autor de todas las inclinaciones perversas.

El orgullo, el placer y la ambición personal, son las carnadas que han atrapado a muchos.
Estas cosas, junto con muchas otras, deben ser negadas y rechazadas,
si queremos ser seguidores de Cristo en una vida de justicia.
Y al ser rechazadas continuamente, encontraremos que la raíz de la iniquidad se seca,
y la gracia crece; los deseos pecaminosos disminuyen, y los deseos celestiales aumentan;
la semilla más pequeña se convierte en la mayor de las hortalizas;
y la masa de harina llega a ser una en naturaleza con la levadura celestial.

Sin embargo, esta negación debe ser mientras el dragón se encuentre en el cascarón,
es decir, mientras el pecado sea todavía una inclinación,
antes de que se convierta en una acción;
porque las inclinaciones pecaminosas se pueden rehusar,
pero las acciones pecaminosas no se pueden deshacer ¿Y qué nos
puede mostrar el surgimiento de las inclinaciones malignas?
Los predicadores no pueden; los libros no pueden;
nada que esté fuera puede efectivamente revelarnos lo que está dentro.
Debe ser una luz interna; debe ser la lámpara del Señor,
el Espíritu eterno que en el principio se le dio al hombre como instructor.

En las Escrituras leemos acerca de hombres buenos, hombres fieles, hombres abnegados,
incluso cuando no había predicadores o libros;
y ¿quién era su maestro sino el Espíritu eterno?
¿Qué guía tenían sino la luz de justicia en sus propios corazones?
Y si nuestros predicadores de hoy en día se preocuparan
por volver los corazones de las personas a este Guía interno,^
footnote:[Ver Hechos 26:18 y Hechos 20:32]
y convertirlos en fieles seguidores de Él, tendríamos más hombres buenos,
más hombres fieles, y más hombres abnegados, que los que se pueden encontrar ahora.

Ni los hombres ni los ángeles pueden dar mejores consejos
a un pueblo que se ha vuelto hacia esta luz interna,
que el que Pablo dio a los gálatas cuando los exhortó a "`Andar en el Espíritu`";
porque si no somos guiados por un Espíritu recto, nunca podremos llevar una vida justa.

Pero, así como la semilla de pecado crece y se fortalece en nosotros
cuando nos entregamos a las inclinaciones malignas,
así la Semilla de gracia crece y se fortalece en
nosotros al negar las inclinaciones malignas.
Al despojarnos del viejo hombre nos vestimos del nuevo,
y el nuevo hombre es el que nos hace nuevas criaturas,
y el que engendra una vida nueva y celestial.

Si no aprendemos a negar las inclinaciones malignas,
y a vivir en el continuo ejercicio de esto,
entonces (aunque escuchemos todos los días de nuestras vidas a los predicadores)
no seremos más que la puerta que gira sobre sus quicios,
o como Israel en el desierto, moviéndonos a menudo de un lado hacia otro,
pero quedando cortos de una vida justa,
de la misma manera que la primera generación que salió de
Egipto quedó corta de la Tierra Prometida.

No podemos permanecer en el camino de justicia,
hasta que Su luz brille con tal claridad que podamos ver el levantamiento
de todas las inclinaciones malignas desde cierta distancia.
Porque cuando la gracia llegue a ser lo más alto en nosotros,
la raíz de la iniquidad será lo más bajo.
Cuando una llegue a permanecer ante nuestros rostros, la otra quedará a nuestras espaldas.
Porque ¿de dónde viene el orgullo, la altivez, la contienda y la rencilla,
el fraude y el engaño, la opresión y la crueldad, sino del autor de toda maldad?
Pero cuando la carne con sus pasiones es crucificada, tales cosas no se encuentran.
Y sin importar qué religión profesemos, mientras vivamos en la práctica de cualquier mal,
mantendremos vivo lo que debería ser asesinado.

Cuando un espíritu maligno predomina, los hombres no conocen ningún límite; sus oídos,
ojos, lenguas, manos y pies, están en libertad.
Ellos sienten libertad de escuchar malas palabras, contemplar la vanidad,
de hablar orgullosa, precipitada, indiscreta y engañosamente, de hacer violencia,
aceptar sobornos, e ir adonde sea que deseen.
Pero donde gobierna un Espíritu recto, cada miembro del cuerpo queda bajo Su gobierno.
El oído se aparta de las fábulas y el ojo deja de contemplar la vanidad.
Ellos no pueden (como muchos lo hacen), cubrirse, disfrazarse y mentir,
para lograr sus propios fines.
No permiten que salgan de sus bocas conversaciones vanas,
y sus manos son guardadas de hacer el mal.
No pueden caminar por los caminos de impureza, sino que son amantes de la justicia,
y aborrecedores de la maldad, tanto en ellos mismos como en otros.
Y todos podemos llegar a este estado,
al negar todas esas inclinaciones que la luz de justicia
manifiesta como malignas en nuestros corazones.

Ahora, este es mi consejo para todos los profesantes del cristianismo:
que en lugar de contender por prácticas de la piedad,
presten atención a ese don en sí mismos que conduce a la piedad;
en lugar de escudriñar las Escrituras por una forma o práctica correcta,
busquen vivir bajo el gobierno de un Espíritu correcto;
porque entonces serán librados de la potestad de las tinieblas,
y regresarán a Sion (la ciudad de Dios), y a la Nueva Jerusalén,
donde Dios es conocido y verdaderamente adorado.

Hay una cosa más que quisiera que el lector considerara, y es la siguiente:
Aunque dos espíritus operan en cada hombre que viene al mundo, aun así,
el hombre no puede tener dos señores; por lo tanto,
cualquiera de estos dos espíritus que tenga el dominio será señor sobre él.

El derecho de gobernar en todos los hombres le pertenece al Espíritu
eterno que estaba con el Padre antes de la fundación del mundo.
Esto, en las Escrituras, se llama el Espíritu de Cristo;
porque en Jesús (el segundo Adán) no habitaba ningún otro espíritu.
En Cristo no operaban dos espíritus,
como sucede con la descendencia del Adán caído. No tenía en Sí mismo luz y oscuridad,
bien y mal, una semilla de gracia y una semilla de pecado;
sino como dicen las Escrituras, Él estaba "`lleno de gracia y de verdad.`"^
footnote:[Juan 1:14]
En Él estaba la vida (la vida que perdió el primer Adán) como una fuente de justicia;
y Él retuvo esta vida, y por lo tanto mantuvo fuera el espíritu maligno,
que es el autor de toda maldad,
aunque Sus tentaciones excedieron con creces a las de Eva.
Y a pesar de que Él vivió muchos años en la tierra, y se encontró con muchas tentaciones,
aun así, en todo el transcurso de Su vida,
Él cumplió toda justicia y llevó a cabo la voluntad de Dios en la tierra.

Ahora, la Semilla de gracia en cada hombre,
es una en naturaleza con la plenitud que moraba en Él. Y
a medida que esta Semilla brote en cualquiera de nosotros,
y crezca en fuerza y estatura, nos hará conforme a Su imagen.
Así, cuanta más gracia tengamos, más humildes, mansos y amorosos seremos.
Entre más luz tengamos,
mayores descubrimientos hará de lo que está mal en nosotros
y en los demás. Entre más verdad habite en nosotros,
menos maldad e impureza será manifestada por nosotros.

Y a medida que andemos en la luz, creceremos en gracia,
y añadiremos "`a vuestra fe virtud; conocimiento, dominio propio, paciencia, piedad,
afecto fraternal, y amor;`"^
footnote:[2 Pedro 1:5-7]
por lo cual, como dijo Pedro,
"`será otorgada amplia y generosa entrada en el reino
eterno de nuestro Señor y Salvador Jesucristo.`"^
footnote:[2 Pedro 1:11]
Un Espíritu recto será exaltado en nosotros,
y tendrá el único gobierno y dominio sobre nosotros;
y bajo el gobierno de un Espíritu recto,
llevaremos fruto aceptable ante los ojos de Dios.

Ahora, siendo el príncipe de las tinieblas enemigo de toda justicia,
hace todo lo posible para cegar los ojos de nuestro entendimiento
y mantenernos ajenos a esta Semilla justa (que es la fuente de
toda gracia y virtud interna) para alejarnos de Dios y de la piedad.
De modo que, así como aquellos que caminan en la luz del Señor,
añaden virtud a la virtud hasta ser llenos de Su justicia,
así también aquellos que siguen las indicaciones de un espíritu maligno,
añaden vicio al vicio hasta ser llenos de iniquidad.
Estos también tienen un solo señor,
porque el príncipe de la potestad de las tinieblas tiene todo el dominio sobre ellos.
Y en las Escrituras estos dos estados son llamados _vida_ y _muerte._

Creo que se puede decir que cada hombre, cuando viene al mundo,
tiene la vida y salvación puesta delante de él,
y la muerte y la destrucción detrás de él,
y ambas están a cierta distancia de él. También tiene un Espíritu
bueno para conducirlo por el camino de la vida y la salvación,
y un espíritu maligno que busca guiarlo en los caminos de la muerte y la destrucción;
y aunque los dos están en él, aun así, la mayoría de los hombres son ajenos a ambos.
Ahora,
la predicación del evangelio tenía como objetivo (y todavía debe tenerlo) abrir esos
ojos ciegos para que vieran las operaciones y directrices de estos dos espíritus internos,
para que los hombres pudieran apartarse del mal y
convertirse en seguidores de lo que era bueno,
y para que Aquel que tenía derecho llegara a tener el dominio en ellos y sobre ellos.

Y estoy seguro, que aunque muchos ignoran estas cosas, aun así hay muchos que han visto,
sentido y saboreado algo del Espíritu eterno de Jesús. Estos tienen
el conocimiento de algo en sí mismos que clama por verdad y justicia;
y si se aferraran a esto, estarían siguiendo a un Guía recto,
y la Semilla de gracia crecería, la verdad y la fidelidad se incrementarían,
el conocimiento, la templanza, la paciencia, el afecto fraternal y el amor crecerían;
y encontrarían en sí mismos que es otorgada una amplia
y generosa entrada al reino de Cristo.

Pero mientras el espíritu maligno permanece sin ser crucificado,
el yo se interpone en nuestro camino, y en aras de lograr sus fines egoístas,
no se mantienen las balanzas justas, no se lleva a cabo la justicia,
no se establece la equidad, no se cumplen las promesas,
no se manejan fielmente los compromisos,
y no se abandonan las costumbres y modas de este mundo pecaminoso.
Esto entorpece el crecimiento de la Semilla justa;
porque como era imposible derribar a los cananeos mientras que el "`anatema`"^
footnote:[Ver Josué 7]
estuviera en el campamento,
así también es imposible derribar la fuerza del pecado
mientras consideremos más al yo que a nuestro Salvador.
La luz es lo que manifiesta al yo,^
footnote:[Efesios 5:13]
y por medio de ella, podemos ver hacia dónde conduce cada inclinación maligna;
de modo que, al andar en la luz, andamos en el camino de la salvación de Dios.

Sin embargo,
algunos pueden decir de esta vida eterna (como los hombres malvados y perversos
dijeron con respecto a Saúl el elegido del Señor)--"`¿Cómo nos ha de salvar éste?`"^
footnote:[1 Samuel 10:27]
'`¿Qué ventaja puede haber en prestar atención a esta luz?
¡Encontramos en nosotros mismos reprensiones por el pecado,
pero no encontramos nada en nosotros mismos que nos salve del pecado!`'

A tales como estos, les digo lo siguiente: Cristo fue dado por luz^
footnote:[Isaías 42:6, 49:6]
y por jefe^
footnote:[Isaías 55:4]
de los gentiles.
Mientras nos encontremos en la naturaleza de los gentiles,
mientras andemos conforme a la carne; mientras sigamos las inclinaciones malignas,
estaremos apartados de Dios,
alejados de la ciudadanía de Israel y ajenos al nuevo
pacto que Dios hizo con la casa de Jacob.
En este estado, no podemos conocer a Cristo, el Salvador del mundo,
de ninguna otra manera que como Aquel que nos reprende.
Pero estas reprensiones que nos instruyen son el "`camino de vida,`"^
footnote:[Proverbios 6:23]
sí, el camino hacia esa vida que el primer Adán perdió por medio de la transgresión.

Porque,
si debido a estas reprensiones nos apartamos de las cosas
por las que somos reprendidos--ya sean conversaciones ociosas,
un estilo de vida desenfrenado, el orgullo, la pasión,
o cualquier otro vicio al que conduce el espíritu
maligno de este mundo--y seguimos la justicia,
entonces las amonestaciones cesarán, y nuestro reprobador se convertirá en nuestro líder.
Entonces, lo que estaba a nuestras espaldas, estará delante de nuestros rostros;
y lo que deseaba dirigirnos, ahora buscará perseguirnos (como Faraón persiguió a Israel),
para traernos nuevamente de vuelta a nuestra pasada manera de vivir,
y _entonces_ experimentaremos a Cristo como nuestro Salvador.
Porque tal como los que siguieron a Saúl al inicio de su reinado,
vieron cómo los salvó de sus enemigos externos;
así todos los que llegan a ser seguidores del Espíritu eterno de Jesús,
ven cómo Él los salva de sus enemigos espirituales.

Cuando seguimos las inclinaciones pecaminosas, seguimos al guía equivocado,
y en este camino, vamos a sentir que el poder del pecado prevalece,
pero nunca experimentaremos el poder de la gracia que restringe y transforma.
Está escrito que Cristo les da poder a todos los que Lo reciben;^
footnote:[Juan 1:12]
pero ninguno Lo recibe realmente,
sino los que se apartan del pecado cuando son reprendidos por Él,
y se encomiendan a Él como su Salvador.
Sólo estos creen verdaderamente en Su nombre.

Reconozco que el resplandor de la luz interna (que es la primera manifestación de Cristo
a los hijos e hijas de los hombres) parece ser pequeño y sin poder al principio;
y del mismo modo sucede con las primeras inclinaciones al pecado.
Pero si sigue tales inclinaciones pecaminosas hasta donde lo conduzcan,
las encontrará lo suficientemente poderosas.
¿No es cierto que muchos en este día, incluso entre los que se llaman cristianos,
permanecen cautivos bajo el poder del pecado?
De hecho,
creo que sería más fácil para un esclavo atado con cadenas de hierro romper sus ataduras,
levantarse y regresar a su país natal,
que para muchos de estos cristianos dejar de pecar, levantarse de su caída,
y vivir una vida sobria, justa y piadosa.

Ahora,
si la semilla de pecado tiene tal poder sobre nosotros cuando seguimos sus inclinaciones,
¿por qué la Semilla de gracia no puede tener tal poder sobre nosotros,
si regresamos a ella y nos convertimos en sus seguidores?
Ciertamente Juan, quien pasó de muerte a vida,
y vio con sus ojos las cosas como eran en el principio,
sintió tal poder en sí mismo cuando escribió: "`Todo aquel que es nacido de Dios,
no practica el pecado, porque la simiente de Dios permanece en él; y no puede pecar.`"^
footnote:[1 Juan 3:9]
Y al día de hoy se pueden encontrar muchos testigos
vivos que pueden decir desde una experiencia real,
que en la medida que esta Semilla justa se ha levantado y ha llegado a tener dominio,
ha sido tan poderosa y restrictiva que no les ha
sido posible ser injustos en sus tratos y negocios,
ni infieles en sus promesas; no pueden decir una mentira,
aunque fuese muy ventajoso para ellos; no pueden ser excesivos,
malgastando el bien de la creación que Dios les ha
dado para su sustento al comer y beber en exceso;
no pueden oprimir al pobre, a la viuda, ni al huérfano,
ni tomar con violencia aquello que no tienen derecho a tener.
La pequeña Semilla en ellos se ha convertido en la más alta de las plantas,
y tiene tanto poder sobre ellos como el pecado tiene
sobre todos los que moran en él. Estos,
como los colosenses, son librados de la potestad de las tinieblas.
Estos, como los filipenses, tienen su ciudadanía en los cielos.
Estos glorifican a Dios en sus vidas y, por lo tanto,
cumplen el propósito por el que fueron creados.

Una abundancia de predicación ha hecho que muchos hablen de Cristo,
pero es la gracia en el corazón, y la verdad en lo íntimo,
la que hace que los hombres caminen como Cristo.
Y no hay otra manera de alcanzar la plenitud de este tesoro celestial,
sino negando todas las inclinaciones que la luz eterna de justicia
manifieste como injustas y deshonestas en nuestro interior.
Porque al negar lo malo, estamos escogiendo lo bueno;
y así como el crecimiento del pecado viene de abrazar lo que es malo,
así mismo el crecimiento de la gracia viene de abrazar lo que es bueno.

La conformidad con las formas externas de adoración (siendo más
atractivas para las personas que el camino angosto y estrecho de
la cruz) ha adquirido en nuestra presente era el nombre de religión,
Cristianismo y piedad verdadera.
Pero la conformidad que el Dios viviente requiere es,
que seamos conforme a la imagen de Cristo en todos los aspectos
de nuestras vidas--ser santos como Él es santo.
Sin esto,
no podemos ser (como fueron los primeros Cristianos)
verdaderos miembros de la familia de Dios;
no hemos llegado a la Nueva Jerusalén,
y por lo tanto no podemos ser conciudadanos con los santos.
Aunque llevamos el nombre de los primeros cristianos,
no nos encontramos en la naturaleza de los primeros cristianos;
porque el primogénito no ha sido derribado para que un Espíritu
recto gobierne en nosotros y tenga dominio sobre nosotros.

Si el contenido de este libro le parece ajeno al lector,
es porque el lector es ajeno a la vida de los primeros Cristianos.
Porque si Aquel que fue la cabeza y líder de la Iglesia
primitiva se hubiera vuelto nuestra cabeza y líder,
entonces tendríamos un eco en nosotros mismos que
correspondería a lo que está escrito aquí;
y nuestros corazones dirían: "`Así es.`"

Y la manera de obtener la vida justa que ellos experimentaron,
es caminar en la misma luz,
rechazando y apartándose incluso de la cosa más pequeña que la luz manifieste como mala.
Al inicio de nuestro viaje, el camino nos parecerá estrecho y difícil,
pero después de haber viajado por un tiempo, correremos en él con gran deleite.
Porque el reino de los cielos (o gobierno de Cristo por medio de Su Eterno
Espíritu en los corazones de Su pueblo) no consiste solamente en justicia;
la justicia que procede de un espíritu recto está acompañada de paz y gozo.
Así como la angustia y el dolor acompañan al que hace lo malo,
así la paz y el gozo acompañan al que hace lo bueno.
Todos los placeres de la maldad que el mundo entero puede ofrecer,
no se comparan con las alegrías de una vida justa.

Cuando los paganos, por medio de la predicación del evangelio,
se volvieron de su oscuridad y llegaron a ser seguidores del Espíritu eterno,
haciendo morir de este modo la fuerza del pecado,
fueron llamados por el apóstol "`Santos.`"
Este nombre era más apropiado que el de "`Cristianos,`" porque el título de santo
es característico de todas las almas verdaderamente santificadas.

De la misma manera que someterse a la circuncisión
externa les dio a muchos el nombre de Judíos,
así también imitar el bautismo en agua de Juan,
les ha dado a muchos el nombre de cristianos;
pero nada puede darle a un judío o a un cristiano el nombre de santo,
sino un corazón hecho puro, fiel y justo, por medio de hacer morir el pecado,
lo cual es llamado en la Escritura "`el bautismo del Espíritu Santo`"^
footnote:["`Él os bautizará en Espíritu Santo y fuego.
Su aventador está en su mano, y limpiará su era; y recogerá su trigo en el granero,
y quemará la paja en fuego que nunca se apagará.`" --Mateo 3:11-12]--porque
esto no es llevado a cabo por ningún medio externo,
sino al andar en el Espíritu Santo.
Hasta que esto se realice, aunque tengamos el nombre de Cristianos,
de ninguna manera podremos manifestar una conducta celestial,
y entonces el nombre de nada aprovecha.

Porque nosotros, que somos llamados Cristianos,
tenemos en nosotros mismos una semilla de pecado, como todos los demás,
y por falta de ser fieles "`desmalezadores`" que
desarraiguen el mal tan pronto como aparece,
la iniquidad crece tan alta que nada menos que el
poderoso Espíritu de Cristo puede derribarla.
Y de aquellos que siguen siendo ajenos a la obra de este Espíritu, ha surgido un clamor,
que "`¡no hay libertad del pecado en este lado del sepulcro!`"
Pero los colosenses, que fueron librados de la potestad de las tinieblas,
experimentaron mejores cosas; y nosotros experimentaríamos lo mismo,
si nos apartáramos de la iniquidad, y nos familiarizáramos con Su Guía,
y anduviéramos en novedad de vida.

Pero, así como nada desanimó más al campamento de Israel de subir a poseer la tierra de Canaán,
que el informe que los diez espías dieron de los gigantes que moraban allí,
así también nada desalienta más a las almas despiertas de desear una vida de justicia,
que el informe que los profesantes del cristianismo
dan concerniente a la fuerza del pecado,
y cómo no puede ser vencido.
Los que dan este informe nunca han probado el camino de la salvación de Dios.

Todos los espías hablaron bien de la tierra,
como también todas las personas hoy en día hablan bien de una vida sobria,
justa y piadosa.
Todos están dispuestos a encomendar la humildad, mansedumbre, moderación, templanza,
paciencia, pureza, y, sobre todo, los tratos y negocios hechos con franqueza, rectitud,
honestidad y justicia, a pesar de que ellos no practiquen tales cosas.
Y nada detiene una vida piadosa sino esto:
que el espíritu maligno de este mundo sigue predominando dentro de nosotros,
y pocos se esfuerzan (a la manera de Dios) por derribarlo.

Si el campamento de Israel hubiera nombrado un capitán y hubiera regresado a Egipto,
nunca habría dominado a los cananeos en la tierra.
Y mientras nosotros consideremos que es permitido vivir en pecado,
será imposible dominarlo; porque fortaleceremos lo que debemos hacer morir.
La fuerza de los cananeos se iba debilitando por la guerra,
y lo mismo debe suceder con la fuerza del pecado--con esta diferencia:
su guerra era externa y agresiva, y la nuestra debe ser interna y defensiva.
Cuando,
por medio de la lámpara del Señor que brilla en nuestras
almas vemos un pensamiento ambicioso,
un deseo de la carne, un impulso codicioso, o cualquier otra inclinación maligna,
si permanecemos en guardia y negamos su entrada en nuestro corazón,
huirá. Y después de muchos intentos, siendo aún resistido,
rara vez lo intentará de nuevo, y las inclinaciones serán más débiles.

Cuando el "`anatema`"^
footnote:[Josué 7:1, 11-15]
estaba en el campamento, el enemigo prevaleció, e Israel se retiró;
y así es hoy en día. Si cubrimos, si escondemos,
si justificamos lo que nuestros propios corazones condenan,
entonces el mal prevalece y el Espíritu se apaga.
Pero si nos acostumbramos al yugo de la cruz, entonces la fuerza del pecado,
día tras día, será debilitada,
y (como dijeron Josué y Caleb) "`con nosotros estará Jehová.`"^
footnote:[Números 14:9]
Su gracia estará en nuestros corazones, y Su temor estará frente a nuestros ojos.
La verdad, la equidad y la honestidad predominarán internamente,
y entonces será tan fácil llevar una vida sobria, justa y piadosa,
como lo fue vivir una vida descuidada e impía. Porque,
aunque pueda quedar algo de pecado en nosotros, no tendrá ningún poder,
de la misma manera que unos pocos cananeos quedaron en la buena tierra,
pero sin poder para hacer nada.
Y así, todos nuestros miembros que alguna vez fueron siervos del pecado,
se volverán siervos de la justicia, como está escrito "`El mayor servirá al menor.`"^
footnote:[Génesis 25:23]

Pero si nos rebelamos en contra del Señor al unirnos con las inclinaciones
del pecado (como hacen muchos que son llamados cristianos,
como también los paganos en este día),
entonces esta guerra terminará antes de que haya empezado.
Esa semilla que tiene el dominio en nosotros no dejará de tenerlo,
y en la misma condición en la que hayamos vivido, así moriremos--recibiendo la paga,
no según nuestras _palabras,_ sino según nuestras __obras.__^
footnote:[Mateo 16:27; Juan 5:29; Romanos 2:6; 2 Corintios 5:10; Apocalipsis 2:23, 20:12]
Entonces, sabremos que el nombre de Cristiano, sin una naturaleza de cristiano,
no aprovecha de nada al final; porque no es el que es vencido, sino el que vence,
quien no sufrirá daño de la segunda muerte.
