== Capítulo III. La Gracia que Trae Salvación

La mayoría de los hombres ha aprendido a hablar bien de la gracia,
pero pocos pueden decir qué es o dónde se puede encontrar.
Muchos la reconocerán como el don de Dios; sin embargo,
dicen haberla recibido de los labios de los hombres.
Muchos están persuadidos de que toda maldad brota de la falta de gracia,
pero por la ignorancia desatienden sus apariciones dentro de sí mismos.
Muchos están convencidos de que, si la gracia fuera su líder,
sería suficiente para preservarlos de grandes pecados,
pero no pueden creer que sea suficiente para salvarlos de todo pecado.
Todo lo cual muestra claramente que su hablar bien de la gracia es de oídas,
y no por experiencia.

En el siguiente pequeño estudio muestro: 1) qué es la gracia,
2) dónde se puede encontrar, 3) cómo llega a ser líder del hombre,
4) cómo es aquello que salva del pecado, y así obra la verdadera salvación del hombre.
Porque cualquiera que sea salvo del pecado aquí,
ciertamente será salvo de la muerte y de la condenación en lo por venir;
y que muchos puedan llegar a ser testigos de esta salvación, es mi más ardiente deseo.

Pablo, apóstol de Jesucristo, escribiendo a Tito, el primer obispo de Creta, dijo:
"`La gracia de Dios que trae salvación se ha manifestado a todos los hombres,
enseñándonos que, renunciando a la impiedad y a las concupiscencias mundanas,
vivamos en este presente mundo sobria, justa y piadosamente.`"^
footnote:[Tito 2:11 RVG]
A partir de estas palabras tan importantes surgen las siguientes preguntas:

[.discourse-part]
_Pregunta 1._ ¿Qué es la gracia de Dios?

[.discourse-part]
Respuesta: La gracia de Dios, que trae salvación,
es nada menos que una inspiración divina,
un don de Dios para los hijos e hijas de los hombres, un adversario del diablo,
un destructor del pecado y aquello que salva a la humanidad de él.

El don de gracia, bajo la administración del evangelio,
es el cumplimiento de aquel pacto que Dios, por medio de la boca de Su profeta Jeremías,
prometió hacer con la casa de Jacob, que decía: "`Daré mi ley en su mente,
y la escribiré en su corazón;`"^
footnote:[Jeremías 31:33]
para que Su pueblo tuviera una ley de justicia dentro
de ellos mismos con la cual guiar sus pasos.

Así como los príncipes de la tierra rigen y gobiernan a su pueblo mediante una ley externa,
así el Señor determinó regir y gobernar a Su pueblo por medio de una ley interna.
No tendrían necesidad de pasar las páginas de un
libro para saber cómo andar por caminos rectos,
como hizo la simiente de Abraham bajo el primer pacto; sino que,
al mirar la "`ley del Espíritu de vida en Cristo Jesús`"^
footnote:[Romanos 8:2]
en sus propios corazones, sabrían qué está bien y qué está mal,
qué deberían hacer y qué no deberían hacer, qué es justo y qué es injusto,
qué le agrada a Dios y qué no.
Porque esta "`ley es luz`"^
footnote:[Proverbios 6:23]
que alumbra las almas de los hombres,
así como el sol en el firmamento alumbra nuestras casas,
mostrando lo que está limpio y lo que está sucio,
lo que puede permanecer y lo que necesita ser barrido.

Porque así como Dios creó al hombre en el principio humilde, dócil, manso,
misericordioso, puro, amable, justo y fiel, así desea que todos los hombres lo sean.
Pero, dado que nada menos que el buen Espíritu de Dios
en lo íntimo del hombre puede llevarnos a tal condición,
Dios ha dado a cada hombre una medida de este Espíritu para iluminar su
entendimiento y guiarlo en el camino de la vida y salvación. Y esta medida,
siendo el don gratuito de Dios, es llamada _gracia_ por el apóstol,
tanto en este texto como en muchos otros lugares de la Escritura.

[.discourse-part]
_Pregunta 2._ ¿Dónde se manifiesta la gracia de Dios que trae salvación?

[.discourse-part]
Respuesta: El gran Dios, en Su infinita sabiduría y amor eterno,
ha puesto Su Simiente real o "`planta de renombre`"^
footnote:[Ezequiel 34:29]
en los corazones de los hijos e hijas de los hombres,
porque ese es el principal puesto de mando del alma.
Allí puede encontrarse la gracia de Dios que trae salvación.
Y a partir de ahí (hasta que sea velada por nubes de iniquidad)
se muestra como testigo contra toda injusticia e impiedad.

Así como cada inclinación maligna y tentación que
lleva al pecado se manifiesta en el interior,
así también la gracia de Dios--que es dada a los hombres
para salvarlos del pecado--se manifiesta en el interior.
No hay hombre nacido en el mundo (si ha vivido lo suficiente para cometer pecado)
que no haya sentido y experimentado reprensiones por el pecado dentro de sí mismo;
y estas reprensiones internas son algunas de las apariciones de la gracia,
y son llamadas en la Escritura "`Luz,`" o "`luz verdadera,`"^
footnote:[Juan 1:4,5,7,9; 3:19-20; 11:9-10; Hechos 26:18; 2 Corintios 4:6; Efesios 5:13;
2 Pedro 1:19, etc.]
porque manifiesta toda obra de las tinieblas,
mostrándonos tanto cuándo como en qué hemos hecho mal.
Esto lo ha hecho en todos las épocas.

Dios no se ha dejado a Sí mismo (en ninguna época)
sin testimonio en los corazones de los hombres,
para declarar Su justicia, verdad y fidelidad.
Pero hay una gran diferencia entre la primera manifestación de la gracia,
y el poder de la gracia para salvación; entre la luz de la justicia,
y esa plenitud que nos permite llevar una vida de justicia;
entre una semilla que se siembra, y la planta cuando ha alcanzado su pleno crecimiento.
Sin embargo, lo uno lleva a lo otro;
y aquel que alcanza la plenitud de la gracia es quien llega a vivir sobria,
justa y piadosamente en este mundo.

Se dijo de Jesús, el segundo Adán, que estaba "`lleno de gracia;`"^
footnote:[Juan 1:14]
y podemos creerlo fácilmente por los frutos que produjo en Su vida.
Era humilde, modesto, manso, paciente, apacible, justo y fiel.
Resistió al diablo en todas sus tentaciones, llevó una vida irreprensible,
cumplió toda justicia, y a lo largo de toda Su vida retuvo lo que el primer Adán perdió,
a saber, la imagen de Dios.
Y todo aquel que crezca en gracia hasta alcanzar la estatura
plena (llegando a estar lleno de gracia) puede ser llamado,
como lo fue Job, "`varón perfecto.`"^
footnote:[Job 1:1, 8; 2:3]

Y así como las manifestaciones de la gracia son internas,
así también lo son todos sus descubrimientos, revelaciones y enseñanzas.
Cualquiera que recurra al hombre en busca del verdadero
conocimiento de las cosas de Dios,
acude a una escuela equivocada; porque como dijo Pablo:
"`Lo que se conoce acerca de Dios es evidente dentro de ellos,
pues Dios se lo hizo evidente.`"^
footnote:[Romanos 1:19 NBLA]

Los orgullosos, los codiciosos, los envidiosos y otros impíos,
pueden por un tiempo (incluso por largo tiempo),
experimentar las manifestaciones de la gracia.
Pueden experimentar reprensiones por el pecado;
pero si por tales reprensiones no aprenden justicia, entonces no crecen en la gracia,
ni la gracia crece en ellos.
Tales como estos "`esconden su talento en la tierra,`"^
footnote:[Mateo 25:25]
y con el tiempo (por falta de incremento), les es quitado por completo;^
footnote:[Mateo 25: 28]
y al quedar así sin gracia, llevan una vida malvada e impía en este mundo presente.

[.discourse-part]
_Pregunta 3._ Si la gracia de Dios se manifiesta a todos,
y si es suficiente para hacerlos piadosos, ¿por qué hay tantos impíos?

[.discourse-part]
Respuesta:
Así como la gracia de Dios que trae salvación se manifiesta a todos los hombres,
también las inclinaciones del pecado que conducen
a la destrucción se manifiestan a todos los hombres,
y estas comúnmente se presentan primero.
Todos los hombres hallan en sí mismos inclinaciones malignas y
tentaciones a pecar antes de conocer las reprensiones por el pecado;
y la obra del diablo consiste en hacer que las cosas prohibidas parezcan deseables,
y en hacer que el mundo y sus vanidades parezcan llenos de placer.
Ahora bien, a medida que nuestros afectos son cautivados,
cuando hacemos del mundo nuestro deleite y nos aferramos a él,
entonces nos apartamos de Dios.
Y aunque la gracia se manifieste muchas veces,
aunque el buen Espíritu de Dios contienda por mucho tiempo con nosotros,
aunque encontremos en nosotros mismos muchas reprensiones y correcciones y seamos de
este modo hechos conscientes de que nuestros caminos y obras desagradan a Dios,
con todo, somos propensos a persistir en nuestro curso.
Y por esta continua perseverancia,
el pecado crece en fuerza y llega a tener dominio sobre nosotros,
y el diablo hace que una persona impía sea una carnada para atrapar a otra.
Esta es la verdadera causa de que haya tantos hombres y mujeres impíos en el mundo.

Cuanto más se aleja un hombre de Dios y de la piedad, menos deseo tiene de regresar.
Cuanto más se deleita en las vanidades de este mundo,
menos felicidad halla en las cosas de Dios.
Pero mientras quede una chispa de gracia en su corazón,
el diablo lo sigue y persigue con todas sus tentaciones;
porque no puede verdaderamente llamar suyo a nadie hasta que quede desprovisto de gracia.
Y, de hecho,
habría muchos más hombres y mujeres sin gracia en el mundo
si la maldad no estuviera limitada por una ley externa.

Si estuviéramos sin rey, como lo estuvo Israel en otro tiempo;
o si fuéramos como los habitantes de Lais de quienes se decía,
que vivían "`sin que nadie en aquella región los humillase en cosa alguna,`"^
footnote:[Jueces 18:7 RVG]
hallaríamos que muchos de los que llevan el nombre
de cristianos tienen la naturaleza del diablo,
obrando toda clase de maldad.
Por lo tanto,
concierne sobremanera a todos los que aún sienten las manifestaciones
de la gracia aprender justicia a partir de sus reprensiones,
para que la gracia crezca en ellos y sea su guía; pues nada sino la gracia,
y la obediencia para justicia,
nos diferencia de los peores hombres que cometen acciones viles.
Porque así como toda justicia procede de la plenitud de la gracia,
así la abundancia de maldad procede de la falta de gracia.

[.discourse-part]
_Pregunta 4._ ¿Qué clase de salvación trae la gracia?

[.discourse-part]
Respuesta: Así como las manifestaciones de la gracia son reprensiones por el pecado,
así la salvación que trae la gracia es la salvación del pecado.
Si la gracia enseña a los hombres a vivir sobria,
justa y piadosamente en este mundo presente,
entonces la gracia salva a los hombres buenos del poder del pecado en este mundo presente.

Leemos acerca de un ángel que se apareció a José, y le dijo:
"`No temas recibir a María tu mujer, porque lo que en ella es engendrado,
del Espíritu Santo es.
Y dará a luz un hijo, y llamarás su nombre Jesús,
porque él salvará a su pueblo de sus pecados.`"^
footnote:[Mateo 1:20-21]

Nada desfigura la imagen de Dios en el hombre sino el pecado;
ni nada puede restaurar esa imagen sino ser salvos del pecado.
La muerte al pecado lleva a los hombres de vuelta a su principio.
Pablo les dijo a los efesios que habían sido salvados por gracia;
¿y de qué habían sido salvados,
sino del poder del pecado y de Satanás? ¿Y dónde
experimentaron esta gracia sino en sus propios corazones?
Antes de que estos llegaran (al apartarse de sus iniquidades)
a experimentar la gracia reinando en sus corazones,
andaban, como miles lo hacen ahora, según la corriente de este mundo, no negando,
sino más bien haciendo la voluntad de la carne y de los pensamientos.
Entonces estaban sin Cristo, sin luz, sin vida,
sin un sentido o percepción de algo en ellos que fuera de Dios.
Estaban alejados del gobierno del Espíritu eterno de Cristo en lo íntimo,
y ajenos al pacto prometido, sin conocer más de la ley en sus corazones,
por la cual guiar sus pasos, que los hombres impíos de esta época.

Pero cuando Cristo les dio vida,
y se volvieron a Su buen Espíritu en sus propios corazones para ser guiados por Él,
fueron salvados del pecado, llegaron a tener una nueva naturaleza,
y así fueron hechos nuevas criaturas.
Entonces ya no eran ajenos al gobierno de Cristo, sino que,
al hallar Su ley dentro de sí mismos, se convirtieron en siervos de la justicia,
conciudadanos de los santos, y miembros de la familia de Dios.
Y a este estado bendito podríamos llegar todos,
si tan solo abrazáramos el don de Dios para nuestra salvación,
y nos entregáramos a ser enseñados y guiados por él. De hecho,
esta sería nuestra sabiduría, ya que nada más puede someter a Satanás,
salvarnos del pecado y capacitarnos para vivir sobria,
justa y piadosamente en este mundo presente.

Ser salvados del pecado de este lado de la tumba puede parecer
algo absurdo para los que son ajenos a la salvación de Dios;
pero si los hombres estuvieran tan familiarizados con el poder
de la gracia como muchos lo están con el poder del pecado,
dirían: "`El yugo de Cristo es fácil.`"

¿Acaso no ha sido el dicho común de muchos hombres impíos que enmendarían sus vidas,
si tan solo tuvieran el poder para hacerlo?

Dondequiera que el corazón de alguno, por su perseverancia en el pecado,
se haya llenado de injusticia,
allí el pecado y Satanás tienen tal poder sobre las facultades de su alma,
que no puede resistir las inclinaciones malignas ni las tentaciones,
sino que deben ceder a ellas y dejarse llevar,
aunque sepan que es hacia prácticas malignas.
Pero si el pecado tiene tal dominio sobre hombres impíos,
¿por qué la gracia no habría de poder tener tanto dominio sobre los hombres piadosos?
Ciertamente el buen José halló dicho poder en su alma cuando dijo: "`¿Cómo, pues,
haría yo este grande mal, y pecaría contra Dios?`"^
footnote:[Génesis 39:9]

Al ser la gracia una inspiración divina,
gobierna los corazones de todos los hombres verdaderamente buenos.
Y como el corazón es el principal puesto de mando del alma,
gobierna cada miembro del cuerpo, sujetándolos como con cabestro y freno.
Así, el oído de un hombre lleno de gracia está cerrado
para no escuchar fábulas ni rumores malignos.
Su ojo se aparta de mirar la vanidad.
Su lengua no puede maldecir, jurar, mentir ni participar en ninguna conversación ociosa.
Su mano está impedida de recibir sobornos para pervertir la justicia,
y de tomar cosa alguna que no sea suya.
Sus pies están restringidos de ir con el borracho al exceso,
o con la mujer inmoral a la cámara de la lujuria, o con personas groseras a disturbios,
fiestas o cualquier otra práctica semejante.
Por medio de este dominio que la gracia llega a tener sobre el alma,
el Señor salva a Su pueblo de sus pecados.
Y mientras vivamos en sujeción a su poder, seremos siervos de otro Príncipe;
el pecado y Satanás habrán perdido su dominio sobre nosotros.
Esta es la salvación de Dios, y por medio de ella llegamos a vivir sobria,
justa y piadosamente, en este mundo presente.

[.discourse-part]
_Pregunta 5._ ¿De quién hablaba el apóstol cuando dijo:
"`enseñándonos`"? ¿Se refería al mundo en general, o sólo a algunos en particular?

[.discourse-part]
Respuesta: Cristo fue dado como "`luz a las naciones.`"^
footnote:[Isaías 42:6; 49:6; Isaías 60:3; Lucas 2:32; Hechos 13:47; 26:23]
Y en la medida que Le obedecían, también llegó a ser su líder,
salvándolas de toda impiedad,
y llegaron a vivir bajo el gobierno de Su Espíritu eterno en sus propios corazones.
Sólo a éstas reconoce el Señor como Su pueblo,
y nadie sino ellas pueden llamarlo Señor en verdad.

La gracia "`se ha manifestado a todos los hombres.`"^
footnote:[Tito 2:11]
A cada uno que nace en el mundo le es dado un don de luz en su alma,^
footnote:[Juan 1:9, Romanos 1:19 LBLA]
que le muestra las inclinaciones de pecado^
footnote:[Juan 16:8; Romanos 1:19; Juan 3:19-21]
y lo reprende cada vez que se rinde a ellas.

Toda justicia verdadera se aprende del libro de la ley,
cuando ésta llega a ser escrita en nuestros corazones.
Pero como esta ley es "`la ley del Espíritu de vida,`"^
footnote:[Romanos 8:2]
primero debemos ser vivificados por Cristo y tener el Espíritu de vida,
antes de poder aprender de esa ley.
Y entonces, conforme nos volvemos de la impiedad al don de gracia,
producimos los frutos de la gracia en nuestras vidas.
Pero, puesto que hallamos tan pocos produciendo tales frutos,
podemos concluir ciertamente que, a pesar de que la gracia se manifiesta a todos,
no todos son obedientes a ella.

[.discourse-part]
_Pregunta 6._ Confesamos que hemos experimentado reprensiones internas por el pecado;
que hemos sido frenados,
reprobados y condenados en nosotros mismos después de haber hecho lo malo.
Pero cuando fuertes inclinaciones y tentaciones se han levantado en nuestras mentes,
no hemos hallado nada en nosotros mismos que nos contenga de hacer el mal;
y negar la impiedad y los deseos mundanos con nuestra propia
fuerza parece demasiado difícil para cualquier mortal,
especialmente cuando un pecado ha tomado dominio sobre nosotros.
¿Qué podemos hacer en ese caso?

[.discourse-part]
Respuesta: Si el hombre, con sus propias fuerzas,
pudiera liberar su alma de la potestad del pecado y de Satanás,
regresar a Dios y llevar una vida sobria, justa y piadosa en este mundo presente,
no habría necesidad de un Redentor, ni ocasión para un Salvador,
ni necesidad de un Espíritu vivificante para dar vida a nuestras almas,
ni de que Dios escriba Su ley en nuestros corazones como regla para guiar nuestros pasos.
No habría necesidad de una luz en nuestras almas
que nos muestre dónde el diablo tiende su red,
lanza su carnada, pone su trampa y despliega sus falsas apariencias.
Pero el hombre es tan incapaz de liberar su alma del poder
del pecado y de Satanás sin el poder del Señor,
como Israel fue incapaz de liberarse de la servidumbre del
Faraón sin la poderosa mano y el brazo extendido de Dios.
Por esta razón, la gracia se manifiesta a todos los hombres para ayudarlos.
Y aunque la aparición de la gracia puede parecer un Salvador demasiado pequeño
para liberar nuestras almas de la severa esclavitud al pecado y a Satanás,
y para conducirnos en el camino de la vida y salvación
hasta que lleguemos al final de nuestra carrera,
y vivir bajo el gobierno de Cristo; sin embargo,
no es más pequeña que el libertador de Israel,
quien fue enviado para sacarlos de la esclavitud
de Faraón y conducirlos a la Tierra Prometida.

La ayuda de Israel llegó a través de dos ancianos (siendo el más joven
de ellos de ochenta años) sin más arma que la vara en una de sus manos.
Sin embargo,
por este medio tan pequeño--estando Dios con ellos--sacaron
a seiscientos mil hombres (sin contar mujeres y niños) de
debajo del poder y de la esclavitud de Faraón. Y la gracia,
siendo una inspiración divina,
es ayuda suficiente para sacar a millones de debajo
de la servidumbre al pecado y del poder de Satanás,
si los hombres tan solo confiaran y se entregaran a ella para ser guiados.

Si soy reprendido en mí mismo por decir una mentira,
y tengo en cuenta ese poder que me reprendió,
entonces tendré temor de decir otra mentira.
O si hallo en mí mismo reprensiones por no cumplir mi palabra, o por hacer algo malo,
y tengo en cuenta tales reprensiones, entonces tendré temor de repetir mi necedad,
no sea que las próximas sean más severas.
Y en la medida que este temor santo permanece en nosotros,
aprendemos a negar la impiedad, y al negar la impiedad llegamos a aprender la justicia.
Pero aquellos que hallan en sí mismos reprensiones por el pecado,
pero no les prestan atención, son como los escolares que cargan con libros,
pero no aprenden nada de ellos; estos no son estudiantes en la escuela de la gracia.

Hemos leído que el "`camino de vida son las reprensiones que te instruyen,`"^
footnote:[Proverbios 6:23]
y muchos hombres buenos hoy día reconocerán que,
si no fuera por las reprensiones de la instrucción que sintieron en sus propios corazones,
por las cuales llegaron a negar la injusticia,
nunca habrían llegado a una vida de justicia.
Porque donde las reprensiones por el pecado son recibidas en amor, el Señor no se retira,
sino que sigue con más. Y cuanta más maldad es sometida de este modo,
tanto más llega el alma a ver en la luz del Señor,
y más poder recibe de Él para vencer todo pecado.

Si una plaga no hace que Faraón esté dispuesto a dejar ir a Israel,
encontrará una plaga tras otra, hasta que esté dispuesto.
Y si una reprensión no hace que estemos dispuestos a separarnos de un pecado amado,
tendremos una tras otra, sí, incluso angustia y terror.

Pablo experimentó "`el terror del Señor`"^
footnote:[2 Corintios 5:11 RV1602P]
antes de llegar a experimentar paz con Dios, y paz en su propia consciencia.
Estuvo familiarizado con el juicio antes de llegar a obtener la victoria.
Nada tiene poder para romper las ataduras de la cautividad
y librarnos de la ley del pecado y la muerte,
sino la ley del Espíritu de vida en nuestros propios corazones.

Los mayores enemigos de Israel no fueron sometidos tan pronto como salieron de Egipto,
sino cuando llegaron a la Tierra Prometida;
tampoco el cuerpo del pecado se debilita apenas nos alejamos de la injusticia,
sino más bien cuando entramos en la vida de justicia, con la gracia como nuestro líder,
así como Josué lo fue para ellos.
Porque el pecado no puede mantenerse ante la presencia de la justicia,
del mismo modo que los cananeos no pudieron mantenerse ante la presencia de Josué.

Y si algún pecado ha tomado dominio sobre nosotros,
y sus violentas inclinaciones se levantan contra nosotros,
entonces es el momento de "`estar quietos, Jehová peleará por vosotros.`"^
footnote:[Éxodo 14:14]
Porque conforme nuestros corazones vayan siendo poseídos por la gracia, entonces,
como dicen las Escrituras: "`vendrá el enemigo como río,
mas el Espíritu de Jehová levantará bandera contra él`"^
footnote:[Isaías 59:19]
en el corazón.

La contienda del Señor no es (como los hombres imaginan vanamente) contra el pecador,
sino contra el autor del pecado.
Sus apariciones son todas en amor para salvar al pecador,
y Sus juicios son para debilitar la fuerza del pecado.
Porque, una vez que un hombre es liberado del pecado,
está tan dispuesto a llevar una vida justa como cualquier
impío puede estarlo a llevar una vida malvada;
y su gozo es mucho mayor, aunque el mundo no pueda verlo.

[.discourse-part]
_Pregunta 7._ ¿Qué puede ser llamado, verdadera y correctamente, una "`vida sobria,
justa y piadosa`"?

[.discourse-part]
Respuesta: Muchos, en cierta medida, pueden estar familiarizados con una vida sobria;
pero rara vez se considera una vida justa y piadosa.

Una especie de devoción que consiste en escuchar sermones,
leer buenos libros y cumplir con los deberes familiares,
ha sido considerado durante muchos siglos como piedad;
y aquellos que practican tales cosas han sido llamados justos.
Estas cosas no deben ser desalentadas cuando son hechas con sinceridad;
pero no son la verdadera naturaleza de la justicia y la piedad.
Esto, y mucho más, podría haberse hallado entre los escribas y los fariseos, sin embargo,
Jesús les dijo a Sus discípulos:
"`Si vuestra justicia no fuere mayor que la de los escribas y fariseos,
no entraréis en el reino de los cielos.`"^
footnote:[Mateo 5:20]

¿Quién hay entre los llamados cristianos que, un día de cada siete,
no se ocupe de algo llamado piedad?
Pero la mayor parte de estos no han aprendido a negar la impiedad.
Y aquellos que no han aprendido a negar la impiedad,
están aún lejos de la vida justa y piadosa que nuestro
Señor Jesucristo enseña a todos sus seguidores.
Porque cualquiera que piense alcanzar una vida justa y piadosa,
de otro modo que no sea por las enseñanzas de gracia en su propio corazón,
engaña a su propia alma.

Los hombres pueden cortar u obstaculizar el crecimiento
de muchas ramas de iniquidad que aparecen externamente,
pero no pueden quitar la causa que está dentro; y mientras la causa no sea eliminada,
no puede haber completa cura.
Ahora bien, así como la gracia tiene una Fuente, la iniquidad tiene una raíz,
y el hacha que hiere esa raíz está en las manos de Cristo.
¿Y qué es el hacha, sino "`la ley del Espíritu de vida;`"^
footnote:[Romanos 8:2]
la ley de justicia dentro de nosotros?
Esto obró una perfecta cura en Pablo.
Esto lo hizo un hombre libre, un hombre bueno y un ministro del evangelio;
y eso que curó a Pablo y lo libró del poder del pecado,
es suficiente para hacer lo mismo por todos los hombres.

Pablo dijo: "`Andad en el Espíritu; y no cumpliréis las concupiscencias de la carne.`"^
footnote:[Gálatas 5:16 RV1602P]
Este es el único remedio.
Este es el ungüento que cura el alma.
¿Y qué es andar en el Espíritu,
sino seguir la guía de la gracia en nuestros propios corazones?
Porque la gracia, conforme llega a tener dominio sobre nosotros,
derriba todos los pensamientos altivos, abate el orgullo, expulsa la codicia,
no le da cabida a la ira, y nos reduce a un estado tranquilo y pacífico.
La gracia no nos permitirá hacer nada injusto, ni decir una mala palabra,
porque ella es el prometido Espíritu que "`guía a toda verdad,`"^
footnote:[Juan 16:13]
guía fuera de todo error, y así trae en verdad la salvación.

Ningún hombre puede llevar una vida justa hasta que el Espíritu
justo llegue a tener toda la posesión de su corazón;
porque del buen tesoro del corazón procede toda bondad.
El Espíritu es nuestro guía, y siendo este Espíritu de una naturaleza divina,
nos hace ser de mente celestial.

Nada excede la justicia de los escribas y fariseos,
sino la justicia que procede del Espíritu recto en
nuestros corazones--esta no es nuestra propia justicia,
sino la justicia de Cristo.
Y así como el mal procede del corazón donde el espíritu
maligno de este mundo tiene posesión,
también el amor a todos los hombres procede del corazón
donde el buen Espíritu de Dios ha llegado a permanecer.
Pero esta permanencia del Espíritu no es experimentada hasta que,
renunciando a la impiedad y a los deseos mundanos, el espíritu de este mundo es negado,
y de este modo el corazón es limpiado.
Entonces, y no antes, llegamos a conocer a "`Jehová, justicia nuestra.`"^
footnote:[Jeremías 23:6; 33:16]

Y puesto que esta reforma viene únicamente por la gracia de nuestro Señor Jesucristo,
permítanme decir con el profeta: "`A todos los sedientos: Venid a las aguas`"^
footnote:[Isaías 55:1]
¡y beban!
Todo aquel que tenga un deseo en su alma tras la justicia,
¡vuélvase a la gracia de Dios en su propio corazón! El agua
a la que el profeta invitó a todas las almas sedientas,
no es otra sino la que da Cristo.
Aquel que beba de esta agua no tendrá sed jamás,
sino que tiene (como muchos pueden testificar hoy) un manantial en sí mismo,
no solo brotando, sino saltando para vida eterna.

La gracia de Dios es un don gratuito, sin dinero y sin precio.
Nada se requiere de parte del hombre sino escucharla y seguir su consejo.
"`Oíd,`" dice el profeta, "`y vivirá vuestra alma.`"^
footnote:[Isaías 55:3]
Adán, por prestar atención a las inclinaciones malignas, murió a la justicia,
y así también todos los hombres impíos. Pero el que presta atención a la voz de la gracia,
vive para la justicia; y a partir de esa Fuente que tiene en sí mismo,
lleva una vida sobria, justa y piadosa en este mundo presente.

[.discourse-part]
_Pregunta 8._ ¿No fueron dadas las Escrituras para nuestro aprendizaje,
y no son acaso una regla de justicia suficiente?

[.discourse-part]
Respuesta: Las Escrituras son, ciertamente, una buena regla;
pero ¿quién puede andar en esta regla,
a menos de que esté lleno del buen Espíritu de Dios?

La casa de Jacob no sólo tenía diez mandamientos escritos en tablas de piedra,
sino que también tenía muchos otros estatutos y preceptos escritos en sus libros,
que procedían de un Juez justo.
Estos no sólo eran leídos, sino también explicados cada día de reposo,
para que pudieran caminar por sendas de justicia.
Pero a pesar de que Israel tenía las palabras de Dios en sus libros,
muchos no tenían el temor de Dios en sus corazones, y así,
aunque tenían un gran celo por su adoración externa y forma de devoción,
eran impíos en sus vidas y conducta.

¿Y qué diré de nosotros, que somos llamados cristianos?
Tenemos las palabras de Dios, las palabras de los profetas,
las palabras de Cristo y las palabras de los apóstoles en nuestro libro.
Tenemos grandes leyes de justicia, pero ¿guiamos nuestros pasos por esta regla?
¿Podemos hacerlo?

Que aquellos que dicen que las Escrituras son nuestra única regla,
examinen su capacidad para andar según esta regla.
¿Son ustedes luz para el mundo?
¿Están tan lejos de cometer adulterio, que ni siquiera tienen un pensamiento lujurioso?
¿Pueden abstenerse de herir cuando son heridos?
¿Pueden darle su capa al que injustamente les quita su túnica?
¿Pueden amar a sus enemigos?
¿Pueden bendecir a los que los maldicen?
¿Pueden hacer el bien a los que los aborrecen?
¿Pueden orar por los que los ultrajan?
¿Se preocupan por lo que han de comer o beber, o lo que han de vestir?
¿Pueden hacer a todos los hombres tal como quisieran que ellos les hicieran a ustedes?
Este es el yugo de Cristo;
¿pueden inclinar su corazón y su mente a él? Esta es la carga de Cristo,
¿pueden llevarla?
Él dijo: "`Mi yugo es fácil y ligera Mi carga,`"^
footnote:[Mateo 11:30]
pero si estas cosas son demasiado duras y pesadas,
es porque aún no conocen Su gracia y Su Espíritu.
Tienen nombre de cristianos, pero aún no están en la naturaleza cristiana.
Tienen una regla escrita, pero no tienen el poder para andar conforme a su regla.
Entonces, ¿de qué les sirve tener esa regla escrita?

Si realmente deseamos andar conforme a la regla de la Escritura,
si en verdad tenemos la intención de guardar los mandamientos de nuestro Señor,
y si realmente deseamos llevar una vida justa y piadosa en este mundo presente,
debemos volvernos a la gracia de Dios en nuestros propios corazones;
pues sólo la gracia da poder para cumplir esta regla.
La plenitud de gracia que habitaba en Cristo hizo que todas estas cosas fueran fáciles
para Él. Y a medida que crecemos en gracia y llegamos a ser llenos de ella,
esas cosas también se hacen fáciles para nosotros.
La gracia hace morir el pecado, y cuando el pecado está muerto,
nada es más fácil que llevar una vida justa.

[.discourse-part]
Objeción: Pero algunos podrían decir:
"`Nuestra vida y salvación no dependen de las obras de justicia, sino de la fe.
Creemos, y por ello esperamos ser salvos.`"

[.discourse-part]
Respuesta: Sé que aquí es donde la mayoría de los hombres han puesto su dependencia,
y todos asumen que poseen la fe salvadora.
Pero ¿es la suya la fe la que "`purifica los corazones,`"^
footnote:[Hechos 15:9]
y hace de sus cuerpos templos aptos para el Espíritu Santo de Dios?

Pablo puso a los corintios a examinarse a sí mismos,
para la prueba y comprobación de su fe;
y sería sabio si todos los que se consideran creyentes
pusieran a prueba su fe por el mismo criterio.
"`Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"^
footnote:[2 Corintios 13:5]

¿Cómo podemos conocer al único Dios verdadero si no experimentamos Su presencia?
¿Cómo podemos conocer a nuestro Salvador si Él no se encuentra dentro de nosotros,
salvándonos de nuestros enemigos espirituales,
así como Josué estaba en el campamento de Israel para salvarlos de sus enemigos externos?
Y esta es la vida eterna, no oír hablar acerca de un Dios y un Salvador,
sino conocerlo a Él, sentir Su poder,
y llegar a ser testigos de Su salvación. Estos son los verdaderos creyentes,
pues sus ojos han visto aquello en lo que creen.

La fe y las obras de justicia van de la mano.
Aquel que tiene una, tiene ambas, y la gracia es la fuente de donde proceden las dos.
El incrédulo, el impío y el que carece de gracia, no tiene ninguna.

[.discourse-part]
_Pregunta 9._ Si la gracia interior y espiritual es suficiente
para enseñarnos nuestro deber hacia Dios y hacia el hombre,
y para establecernos en justicia, ¿por qué entonces había un ministerio externo,
y para qué fin fueron dados a la iglesia los apóstoles, profetas, evangelistas,
pastores y maestros?

[.discourse-part]
Respuesta:
Pablo le dijo al rey Agripa que él había sido puesto "`por ministro y testigo.`"^
footnote:[Hechos 26:16]
Él era testigo de la poderosa operación de la gracia en su propia alma,
y por eso podía decir a los demás lo que podía hacer por ellos.

En el estado de degeneración,
todos los hombres son ajenos a la gracia y no conocen al Señor.
La obra del ministerio es abrir el entendimiento de tales personas,
y volverlos a este Maestro celestial.
Pablo fue enviado "`para que +++[+++los hombres]
se conviertan de las tinieblas a la luz, y de la potestad de Satanás a Dios,
para que reciban, por la fe que es en mí,
perdón de pecados y herencia entre los santificados.`"^
footnote:[Hechos 26:17-18]

Algunos fueron enviados para plantar, otros fueron enviados para regar,^
footnote:[1 Corintios 3:5-8]
para que ninguna planta se marchitara antes de llegar a estar arraigada y cimentada.
Pero encontramos, que incluso en los tiempos antiguos,
algunos se volvieron de lo que habían alcanzado, porque no se aferraron a su Guía;
y con éstos, Pablo se vio forzado a sufrir dolores de parto,
hasta que Cristo fuera formado en ellos.^
footnote:[Ver Gálatas 4:19]
Porque, así como las plantas no quedan arraigadas tan pronto como son plantadas,
tampoco los hombres se establecen en justicia tan pronto como se apartan de la injusticia.
Por lo tanto, los fuertes deben velar por los débiles,
y tenderles una mano en sus tribulaciones hasta que lleguen, en unidad del Espíritu,
"`a un varón perfecto, a la medida de la estatura de la plenitud de Cristo.`"^
footnote:[Efesios 4:13; Ver también Colosenses 1:28]
Entonces ya no hay necesidad de un ministerio externo;
porque esta perfección se experimenta cuando el Espíritu
recto llega a tener todo el gobierno en nosotros.

Pero, ¿quiénes son aptos para plantar y para regar?
Ningún impío, pues éstos no tienen el Espíritu de Jesús,
ni conocen en sí mismos el camino de la salvación de Dios,
y por tanto no son aptos para dirigir a otros o tenderles una mano.
Pero los verdaderos ministros son aquellos que, como Pablo,
han experimentado aquello que testifican,
han viajado ellos mismos en el camino de la salvación de Dios, y han llegado,
mediante de las muchas enseñanzas de la gracia,
a tal fuerza y perfección que pueden "`renunciar a la impiedad y a los deseos mundanos,
y vivir en este presente mundo sobria, justa y piadosamente.`"^
footnote:[Tito 2:12]
