== Capítulo III. La Gracia que Trae Salvación

La mayoría de los hombres ha aprendido a hablar bien de la gracia,
pero pocos pueden decir qué es o dónde se puede encontrar.
Muchos reconocerán que ella es el don de Dios; sin embargo,
dicen haberla recibido de los labios de los hombres.
Varios están persuadidos de que toda maldad brota de la falta de gracia,
pero a través de la ignorancia desatienden sus apariciones dentro de sí mismos.
Muchos están convencidos de que, si la gracia fuera su líder,
sería suficiente para preservarlos de pecados grandes,
pero estos no pueden creer que sea suficiente para salvarlos de todo pecado.
Todo lo cual muestra claramente, que lo bueno que dicen de la gracia es de oídas,
y no por experiencia.

Este pequeño tratado muestra: 1) qué es la gracia, 2) dónde se puede encontrar,
3) cómo se convierte en el líder del hombre, 4) cómo es que salva del pecado,
y por lo tanto efectúa la verdadera salvación del hombre.
Porque cualquiera que sea salvo del pecado aquí,
ciertamente será salvo de la muerte y de la condenación en lo por venir;
y que muchos puedan llegar a ser testigos de esta salvación, es el deseo de,

[.signed-section-signature]
Hugh Turford.

[.asterism]
'''

Pablo, un apóstol de Jesucristo, escribiéndole a Tito, el primer obispo de Creta,
dijo lo siguiente:
"`La gracia de Dios que trae salvación se ha manifestado a todos los hombres,
enseñándonos que, renunciando a la impiedad y a las concupiscencias mundanas,
vivamos en este presente mundo sobria, justa y piadosamente.`"^
footnote:[Tito 2:11]
A partir de estas declaraciones de peso, surgen las siguientes preguntas:

[.discourse-part]
_Pregunta 1._ ¿Qué es la gracia de Dios?

[.discourse-part]
Respuesta: La gracia de Dios, que trae Salvación,
es nada menos que una inspiración divina,
un don de Dios para los hijos e hijas de los hombres, un adversario del diablo,
un destructor del pecado, y lo que salva a la humanidad de eso mismo.

El don de gracia, bajo la administración del evangelio,
es el cumplimiento de ese pacto que Dios (por medio de la boca de Jeremías,
Su profeta) prometió hacer con la casa de Jacob,
que "`Él escribiría Su ley en sus corazones, y pondría Su Espíritu en sus entrañas;`"^
footnote:[Jeremías 31:33]
para que Su pueblo tuviera una ley de justicia dentro
de ellos mismos para guiar sus pasos.

Así como los príncipes de la tierra señorean y gobiernan
a su pueblo por medio de una ley externa,
así el Señor determinó señorear y gobernar a Su pueblo por medio de una ley interna.
Ellos no tienen necesidad de buscar entre las páginas de
un libro para saber cómo andar en los caminos rectos,
como lo hizo la simiente de Abraham bajo el primer pacto;
sino que al mirar la "`ley del Espíritu de vida en Cristo Jesús`"^
footnote:[Romanos 8:2]
en sus propios corazones, entenderán qué está bien y qué está mal,
qué deben hacer y qué no deben hacer, qué es justo y qué es injusto,
qué le agrada a Dios y qué no.
Porque esta "`ley es luz`"^
footnote:[Proverbios 6:23]
que alumbra las almas de los hombres,
como el sol en el firmamento alumbra nuestras casas,
mostrando lo que está limpio y lo que está sucio,
lo que puede permanecer y lo que necesita ser barrido.

Porque, así como Dios hizo al hombre en el principio humilde, dócil, manso,
misericordioso, puro, amable, justo y fiel,
Él desea que todos los hombres sean así. Pero debido a que nada menos que el buen Espíritu
de Dios en lo interno del hombre puede llevar a cualquiera de nosotros a tales cualidades,
Dios le ha dado a cada hombre una medida de este Espíritu para iluminar su entendimiento,
y guiarlo en el camino de la vida y salvación. Y esta medida,
siendo el don gratuito de Dios, es llamada _gracia_ por el apóstol,
tanto en este texto como en muchos otros lugares de la Escritura.

[.discourse-part]
_Pregunta 2._ ¿Dónde aparece la gracia de Dios que trae salvación?

[.discourse-part]
Respuesta: El gran Dios, en Su infinita sabiduría y amor eterno,
ha puesto Su Simiente real o "`planta de renombre`"^
footnote:[Ezequiel 34:29]
en los corazones de los hijos e hijas de los hombres,
porque ese es el principal puesto de mando del alma.
Allí se puede encontrar la gracia de Dios que trae salvación. Y a partir
de ahí (hasta que las nubes de iniquidad la velan) se muestra a sí misma
como un testigo en contra de toda injusticia e impiedad.

Así como cada inclinación maligna y tentación que lleva al pecado aparece dentro,
así la gracia de Dios--que es dada a los hombres
para salvarlos del pecado--también aparece dentro.
No hay un hombre nacido en el mundo (si ha vivido lo suficiente para cometer pecado)
que no haya sentido y experimentado reprimendas por el pecado dentro de sí mismo;
y estas reprensiones internas son algunas de las apariciones de la gracia,
y son llamadas en la Escritura "`Luz,`" o "`luz verdadera,`"^
footnote:[Juan 1:4,5,7,9:3:19-20; 11:9-10; Hechos 26:18; 2 Corintios 4:6; Efesios 5:13;
2 Pedro 1:19, etc.]
porque manifiesta cada obra de las tinieblas,
mostrándonos cuándo y dónde hemos hecho algo mal.
Esto lo ha hecho en todos los siglos.

Dios no se dejó a Sí mismo (en ninguna era) sin un testigo en los corazones de los hombres,
para declarar Su justicia, verdad y fidelidad.
Pero hay una gran diferencia entre la primera aparición de la gracia,
y el poder de la gracia que lleva a salvación; entre la luz de la justicia,
y esa plenitud que nos permite llevar una vida de justicia;
entre una semilla que se siembra, y una planta cuando llega a su crecimiento pleno.
Sin embargo, el uno lleva al otro;
y es aquel que alcanza la plenitud de la gracia el que llega a vivir sobria,
justa y piadosamente en este mundo.

Se dijo de Jesús, el segundo Adán, que Él estaba "`lleno de gracia;`"^
footnote:[Juan 1:14]
y podemos creerlo fácilmente por los frutos que Él produjo en Su vida.
Él era humilde, modesto, manso, paciente, apacible, justo y fiel.
Resistió al diablo en todas sus tentaciones, llevó una vida irreprensible,
cumplió toda justicia,
y en el transcurso de toda Su vida retuvo lo que el primer Adán perdió, a saber,
la imagen de Dios.
Y cualquiera que crezca en gracia hasta alcanzar la estatura
plena (siendo lleno de gracia) puede ser llamado,
como Job, "`hombre perfecto.`"^
footnote:[Job 1:1, 8; 2:3]

Y así como las apariciones de la gracia son internas,
también lo son todos sus descubrimientos, revelaciones y enseñanzas.
Cualquiera que recurra al hombre en búsqueda del
verdadero conocimiento de las cosas de Dios,
está yendo a la escuela equivocada; porque como dijo Pablo:
"`Lo que se conoce acerca de Dios es evidente dentro de ellos,
pues Dios se lo hizo evidente.`"^
footnote:[Romanos 1:19]

Los orgullosos, los idólatras, los envidiosos, y otras personas impías,
pueden experimentar por un tiempo (incluso por un largo tiempo),
las apariciones de la gracia.
Pueden experimentar reprensiones por el pecado;
pero si por medio de esas reprensiones no aprenden justicia,
entonces no crecen en gracia, ni la gracia crece en ellos.
Tales como estos "`esconden su talento en la tierra,`"^
footnote:[Mateo 25:25]
y con el tiempo (por falta de incremento), les es quitado;^
footnote:[Mateo 25: 28]
y entonces al quedar sin gracia, llevan una vida malvada e impía en este mundo presente.

[.discourse-part]
_Pregunta 3._ Si la gracia de Dios aparece a todos,
y si es suficiente para hacerlos piadosos, entonces ¿por qué hay tantos impíos?

[.discourse-part]
Respuesta: Así como la gracia de Dios que trae salvación aparece a todos los hombres,
también las inclinaciones del pecado que conducen
a la destrucción aparecen a todos los hombres,
y estas comúnmente aparecen primero.
Todos los hombres encuentran inclinaciones malignas y tentaciones
en sí mismos a pecar antes de conocer las reprensiones por el pecado;
y el trabajo del diablo es hacer que las cosas prohibidas parezcan deseables,
y que el mundo y sus vanidades se muestren llenos de placer.
Ahora, cuando nuestros afectos llegan a ser cautivados,
cuando hacemos del mundo nuestro deleite y nos aferramos a él,
entonces nos apartamos de Dios.
Y aunque la gracia pueda aparecerse muchas veces,
a pesar de que el buen Espíritu de Dios pueda luchar por mucho tiempo con nosotros,
aunque encontremos en nosotros mismos muchas reprensiones y correcciones,
y seamos de este modo hechos sensibles de que nuestros caminos y obras desagradan a Dios,
sin embargo, somos propensos a persistir en nuestro curso.
Y por medio de esta continua perseverancia,
el pecado se hace fuerte y llega a tener dominio sobre nosotros,
y el diablo hace que una persona impía sea una carnada para atrapar a otra.
Esta es la razón por la que tenemos tantos hombres y mujeres impíos en el mundo.

Cuanto más se aleja un hombre de Dios y de la piedad, menos deseo tiene de regresar.
Cuanto más se deleita en las vanidades de este mundo,
menos felicidad ve en las cosas de Dios.
Pero mientras permanezca una chispa de gracia,
el diablo lo sigue y persigue con todas sus tentaciones;
porque él no puede verdaderamente llamar suyo a nadie,
hasta que quede sin nada de gracia.
Y, de hecho,
habría muchos más hombres y mujeres sin gracia en el mundo si la
maldad no estuviera limitada por una ley externa.

Si estuviéramos sin rey (como lo estuvo Israel en los días de los jueces);
o si fuéramos como los habitantes de Lais de quienes se decía,
"`no había gobernante humillándolos en nada en aquella tierra,`"^
footnote:[Jueces 18:7]
encontraríamos que muchos de los que llevan el nombre
de cristianos tienen la naturaleza del diablo,
obrando toda clase de maldad.
Así que les concierne a todos los que aún sienten las apariciones de la gracia,
aprender justicia a partir de sus reprensiones,
para que la gracia pueda crecer en ellos y ser su guía; porque nada más que la gracia,
y la obediencia para justicia,
nos diferencia de los peores hombres que cometen acciones viles.
Porque, así como toda justicia procede de la plenitud de la gracia,
también la abundancia de maldad procede de la falta de gracia.

[.discourse-part]
_Pregunta 4._ ¿Qué clase de salvación trae la gracia?

[.discourse-part]
Respuesta: Así como las apariciones de la gracia son reprensiones por el pecado,
la salvación que trae la gracia es la salvación del pecado.
Si la gracia enseña a los hombres a vivir sobria,
justa y piadosamente en este mundo presente,
entonces la gracia salva a los hombres buenos del poder del pecado en este mundo presente.

Leemos acerca de un ángel que se le apareció a José, y le dijo:
"`No temas recibir a María tu mujer, porque lo que en ella es engendrado,
del Espíritu Santo es.
Y dará a luz un hijo, y llamarás su nombre Jesús,
porque él salvará a su pueblo de sus pecados.`"^
footnote:[Mateo 1:20-21]

Sólo el pecado desfigura la imagen de Dios en el hombre;
y ser salvos del pecado es lo único que recupera esa imagen.
La muerte del pecado lleva a los hombres de vuelta a su inicio.
Pablo les dijo a los efesios que ellos eran salvos por la gracia;
y ¿de qué fueron salvos,
sino del poder del pecado y de Satanás? Y ¿dónde
experimentaron esta gracia sino en sus propios corazones?
Antes de que estos llegaran (al apartarse de sus iniquidades)
a experimentar la gracia reinando en sus corazones,
ellos caminaron, como miles lo hacen ahora, según la corriente de este mundo, no negando,
sino más bien haciendo la voluntad de la carne y de los pensamientos.
Entonces estaban sin Cristo, sin luz, sin vida,
sin un sentido o percepción de algo en ellos que fuera de Dios.
Ellos estaban alejados del gobierno del Espíritu eterno de Cristo en lo íntimo,
y ajenos al pacto prometido, conociendo tan poco de la ley en sus corazones,
por la cual guiar sus pasos, como los hombres impíos de esta época.

Pero cuando Cristo les dio vida,
y se volvieron a Su buen Espíritu en sus propios corazones para ser dirigidos por Él,
fueron salvados del pecado, y llegaron a tener una nueva naturaleza,
y por lo tanto fueron hechos nuevas criaturas.
Entonces ya no eran ajenos al gobierno de Cristo,
sino que al encontrar Su ley en sí mismos, se hicieron siervos de la justicia,
conciudadanos de los santos, y miembros de la familia de Dios.
Y a este estado bendito podríamos llegar todos,
si tan solo abrazáramos el don de Dios como nuestra salvación,
y nos entregáramos para ser enseñados y guiados por él. De hecho,
esta sería nuestra sabiduría, ya que nada más puede someter a Satanás,
salvarnos del pecado, y permitirnos vivir sobria,
justa y piadosamente en este mundo presente.

Ser salvado del pecado de este lado de la tumba puede parecer
algo absurdo para los que son ajenos a la salvación de Dios;
pero si los hombres estuvieran familiarizados con el poder de la gracia,
como muchos están familiarizados con el poder del pecado, dirían:
'`El yugo de Cristo es fácil.`'

¿No ha sido este el dicho común de muchos hombres impíos,
que ellos rectificarían sus vidas, sin tan sólo tuvieran el poder?

Dondequiera que el corazón de alguien, por medio de la perseverancia en el pecado,
se haya llenado de injusticia,
allí el pecado y Satanás tienen tal poder sobre las facultades de sus
almas que no pueden resistir las inclinaciones malignas y las tentaciones,
sino ceden a estas y se dejan llevar, aunque saben que son prácticas malignas.
Pero si el pecado tiene tal dominio sobre hombres impíos,
¿por qué la gracia no puede tener tanto dominio sobre los hombres piadosos?
Ciertamente José encontró ese poder en su alma, cuando dijo: "`¿Cómo, pues,
haría yo este grande mal, y pecaría contra Dios?`"^
footnote:[Génesis 39:9]

La gracia, al ser una inspiración divina,
gobierna los corazones de todos los hombres verdaderamente buenos.
Y como el corazón es el principal puesto de mando del alma,
ella gobierna cada miembro del cuerpo, sujetándolos como con un cabestro y freno.
Así el oído de un hombre de gracia es cerrado para
no escuchar las fábulas y los informes malignos.
Su ojo es apartado de mirar la vanidad.
Esta gracia no le permite a su lengua maldecir, jurar, mentir,
o participar en cualquier conversación ociosa.
Su mano es restringida y por lo tanto no puede recibir sobornos para pervertir la justicia,
ni tomar ninguna cosa que no sea suya.
Sus pies son restringidos y no pueden ir con el borracho al exceso,
o con la mujer inmoral a la cámara del desenfreno,
o con personas groseras para hacer disturbios, fiestas, o cualquier otra cosa similar.
Por medio de este dominio que la gracia llega a tener sobre el alma,
el Señor salva a Su pueblo de sus pecados.
Y mientras vivamos en sujeción a su poder, seremos sirvientes a otro Príncipe;
el pecado y Satanás habrán perdido su dominio sobre nosotros.
Esta es la salvación de Dios, y por medio de ella llegamos a vivir sobria, justa,
y piadosamente, en este mundo presente.

[.discourse-part]
_Pregunta 5._ ¿De quién estaba hablando el apóstol cuando dijo,
"`enseñándonos`"? ¿Se refería al mundo en general, o sólo a algunos particulares?

[.discourse-part]
Respuesta: Cristo fue dado como "`una luz a las naciones;`"^
footnote:[Isaías 42:6; 49:6; Isaías 60:3; Lucas 2:32; Hechos 13:47; 26:23]
y conforme Le obedecieron, también llegó a ser su líder fuera de toda impiedad,
y llegaron a vivir bajo el gobierno de Su Espíritu eterno en sus propios corazones.
Sólo a éstos el Señor reconoce como Su pueblo,
y nadie sino ellos pueden llamarlo Señor en verdad.

La gracia "`se ha manifestado a todos los hombres.`"^
footnote:[Tito 2:11]
Todos los que nacen en el mundo reciben un don de luz en su alma,^
footnote:[Juan 1:9]
que les muestra las inclinaciones de pecado,^
footnote:[Juan 16:8; Romanos 1:19; Juan 3:19-21]
y los reprende cada vez que se rinden ante ellas.

Toda justicia verdadera se aprende del libro de la
ley cuando llega a ser escrita en nuestros corazones.
Pero como esta ley es "`la ley del Espíritu de vida,`"^
footnote:[Romanos 8:2]
primero debemos ser vivificados por Cristo y tener el Espíritu de vida,
antes de que podamos aprender de esa ley.
Y entonces, a medida que nos volvemos de la impiedad al don de gracia,
producimos los frutos de la gracia en nuestras vidas.
Pero puesto que encontramos muy pocos produciendo tales frutos,
podemos ciertamente concluir que, a pesar de que la gracia aparece a todos,
no todos son obedientes a ella.

[.discourse-part]
_Pregunta 6._ Confesamos que hemos sentido reprensiones internas por el pecado;
hemos sido frenados, reprobados,
y condenados en nosotros mismos después de haber hecho lo malo.
Pero cuando fuertes inclinaciones y tentaciones se han levantado en nuestras mentes,
no hemos encontrado nada en nosotros mismos que nos impida hacer el mal;
y pareciera muy difícil para cualquier mortal negar la impiedad
y los deseos mundanos con nuestra propia fuerza,
especialmente cuando un pecado ha tomado dominio sobre nosotros.
¿Qué podemos hacer en ese caso?

[.discourse-part]
Respuesta: Si el hombre, con sus propias fuerzas,
pudiera librar su alma de la potestad del pecado y de Satanás, regresar a Dios,
y llevar una vida sobria, justa y piadosa en este mundo presente,
no habría necesidad de un Redentor o Salvador,
ni sería necesario que el Espíritu vivificante diera vida a nuestras almas,
o que Dios escribiera Su ley en nuestros corazones como regla para guiar nuestros pasos.
No habría necesidad de una luz en nuestras almas
para mostrarnos dónde el diablo extiende su red,
lanza su carnada, pone su trampa, y expone sus falsas apariencias.
Pero el hombre es tan incapaz de librar su alma del
poder del pecado y de Satanás sin el poder del Señor,
como Israel fue incapaz de librarse de la servidumbre del
Faraón sin la poderosa mano y brazo extendido de Dios.
Por esta razón, la gracia aparece a todos los hombres para ayudarlos.
Y aunque la aparición de la gracia puede parecer un Salvador demasiado pequeño para
poder liberar nuestras almas de una esclavitud tan grande al pecado y a Satanás,
y para conducirnos en el camino de la vida y salvación
hasta que lleguemos al final de nuestra carrera,
para vivir bajo el gobierno de Cristo; sin embargo,
no es más pequeño que el libertador de Israel,
que fue enviado para sacarlos de la esclavitud de
Faraón y conducirlos a la Tierra Prometida.

La ayuda de Israel vino a través de dos ancianos (siendo el más joven de ellos
de ochenta años) sin ningún arma sino con la vara en una de sus manos.
Sin embargo,
a través de este medio tan pequeño--estando Dios con ellos--sacaron
a seiscientos mil hombres (sin contar mujeres y niños) de
debajo del poder y de la esclavitud de Faraón. Y la gracia,
siendo una inspiración divina,
es una ayuda suficiente para sacar a millones de debajo
de la servidumbre de pecado y del poder de Satanás,
si los hombres tan solo confiaran y se entregaran a ella para ser guiados.

Si soy reprobado por haber dicho una mentira, y tengo en cuenta el poder que me reprobó,
entonces tendré temor de decir otra mentira.
O si encuentro en mí mismo reprensiones por no cumplir mi palabra, o por hacer algo malo,
y tengo en cuenta tales reprimendas, entonces tendré temor de repetir mi necedad,
no sea que las próximas sean más agudas.
Y a medida que este temor santo permanece en nosotros, aprendemos a negar la impiedad,
y al negar la impiedad, llegamos a aprender la justicia.
Pero aquellos que encuentran en sí mismos reprobaciones por el pecado,
mas no les prestan atención, son como los escolares que cargan con libros,
pero no aprenden nada de ellos; estos no son estudiantes en la escuela de la gracia.

Hemos leído que el "`camino de vida son las reprensiones que te instruyen,`"^
footnote:[Proverbios 6:23]
y muchos hombres buenos hoy día reconocerán que,
si no fuera por las reprensiones de instrucción que sintieron en sus propios corazones,
por las cuales llegaron a negar la injusticia,
nunca habrían llegado a una vida de justicia.
Porque donde las reprensiones por el pecado se reciben en amor, el Señor no se retira,
sino que nos da más. Y cuanta más maldad se someta de este modo,
más el alma llega a ver en la luz del Señor,
y más poder recibe de Él para vencer todo pecado.

Si una plaga no hace que Faraón esté dispuesto a dejar ir a Israel,
encontrará una plaga tras otra, hasta que esté dispuesto.
Y si una reprimenda no hace que estemos dispuestos a separarnos de un pecado amado,
tendremos una tras otra, sí, incluso angustia y terror.

Pablo conocía "`el terror del Señor`"^
footnote:[2 Corintios 5:11]
antes de experimentar paz con Dios, y paz en su propia consciencia.
Él estaba familiarizado con el juicio antes de llegar a obtener la victoria.
Nada tiene poder para romper las ataduras de la cautividad,
y librarnos de la ley del pecado y la muerte,
sino la ley del Espíritu de vida en nuestros propios corazones.

Los mayores enemigos de Israel no fueron sometidos tan pronto salieron de Egipto,
sino cuando llegaron a la Tierra Prometida;
tampoco el cuerpo del pecado se debilita apenas nos alejamos de la injusticia,
sino más bien cuando llegamos a la vida de justicia, con la gracia como nuestro líder,
así como Josué era el de ellos.
Porque de la misma manera que los cananeos no pudieron
permanecer ante la presencia de Josué,
el pecado tampoco puede permanecer ante la presencia de la justicia.

Y si algún pecado ha tomado dominio sobre nosotros,
y sus violentas inclinaciones se levantan en contra de nosotros,
entonces es hora de "`estar quietos, Jehová peleará por vosotros.`"^
footnote:[Éxodo 14:14]
Porque a medida que nuestros corazones lleguen a ser conquistados por la gracia,
entonces "`vendrá el enemigo como río,
mas el Espíritu de Jehová,`" estando en el corazón, "`levantará bandera contra él.`"^
footnote:[Isaías 59:19]

La controversia del Señor no es (como muchos hombres
imaginan en vano) en contra del pecador,
sino en contra del autor del pecado.
Sus apariciones son todas en amor para salvar al pecador,
y Sus juicios son para debilitar la fuerza del pecado.
Porque una vez que un hombre es libre del pecado,
está tan dispuesto a llevar una vida justa como cualquier
hombre impío podría estar dispuesto a llevar una vida malvada;
y su gozo es mucho mayor, aunque el mundo no puede verlo.

[.discourse-part]
_Pregunta 7._ ¿Qué es verdadera y correctamente una "`vida sobria, justa, y piadosa`"?

[.discourse-part]
Respuesta: Muchos saben, en cierta medida, qué es una vida sobria,
pero muy pocos entienden lo que es tener una vida justa y piadosa.

Se ha considerado durante muchos años como piedad,
una especie de devoción que consiste en escuchar sermones, leer buenos libros,
y realizar deberes familiares; y aquellos que practican tales cosas,
han sido llamados personas justas.
Estas cosas no deben menospreciarse cuando son hechas con sinceridad;
pero no son la verdadera naturaleza de la justicia y la piedad.
Esto y mucho más pudo haberse encontrado entre los escribas y los fariseos, sin embargo,
Jesús les dijo a Sus discípulos "`que si vuestra justicia
no fuere mayor que la de los escribas y fariseos,
no entraréis en el reino de los cielos.`"^
footnote:[Mateo 5:20]

¿Quién entre los llamados cristianos,
no está en la práctica de algo llamado religión un día de cada siete?
Pero la mayor parte de estos aún no han aprendido a negar la impiedad.
Y aquellos que no han aprendido a negar la impiedad,
están aún lejos de la vida justa y piadosa que nuestro
Señor Jesucristo enseña a todos sus seguidores.
Porque cualquiera que piense alcanzar una vida justa y piadosa,
de otro modo que no sea por medio de las enseñanzas de gracia en su propio corazón,
está engañando a su propia alma.

Los hombres pueden cortar u obstaculizar el crecimiento
de muchas ramas de iniquidad que aparecen externamente,
pero no pueden quitar la causa que está dentro; y hasta que sea eliminada la causa,
no puede haber una cura completa.
Ahora, así como la gracia tiene una Fuente,
de la misma manera la iniquidad tiene una raíz,
y el hacha que ataca a esta raíz está en las manos de Cristo.
¿Y qué es el hacha, sino "`la ley del Espíritu de vida`"?^
footnote:[Romanos 8:2]
--una ley de justicia dentro de nosotros.
Esto trajo una perfecta cura en Pablo.
Esto lo hizo un hombre libre, un hombre bueno, y un ministro del evangelio;
y eso que curó a Pablo, y lo libró del poder del pecado,
es suficiente para hacer lo mismo por todos los hombres.

Pablo dijo, "`Andad en el Espíritu, y no satisfagáis los deseos de la carne.`"^
footnote:[Gálatas 5:16]
Este es el único remedio.
Este es el ungüento que cura el alma.
Y qué es andar en el Espíritu,
sino seguir la guía de la gracia en nuestros propios corazones.
Porque la gracia, conforme llega a tener dominio sobre nosotros,
derriba todos los pensamientos altivos, humilla el orgullo, apaga la codicia,
no le da cabida a la ira, y nos lleva a un estado de ánimo tranquilo y pacífico.
La gracia no nos permitirá hacer nada injusto, ni decir una mala palabra,
porque ella es el "`Espíritu de verdad`" prometido que "`guía a toda verdad,`"^
footnote:[Juan 16:13]
nos guía fuera de todo error, y por lo tanto trae salvación en verdad.

Ningún hombre puede llevar una vida justa hasta que un Espíritu
justo llegue a tener toda la posesión de su corazón;
porque es del buen tesoro del corazón que proceden todas las cosas buenas.
El Espíritu es nuestro guía, y al ser de una naturaleza divina,
este guía nos hace tener una mente celestial.

Nada excede la justicia de los escribas y fariseos,
sino la justicia que procede del Espíritu recto en
nuestros corazones--esta no es nuestra propia justicia,
sino la justicia de Cristo.
Y así como el mal procede de un corazón en donde
el espíritu maligno de este mundo tiene posesión,
también el amor a todos los hombres procede de un corazón
donde el buen Espíritu de Dios ha llegado a permanecer.
Pero esta permanencia del Espíritu no es experimentada, hasta que,
al renunciar a la impiedad y a los deseos mundanos, el espíritu de este mundo sea negado,
y de este modo el corazón sea limpiado.
Entonces, y no antes, llegamos a conocer a "`Jehová, justicia nuestra.`"^
footnote:[Jeremías 23:6; 33:16]

Y puesto que esta reforma solo viene por la gracia de nuestro Señor Jesucristo,
permítanme decir con el profeta, "`A todos los sedientos: Venid a las aguas`"^
footnote:[Isaías 55:1]
¡y beban!
Todos los que tengan un deseo en su alma por justicia,
¡vuélvanse a la gracia de Dios en su propio corazón! Esta
agua a la que el profeta invitó a todas las almas sedientas,
no es otra que la que Cristo da.
Quienquiera que beba de esta agua, no tendrá sed jamás,
pero tiene (como muchos pueden testificar hoy en día) una fuente de agua en sí mismo,
que no solamente fluye, sino que salta para vida eterna.

La gracia de Dios es un don gratuito, sin dinero y sin precio.
No se requiere nada de parte del hombre más que escucharlo, y seguir su consejo.
"`Oíd,`" dice el profeta, "`y vivirá vuestra alma.`"^
footnote:[Isaías 55:3]
Adán, al prestar atención a las inclinaciones malignas, murió a la justicia;
asimismo lo hacen todos los hombres impíos. Pero
el que presta atención a la voz de la gracia,
vive para la justicia; y a partir de esa Fuente que tiene en sí mismo,
lleva una vida sobria, justa y piadosa en este mundo presente.

[.discourse-part]
_Pregunta 8._ ¿No fueron dadas las Escrituras para nuestro aprendizaje,
y no son una regla de justicia suficiente?

[.discourse-part]
Respuesta: Las Escrituras son ciertamente una buena regla;
pero ¿quién puede seguir esta regla, a menos de que esté lleno del buen Espíritu de Dios?

La casa de Jacob no solo tenía diez mandamientos escritos en las tablas de piedra,
sino que también tenían muchos otros estatutos y mandamientos escritos en sus libros,
que procedían de un Juez justo.
Estos no solo se leían, sino que también se les explicaban cada día de reposo,
para que ellos pudieran caminar por sendas de justicia.
Pero a pesar de que Israel tenía las palabras de Dios en sus libros,
muchos no tenían el temor de Dios en sus corazones, y, por ende,
aunque tenían un gran celo por su forma externa de adoración y devoción,
eran impíos en sus vidas y conducta.

¿Y qué diré de nosotros que somos llamados cristianos?
Tenemos las palabras de Dios, las palabras de los profetas, las palabras de Cristo,
y las palabras de los apóstoles en nuestro libro.
Tenemos grandes leyes de justicia, pero ¿guiamos nuestros pasos por esta regla?
¿Podemos hacerlo?

Que aquellos que dicen que las Escrituras son nuestra única regla,
examinen su capacidad de caminar según esta regla.
¿Están viviendo como luces para el mundo?
¿Están tan lejos de cometer adulterio que no tienen ni un pensamiento lujurioso?
¿Pueden abstenerse de herir cuando se encuentran heridos?
¿Pueden darle su capa al que le quita su túnica injustamente?
¿Pueden amar a sus enemigos?
¿Pueden bendecir a los que los maldicen?
¿Pueden hacer el bien a los que los odian?
¿Pueden orar por los que los ultrajan?
¿Se preocupan por lo que van a comer o beber, o lo que van a vestir?
¿Pueden hacer a todos los hombres como les gustaría que les hicieran a ustedes?
Este es el yugo de Cristo;
¿pueden inclinar su corazón y su mente a él? Esta es la carga de Cristo,
¿pueden llevarla?
El dijo, "`Mi yugo es fácil y ligera Mi carga,`"^
footnote:[Mateo 11:30]
pero si estas cosas son demasiado duras y pesadas,
es porque aún no conocen Su gracia y Su Espíritu.
Ustedes tienen el nombre de cristiano,
pero aún no se encuentran en la naturaleza cristiana.
Tienen una regla escrita, pero no tienen el poder para seguirla.
¿Entonces de qué les sirve tener esa regla escrita?

Si realmente deseamos caminar según la regla de la Escritura,
si en verdad tenemos la intención de guardar los mandamientos de nuestro Señor,
y si realmente deseamos llevar una vida justa y piadosa en este mundo presente,
debemos volvernos a la gracia de Dios en nuestros propios corazones;
pues solo la gracia da poder para cumplir con esta regla.
La plenitud de la gracia que moraba en Cristo hizo que todas estas cosas fueran fáciles.
Y a medida que crezcamos en gracia y lleguemos a ser llenos de ella,
esas cosas también se harán fáciles para nosotros.
La gracia hace morir el pecado, y cuando el pecado está muerto,
nada es más fácil que llevar una vida justa.

[.discourse-part]
Objeción: Pero algunos pueden decir,
"`nosotros no dependemos de obras de justicia para tener vida y salvación, sino de la fe.
Nosotros creemos, y por lo tanto esperamos ser salvos.`"

[.discourse-part]
Respuesta: Sé que aquí es donde la mayoría de los hombres han puesto su dependencia,
y todos asumen que poseen la fe salvadora.
Pero ¿es su fe la que "`purifica los corazones,`"^
footnote:[Hechos 15:9]
y hace de sus cuerpos templos aptos para el Espíritu Santo de Dios?

Pablo puso a los corintios a examinarse a sí mismos,
para la prueba y comprobación de su fe;
y sería sabio si todos los que se consideran creyentes probaran su fe por el mismo criterio.
"`Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"^
footnote:[2 Corintios 13:5]

¿Cómo podemos conocer al único verdadero Dios si no experimentamos Su presencia?
¿Cómo podemos conocer a nuestro Salvador si Él no se encuentra dentro de nosotros,
salvándonos de nuestros enemigos espirituales,
así como Josué estaba en el campamento de Israel para salvarlos de sus enemigos externos?
Y esta es la vida eterna, no oír hablar de un Dios y un Salvador, sino conocerlo a Él,
sentir Su poder,
y ser testigos vivos de Su salvación. Estos son los verdaderos creyentes,
porque sus ojos han visto lo que ellos creen.

La fe y las obras de justicia van de la mano.
Aquel que tiene la una, tiene ambas, y la gracia es la fuente de donde proceden las dos.
El incrédulo, el impío, y el que carece de gracia, no tiene ninguna.

[.discourse-part]
_Pregunta 9._ Si la gracia interna y espiritual es suficiente
para enseñarnos nuestro deber hacia Dios y al hombre,
y para establecernos en justicia, entonces ¿por qué hubo un ministerio externo,
y para qué fin fueron dados los apóstoles, profetas, evangelistas, pastores,
y maestros a la iglesia?

[.discourse-part]
Respuesta: Pablo le dijo al rey Agripa que él fue puesto "`por ministro y testigo.`"^
footnote:[Hechos 26:16]
Él era un testigo de la operación poderosa de la gracia en su propia alma
y así pudo decir a los demás lo que podría hacer por ellos.

En el estado de degeneración todos los hombres son ajenos a la gracia,
y ellos no conocen al Señor. La obra del ministerio es abrir los entendimientos de tales,
y volverlos a este Maestro celestial.
Pablo fue enviado "`para que los hombres se conviertan de las tinieblas a la luz,
y de la potestad de Satanás a Dios, para que reciban, por la fe que es en mí,
perdón de pecados y herencia entre los santificados.`"^
footnote:[Hechos 26:17-18]

Algunos fueron enviados para plantar, otros fueron enviados para regar,^
footnote:[1 Corintios 3:5-8]
para que ninguna planta se marchitara antes de ser arraigada y cimentada.
Pero encontramos, que incluso en los tiempos antiguos,
algunos se volvieron de lo que habían alcanzado, porque no se aferraron a su Guía;
y con éstos, Pablo se vio forzado a "`sufrir dolores de parto,
hasta que Cristo fuera formado en ellos.`"^
footnote:[Gálatas 4:19]
Porque, así como las plantas no son arraigadas tan pronto como se plantan,
así también los hombres no son establecidos en justicia
tan pronto como se apartan de la injusticia.
Por lo tanto, los que son fuertes deben velar sobre los que son débiles,
y ayudarles en sus tribulaciones hasta que lleguen, en unidad del Espíritu,
"`a un varón perfecto, a la medida de la estatura de la plenitud de Cristo.`"^
footnote:[Efesios 4:13; Ver también Colosenses 1:28]
Entonces no se necesitará de un ministerio externo;
porque esta perfección se experimenta cuando un Espíritu
recto llega a tener todo el gobierno en nosotros.

Sin embargo, ¿quiénes son aptos para plantar y para regar?
Ningún hombre impío, porque estos no tienen el Espíritu de Jesús,
ni conocen el camino de la salvación de Dios en sí mismos,
y por lo tanto no son aptos para dirigir a otros o tenderles la mano.
Pero los verdaderos ministros son aquellos que (como
Pablo) han experimentado eso de lo que testifican,
han viajado en el camino de la salvación de Dios,
y han llegado a través de las muchas enseñanzas de la gracia a tal fuerza y perfección,
que pueden "`renunciar a la impiedad y a los deseos mundanos,
y vivir en este presente mundo sobria, justa y piadosamente.`"^
footnote:[Tito 2:12]
